### ISSUE TITLE
`require` inside a Task is partially broken

### ISSUE THREAD

**Issue by zilti** [boot-clj/boot#100]
I know it's a terrible title, but I'm not sure how to word it correctly. It seems Boot first tries to compile the whole file, and while doing that has the bug that following use case does not work:

```Clojure
(deftask example []
(require 'some-namespace)
(some-namespace/do-something "abc"))
```

The workaround I'm using at the moment is as follows:

```Clojure
(deftask example []
(require 'some-namespace)
(eval `(some-namespace/do-something "abc")))
```

I'm not 100% sure if this is a bug in Boot or in Clojure itself.

**Comment by martinklepsch** [comment]
Hi @zilti, could you elaborate what specifically you are trying to achieve?
Is there a specific reason you don't put the `require` into the `ns` form?

**Comment by zilti** [comment]
I'm writing an application with a server part and a client part and use the 
same build.boot file for it. So I have every task just once, and one "prepare-
server" and a "prepare-client" task to set up the surroundings for the other 
tasks.

**Comment by Deraen** [comment]
This is not a bug in either.

If you need to refer to a var in a namespace which is loaded only during runtime you should manually resolve symbol to var:

```clj
user=> (defn a [] (require 'schema.core) (schema.core/check {} {:a 1})
=> exception
user=> (defn a [] (require 'schema.core) ((resolve 'schema.core/check) {} {:a 1}))
#'user/a
```
