### ISSUE TITLE
Don't require .boot extension for writing boot CLI scripts

### ISSUE THREAD

**Issue by benwbooth** [boot-clj/boot#105]
I really like boot, but it's kind of annoying that all boot CLI scripts have to have a .boot extension, since most editors won't be able to detect them as Clojure scripts without customizing the editor config to detect them. Clojure scripts usually end in .clj, and if I'm writing an executable script, I shouldn't be required to give any extension at all. I guess the .boot extension is how boot distinguishes between calling a script and running a task, but coudn't there be some other way to distinguish between scripts and tasks?

**Comment by alandipert** [comment]
Yes, the .boot extension is how boot distinguishes between script invocation via shebang and running a task.  It is annoying but we haven't figured out another way, definitely open to suggestions.

**Comment by benwbooth** [comment]
What if boot first looks for a matching script name, then if it fails, it tries to run a task matching that name? If you REALLY just want to run a task, you could put a "--" argument before the task name to ensure that it's treated like a task.

**Comment by martinklepsch** [comment]
I personally don't see an issue with that. Maybe information how to setup editors could be part of the README Install section. 

That said there were other people asking be about this so it seems to be at least some source of confusion.

**Comment by benwbooth** [comment]
Setting up editors can be a bit of a hassle. I think the bigger issue is someone might want to write an executable script, but may not want to advertise the implementation details as part of the script name. Or they may want a short script name, and having to type ".boot" at the end is an annoyance.

**Comment by micha** [comment]
I think that the requirement for the `.boot` extension to distinguish scripts may not really be necessary. It's kind of confusing and I remember it had some tricky corner cases. This part of boot is pretty old though, and some new developments have come to light more recently, like using launch4j to build the windows binaries, for example. We can add information from the launch context now that we couldn't do with just a jar file before, like adding the path to the executable as a system property. This may help with the command line parsing, as I think this was one thing that made it more difficult to tell the difference between tasks and files.

If we can find a new way to disambiguate these cases I'd be happy to remove this restriction.

**Comment by micha** [comment]
This is somewhat related to #103 maybe. Like suppose we gave up the entire concept of having a magical file named `build.boot` and instead use shebangs (`#!/usr/bin/env boot`) on Unix and let the user associate whichever file extension they like on Windows? Then instead of `build.boot` on Unix you could have `foo` with the shebang, and instead of doing `boot some-task` you'd do `./foo some-task`?

**Comment by jballanc** [comment]
I was just recently playing around with [Chicken Scheme](http://www.call-cc.org) and saw that the Chicken Scheme interpreter, `csi`, has a `-script` option that can either accept the filename of a script to run, or can be used in the shebang line to make a runnable Chicken Scheme script:

```scm
#!/usr/bin/env csi -script
(
  ;;...your scheme here
)
```

What's really elegant about this is that the name of the file is automatically appended to the shebang line (which is why currently using a boot shebang in `./foo` give a warning about the `foo` task not existing). In other words, if we implement `-script` for boot, then we get the shebang for free!

**Comment by micha** [comment]
@jballanc Unfortunately [it doesn't work on all platforms][1], I don't think?

[1]: http://en.wikipedia.org/wiki/Shebang_%28Unix%29#Portability

**Comment by jballanc** [comment]
@micha I think that caveat is specific to items on the shebang line passed as arguments to the shebang interpreter. The filename is always passed as an additional line AFAIK. For example, make a file named `shebang.sh` like so:

```sh
#!/bin/echo shebang args
Contents
```

...and you should get out `shebang args shebang.sh`. The only question is whether `shebang args` was passed as one arg or two. That is, whether it's equivalent to `/bin/echo "shebang args" shebang.sh` or `/bin/echo shebang args shebang.sh`.

Or, stated another way: if it's good enough for Chicken, it should be good enough for Boot, no? ;-)

**Comment by micha** [comment]
I don't know about Chicken, so I can't say, but if

    #!/usr/bin/env shebang args

ends up being parsed as

    /usr/bin/env "shebang args" shebang.sh

then it will fail to call the `shebang` interpreter and you'll get an error when `env` can't find any `shebang args` in your path.

**Comment by micha** [comment]
For instance:

```
$ uname 
Linux
```
```
$ cat ~/bin/interp 
#!/usr/bin/env bash
for i in "$@"; do echo "<< $i >>"; done
```
```
$ cat foop 
#!/usr/bin/env interp -x
asdf
```
```
$ ./foop 
/usr/bin/env: interp -x: No such file or directory
```

**Comment by jballanc** [comment]
I suppose one solution is just to tell people to use an absolute path in their Boot shebang if they're on such a system...but I realize that's not really a tenable solution. Baring that, I think the only options then are either to peek at the first argument and check to see if it is a file with a shebang, or just require that the first argument always be a script file (either via shebang or passed as first argument on the command-line).

I'd be happy to help implement either solution, as I also have an interest in being able to write Boot scripts without necessarily having to attach `.boot` to the end.

**Comment by micha** [comment]
You mean, like requiring

```
$ boot build.boot repl
```

instead of just

```
$ boot repl
```

?

**Comment by jballanc** [comment]
@micha right, which pretty much sucks. So, I think it should be easy enough to:

1. Check if the first argument matches the path to a file on disk
2. If yes, check if the first line of that file is a shebang with `boot` somewhere in there
3. If yes again, then load it as a boot script regardless of file extension

Is there anything I'm missing as to why this wouldn't work? The only potential problem I can think of is if a file share the same name as a task, but I think that should be relatively rare (also, I think most systems will pass a fully-qualified path for the file, effectively eliminating that possibility).

**Comment by micha** [comment]
@jballanc Thanks for your patience! I think I can understand now. Your method does seem like it will work. I'll do it and see how it goes.
