### ISSUE TITLE
Possible improvement to boot Bash header

### ISSUE THREAD

**Issue by benwbooth** [boot-clj/boot#107]
I opened the boot script in my editor, and noticed the following bash script that loads an embedded Jarfile:

```
#!/usr/bin/env bash
java $BOOT_JVM_OPTIONS -jar $0 "$@"
exit
```

I guess the JAR loader skips the bash section somehow, and starts processing when it finds the PK zip header? Neat trick! However, wouldn't it be better written this way:
```
#!/usr/bin/env bash
exec java $BOOT_JVM_OPTIONS -jar "$0" "$@"
```

I quoted the $0 argument (just in case), removed the exit statement, and used an exec instead. This way, the exit code from java gets returned by the script, and you don't have any bash interpreter overhead while java is running.

**Comment by micha** [comment]
Awesome, yes this seems much better. I'll test this!
