### ISSUE TITLE
add :name "string" to uber task

### ISSUE THREAD

**Issue by gzmask** [boot-clj/boot#116]
In current uber task, there is no way to specify output file name:
https://github.com/boot-clj/boot/blob/master/boot/core/src/boot/task/built_in.clj#L366

each time boot will give random name for the uberjar file and is a bit confusing

**Comment by schmir** [comment]
You can workaround the problem by giving the :file argument to the *jar* (not the uber) task.
I've also reported that in #112.

**Comment by gzmask** [comment]
@schmir Works. Thanks!
