### ISSUE TITLE
Add --uber option to jar, war tasks

### ISSUE THREAD

**Issue by alandipert** [boot-clj/boot#118]
The `uber` task is notoriously slow because it dumps static, exploded dependencies into the fileset on every build.  It does this so subsequent `jar` or `war` tasks can see all the files that need to go into the jar.  See #94 for a full discussion of the problem.

We think the best way to address the problem is by adding an `--uber` option to `jar` and `war`.  That way, instead of needing to explode dependencies into the fileset, these tasks will pack dependencies directly into the jar/war being built, and only this "packed" jar goes on the fileset.

It doesn't feel like a great solution because we're loathe to fix a performance problem between two tasks by combining them.  However, we can't think of a better way, and also think uber jars are probably a special case.

The plan is to have this in for 2.0, whether or not we should also deprecate the `uber` task is a good question.  I think probably yes.

**Comment by bobby** [comment]
One datapoint: I've used the `uber` task with :as-jars to build zips with a lib/*.jar dir (uberzip?).  So the capability of stashing jar'd deps on the fileset is a useful capability, whether tied to `uber` or not.

**Comment by alandipert** [comment]
Refs

**Comment by micha** [comment]
I think the `uber` task is pretty fast now. Feel free to reopen if we want to revisit this.
