### ISSUE TITLE
run REPL with own scripts

### ISSUE THREAD

**Issue by hikoz** [boot-clj/boot#121]
Boot is ignoring cli opts with custom scripts [currently](https://github.com/boot-clj/boot/blob/master/boot/core/src/boot/main.clj#L92-93).
I want to run my REPL with custom scripts like this.
```
boot my.boot repl
```
Is there any problems with reading cli options with custom scripts?

**Comment by micha** [comment]
When you have a standalone script like `my.boot`, boot expects that you don't want to run tasks. You can, however, do this:

_my.boot_

    (defn -main [& args]
      (eval `(boot.core/boot ~@args)))

This will do what you need, I think.

**Comment by micha** [comment]
If this doesn't actually fix your issue, please feel free to reopen the ticket :)

**Comment by hikoz** [comment]
Still cannot call with options like -d but works great, thanks.
