### ISSUE TITLE
[Wishlist] Add new boot task with conscript-like functionality for downloading launcher scripts

### ISSUE THREAD

**Issue by benwbooth** [boot-clj/boot#127]
Scala has a nice tool called [conscript](https://github.com/n8han/conscript) which allows you to download sbt launcher scripts from github into your ~/bin folder. This would allow you to write and distribute command-line scripts written in clojure more easily, since maven/ivy only deals in jar files. AFAIK, there is no equivalent tool for clojure. 

If boot had a task that could simplify writing and distributing scripts for launching clojure jar files, it would be really useful. Also, this could possibly help to solve #105, since you could simply define a new launcher in `boot-clj/boot` called `boot-launch`, or whatever, then use that to launch any clojure script using boot without requiring a .boot extension to differentiate between scripts and tasks.

**Comment by alandipert** [comment]
Yes, this would be awesome!  I have imagined something like this - some combination of task(s) and packaging conventions - that set up `~/.boot/bin` as a "binstub" directory.  I imagine somehow jars supplying an entrypoint (maybe via MAIN-CLASS manifest attribute?), and boot somehow keying on this and putting a stub executable in the binstub directory.  Then the user can add ~/.boot/bin to their PATH and use boot to install executables from Maven as long as they adhere to whatever packaging convention we decide on.  I think Ruby gems offer a system like this too.

Re: #105 it's definitely related; also related is some idea of an "uberboot" packaging technique.  This would be a way to make executables that depended only on java, not on boot.  For instance, an uberjar with a MAIN-CLASS that users could run with `java -jar uberboot.jar some.mainclass`

I can imagine how to implement all these things; what would be especially helpful is a plan for doing them all as a set of cohesive and consistent additions.  They all seem to serve slightly different use cases but are also related in spirit.  Maybe we should share our "dream" scenarios, like the things we wish boot did without respect to whether it's been done or we know it's possible?  Then we could be on the same page about what we want.  After that we can get on the same page about how to do what we all want.

So, what awesome ways do we dream about using boot to share boot scripts/programs?

**Comment by danielsz** [comment]
Keying on the "Main-Class" entry in the manifest looks to me like the correct way to do this. The advantage of this strategy is that we don't have to invent anything, no new packaging conventions to impose on users. All they have to do is declare an entry point to their application, and we can take it from there when designing the stub creation mechanism in a boot task. This also follows well-established conventions in Java.

In the case of hyperturbo/lunarlander, for example, you would package your jar like so: boot jar -m alandipert.hyperturbo.lunar-lander. The launcher task will read the manifest in the jar, look for the "Main-Class" entry, and do its magic.

**Comment by onetom** [comment]
For `npm` you can specify [multiple binaries](https://docs.npmjs.com/files/package.json#bin) to install, for example:

https://github.com/jashkenas/coffeescript/blob/master/package.json#L20-L23
https://github.com/mochajs/mocha/blob/master/package.json#L34-L37

which is different from specifying the [main entry point](https://docs.npmjs.com/files/package.json#main), eg:

https://github.com/jashkenas/coffeescript/blob/master/package.json#L20-L23

Just keep this in mind and don't wash together the 2 concepts and also don't make something inferior to what `npm` already has, otherwise how can we [raise $2.6million](http://techcrunch.com/2014/02/11/npm/)... ;)

**Comment by danielsz** [comment]
Fully agreed. Good insights. :+1:

**Comment by alandipert** [comment]
Maybe the the [.cljs.edn way of specifying multiple entrypoints in boot-cljs](https://github.com/adzerk/boot-cljs#multiple-builds) is how we could do multiple executables?  I can imagine something like a `.executables.edn` file with a map like `{:executables [{:main foo.bar/-main :name foobar} {:main foo.secondary/-main :name foosecondary}]}` in it.

This would then be searched for and read at some point (when boot loads a dep? when boot loads a dep and some flag indicating it should look for executables is supplied?).  Then somehow at some point and by means yet unknown, `~/.boot/bin/foobar` and `~/.boot/bin/foosecondary` appear.

A problem that comes to mind is that `~/.boot/bin` constitutes another global namespace, and we'd probably want to warn about collisions at some point in this process.  The situation in the `boot.user` today is kind fo similar; users don't need to namespace-qualify tasks if they're referred into `boot.user`, but Clojure does emit a warning when a definition is replaced.

**Comment by alandipert** [comment]
@onetom maybe we can aim for something only half as good?  I'd be ok with just 1.3 million :-)

**Comment by micha** [comment]
Why not distribute executables via the existing platform package managers?

**Comment by alandipert** [comment]
@micha we can do that too?  It's more work though.

For people following along @danielsz made https://github.com/danielsz/boot-binstub so we can experiment with the idea.

**Comment by danielsz** [comment]
Boot will call the *-main* function when evaluating a .boot file. This is actually pretty flexible and cool in the context of this discussion. 
[boot-binstub](https://github.com/danielsz/boot-binstub "Boot binstub") builds on this feature, providing a stub generating mechanism. It is a first draft but it works. If people like it, we can refine the implementation.

**Comment by flyboarder** [comment]
Closing for now https://github.com/danielsz/boot-binstub is a great starting point for anyone who wants this functionality.
