### ISSUE TITLE
Space character encoded as '32' on Windows

### ISSUE THREAD

**Issue by xokomola** [boot-clj/boot#136]
I'm running:
BOOT_CLOJURE_VERSION=1.6.0
BOOT_VERSION=2.0.0-rc9
on Windows 7

When I try a simple task such as 

Examples taken from http://www.flyingmachinestudios.com/programming/boot-clj/

    (deftask fire
      "Prints 'My pants are on fire!'"
      []
      (println "My pants are on fire!"))

The output is printed fine as: "My pants are on fire!"

However when running:

    (deftask fire
      "Announces that something is on fire"
      [t thing     THING str  "The thing that's on fire"
       p pluralize       bool "Whether to pluralize"]
      (let [verb (if pluralize "are" "is")]
        (println "My" thing verb "on fire!")))

I get: "My32nil321is32on fire!"

I've looked at some of the issues regarding ANSI colors and I don't think it's related to this. I've tried --no-colors -C etc. but I've read that on Windows this is switched off by default anyways.
I also used both the standard OS terminal as a the cygwin bash shell. So although boot seems to run fine the println somehow messes with the output.

**Comment by schmir** [comment]
Thanks for your bug report! Let me know if the above commit doesn't fix the issue.

**Comment by xokomola** [comment]
Recompiled. Fix confirmed (Windows 7)

**Comment by schmir** [comment]
Thanks for the confirmation.

BTW, this issue also applies to non-windows platforms. You just had to turn colorization off.
