### ISSUE TITLE
Warnings should be colored in CLI output

### ISSUE THREAD

**Issue by martinklepsch** [boot-clj/boot#137]
**Update:** Warnings are colored in the REPL because REPLy handles this. For regular terminal `stderr` there is no such handling. It'd be a nice addition if this is printed in similar colors as REPLy errors/warnings. This should respect the `--no-colors` flag that can be passed to Boot.

**Comment by micha** [comment]
This is because REPLy, the nREPL client, prints output on `stderr` red, and `boot.util/info`, `boot.util/warn`, etc. print their output to `stderr`.

**Comment by martinklepsch** [comment]
Fine if I reopen with `enhancement`?

**Comment by micha** [comment]
Sure!

**Comment by micha** [comment]
@martinklepsch How would you like to color output? Perhaps:

| log fn | color |
|---------|--------|
| <samp>dbug</samp> | cyan |
| <samp>info</samp> | green |
| <samp>warn</samp> | yellow |
| <samp>fail</samp> | red |

?

**Comment by martinklepsch** [comment]
Depending on the usual ratio between `info` and `stdout` caused by other things (task output etc.) I'd suggest that `info` stays white. Probably good to play around with the settings here a bit to get a feel for it and not end up with a rainbow-printing build process.
