### ISSUE TITLE
Empty string as task argument doc leads to unexpected exception

### ISSUE THREAD

**Issue by jeluard** [boot-clj/boot#140]
When using an empty string as task argument documentation the following exception is thrown:

```java
java.util.concurrent.ExecutionException: java.lang.NullPointerException, compiling:(danielsz/autoprefixer.clj:16:1)
clojure.lang.Compiler$CompilerException: java.lang.NullPointerException, compiling:(danielsz/autoprefixer.clj:16:1)
         java.lang.NullPointerException:
          clojure.string/lower-case                        string.clj:  215
                     boot.cli/decap                           cli.clj:   13
                boot.cli/format-doc                           cli.clj:   87
      boot.cli/argspec->cli-argspec                           cli.clj:  100
```

Obviously you shouldn't use an empty doc but during development this might be confusing.

**Comment by micha** [comment]
Thanks for the report! Can you please paste a build.boot file that demonstrates the problem? I can't reproduce it here.

**Comment by jeluard** [comment]
Sure. I can reproduce it with [boot-autoprefixer](https://github.com/danielsz/boot-autoprefixer). Make sure you let the doc for [browsers](https://github.com/danielsz/boot-autoprefixer/blob/master/src/danielsz/autoprefixer.clj#L18) empty then call `boot aot`.

**Comment by micha** [comment]
I don't understand, what do you mean by "the doc for browsers"?

**Comment by micha** [comment]
Oh, i think i get it, you mean like

```clojure
(deftask foo
  [b bar WHAT sym ""]
  ...
```

something like that?

**Comment by jeluard** [comment]
Yes sorry I meant the doc for the argument [browsers](https://github.com/danielsz/boot-autoprefixer/blob/master/src/danielsz/autoprefixer.clj#L18) of the task `autoprefixer.` When its value is `""` I get the exception during `boot aot`.

**Comment by micha** [comment]
I chose to just give it a default of `"The browser option."`, hope that's cool?

**Comment by jeluard** [comment]
Even better!
