### ISSUE TITLE
Enable / disable bool task options from command line

### ISSUE THREAD

**Issue by onetom** [boot-clj/boot#143]
Currently there is no way to turn OFF a bool task option from the command-line, only to turn it ON.

I hit this issue when I was trying the built-in `push` task but combined with bootlaces' `build-jar`, which sets the `--ensure-clean` flag on:

```
$ boot package build-jar push -r snapshots
...
Installing hoplon5-semantic-ui-1.10.2-SNAPSHOT.jar...
             clojure.lang.ExceptionInfo: java.lang.AssertionError: Assert failed: project repo is not clean
                                         (or (not ensure-clean) clean?)
```

**Comment by micha** [comment]
This looks more difficult than I thought. It will probably requite modifications to the underlying `clojure.tools.cli` functions.
