### ISSUE TITLE
Consolidate configuration under $BOOT_HOME

### ISSUE THREAD

**Issue by micha** [boot-clj/boot#157]
Reduce home directory pollution by boot-related config files by consolidating them all under the `$BOOT_HOME` directory.

* Boot's internal caching and temp files, etc. will be moved to `$BOOT_HOME/boot/`. This directory can be deleted by the user whenever they like to clear out all internal caches and temp files.
* Profile script will be moved from `$HOME/.profile.boot` to `$BOOT_HOME/profile.boot`.

The current setup should be deprecated.

* A deprecation warning printed when old-style configuration is detected.
* Boot should offer to auto-update the user's configuration.
* Boot should still work if auto-update is refused.
* New configuration will be able to coexist side-by-side with older one, in case user needs to use both new version and older version.

**Comment by mynomoto** [comment]
I think that `$BOOT_HOME/cache/` or `$BOOT_HOME/temp/` makes more sense for caching and temp stuff.

**Comment by micha** [comment]
I'd like to have a single directory that contains all the files that are created by boot so it's clear which directory can be deleted (i.e. files created by boot can be deleted at any time, but the user's `profile.boot` for example can't be).

**Comment by micha** [comment]
Or really to say it another way, I was thinking to have a single directory that is _managed_ by boot. It's really boot managed files that are ephemeral&mdash;boot will automatically regenerate them when they're deleted.

**Comment by jeluard** [comment]
Does `$BOOT_HOME` have a default value? Or do I have to set it? Not sure where `profile.boot` must be located with the default configuration.

**Comment by tonsky** [comment]
@jeluard `~/.boot` by defaul
