### ISSUE TITLE
Consider binding to localhost instead of 0.0.0.0

### ISSUE THREAD

**Issue by hura** [boot-clj/boot#162]
Is there a reason the REPL server bind to 0.0.0.0? This allows anybody who figures out the port to run code on the developers computer. The most common use case should be local development and for those who want to actually develop remotely the extra config option should be a minor inconvenience.
Binding to 0.0.0.0 opens up a pretty unnecessary security hole.

**Comment by micha** [comment]
I just went with the `clojure.tools.nrepl.server/server` default: https://github.com/clojure/tools.nrepl/blob/master/src/main/clojure/clojure/tools/nrepl/server.clj#L125

I see your point, though :)

**Comment by hura** [comment]
Yes, the clojure.repl default is pretty bad IMO. Leiningen bind to localhost too (FYI). Not sure about cider etc.

Thanks!
