### ISSUE TITLE
Request: feature like 'gradle wrapper'

### ISSUE THREAD

**Issue by mtnygard** [boot-clj/boot#163]
Gradle has a helpful feature to create [wrapper scripts](https://gradle.org/docs/current/userguide/gradle_wrapper.html) (Unix style and .bat) in a project. Anyone who clones the source to the project can just use ./gradlew build to run a build.

The key to the wrapper is that it pins down the _exact_ version of gradle to use for the build. This helps when a project has aged a bit and the build tool has moved on. Instead of forcing the new developer to go find the right version of the build tool, the wrapper handles it.

When it's time to update the wrapper, running 'gradle wrapper" recreates the wrappers.

You wouldn't want to check boot into your source repo, but those wrappers are short, just a couple of KB, so adding them to the repo is OK.

**Comment by alandipert** [comment]
Neat!  It reminds me a bit of the ongoing discussion and prototyping going in #127 that @danielsz is exploring.  In boot I think the idea of an independent executable would have additional utility outside of the build use-case, like for single-script applications that aren't necessarily responsible for builds.

**Comment by micha** [comment]
You can actually pin a project to a specific version of boot as I think you're describing, see https://github.com/boot-clj/boot/wiki/Keeping-Boot-Up-to-Date#pin-project-to-specific-boot-version.

**Comment by mtnygard** [comment]
@micha That works well, once the user has boot installed. That's the key benefit of the gradle wrapper... it installs gradle for a user who doesn't already have it.

**Comment by micha** [comment]
The changes in #300 solve all these problems, I think. Finally! Feel free to reopen if this isn't the case :)
