### ISSUE TITLE
Uber spewing to the console in rc12

### ISSUE THREAD

**Issue by mtnygard** [boot-clj/boot#164]
Reproducible using https://github.com/rundis/boot-sample. 

`boot aot pom jar` produces an ordinary jar file.

`boot aot pom uber` spews what look like jar contents to stderr (?!)

My setup:
```
boot-sample master mn › boot -u
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
#https://github.com/boot-clj/boot
#Sat Mar 14 18:08:13 CDT 2015
BOOT_CLOJURE_VERSION=1.7.0-alpha5
BOOT_VERSION=2.0.0-rc12
```

I have reproduced this with Java 1.7.0_67 and Java 1.8.0_40. It happens with Clojure 1.7.0-alpha5 and 1.6.0.

**Comment by alandipert** [comment]
Thanks for the report!  Please note that you can `export BOOT_VERSION=2.0.0-rc11` in your shell to downgrade until this goes out with rc13.
