### ISSUE TITLE
Shabang execution not functioning since 2.0.0-rc11

### ISSUE THREAD

**Issue by mtnygard** [boot-clj/boot#172]
Using this as build.boot:

```
#!/usr/bin/env boot

(defn -main [& args]
  (println "executing as script"))
```

It appears that `-main` is not executed since rc11:

```
shabang › BOOT_CLOJURE_VERSION=1.6.0 BOOT_VERSION=2.0.0-rc10 ./build.boot
executing as script
shabang › BOOT_CLOJURE_VERSION=1.6.0 BOOT_VERSION=2.0.0-rc11 ./build.boot
shabang › BOOT_CLOJURE_VERSION=1.6.0 BOOT_VERSION=2.0.0-rc12 ./build.boot
shabang › BOOT_CLOJURE_VERSION=1.6.0 BOOT_VERSION=2.0.0-rc13 ./build.boot
```

This is consistent across Clojure versions and across JVM versions.

**Comment by alandipert** [comment]
What is your boot App version? (`boot -V`)

I suspect if you download the [latest boot.sh](https://github.com/boot-clj/boot/releases/download/2.0.0-rc13/boot.sh) you'll find this resolved.

Recently the requirement that scripts end in .boot was [lifted](https://github.com/boot-clj/boot/commit/716917e324a6c51c1b692e0f3960b84e489c573d) but I'm not sure this change is compatible with prior App versions.

**Comment by mtnygard** [comment]
`boot -V` wasn't even reporting an app version, so I guess it was out of date.

I downloaded the new script, and it works fine.

Thanks!
