### ISSUE TITLE
Run shell command

### ISSUE THREAD

**Issue by gizak** [boot-clj/boot#177]
I am new to boot, but is there a boot way to run shell commands inside of a task? How can I know the starting dir?

**Comment by micha** [comment]
You can run shell commands via the [clojure.java.shell](https://clojure.github.io/clojure/clojure.java.shell-api.html) namespace.

```clojure
(require 'clojure.java.shell)
(clojure.java.shell/sh "ls" "-l")
```

You can find the current working directory in Clojure via the Java system property:

```clojure
(System/getProperty "user.dir")
```

**Comment by gizak** [comment]
It seems there is already a `sh` in `build.boot`

But this doesn't work:
```clojure
(deftask deps
  "Install deps"
  []
  (with-pre-wrap fileset
    (sh "npm" "install" "finalhandler" "serve-static")
    fileset))
```

This works:
```clojure
(deftask my-ls
  "ls"
  []
  (with-pre-wrap fileset
    (sh "ls" "-l")
    fileset))
```

Did I miss something?

**Comment by micha** [comment]
Hmm. What are the symptoms? What happens with the first one?

**Comment by micha** [comment]
[The source is here](https://github.com/boot-clj/boot/blob/master/boot/pod/src/boot/util.clj#L205-L219), so you can see what it's doing.

**Comment by gizak** [comment]
Thanks! Change `sh` to `dosh` solved the problem. Not sure why behaves like this, but maybe because  `sh` is not evaluated immediately as its name implies.

**Comment by micha** [comment]
Ah, yes. I think that was the problem: `ls -l` completes before the JVM exits, but `npm` didn't have time. The `sh` function runs your shell command in another thread and returns a thunk that can be invoked to wait, while `dosh` calls `sh` _and_ invokes the callback to wait on the command's exit status so it can throw an exception on error. We should probably document these functions :)

**Comment by danielsz** [comment]
:+1: 
I was bitten in the exact same way.
