### ISSUE TITLE
(delete-all ...) is dangerous because it follows symlinks!

### ISSUE THREAD

**Issue by jonathn** [boot-clj/boot#180]
Using this function to delete a temporary directory just lost me 5 hours worth of work because it followed symlinks and deleted the target directories instead of the symlinks themselves!

https://github.com/boot-clj/boot/blob/master/boot/pod/src/boot/file.clj#L108-L111

Please either copy the functions from leiningen or use java.nio as demonstrated here:
http://stackoverflow.com/questions/779519/delete-files-recursively-in-java

**Comment by micha** [comment]
Can you please describe the situation you encountered? I'd like to understand how you were using symlinks a little better.

**Comment by micha** [comment]
I can't reproduce this, but I'll make sure symlinks are not followed in any of the `boot.file` functions that delete things.
