### ISSUE TITLE
repl --init-ns does nothing in rc14

### ISSUE THREAD

**Issue by onetom** [boot-clj/boot#187]
Demonstrated in this repo: https://github.com/onetom/boot-init-ns
It worked in rc13.

**Comment by onetom** [comment]
Seems to be fixed by version https://github.com/boot-clj/boot/commit/b8f77e0c8ab2412e06f50d4575a34963d746c9fc .
If it still works with the next release after rc14, we can close this issue.

**Comment by micha** [comment]
I think we're good to go here. Thanks!
