### ISSUE TITLE
File task option in defclifn fails

### ISSUE THREAD

**Issue by pbzdyl** [boot-clj/boot#190]
I have following build.boot:

    #!/usr/bin/env boot
    (require '[boot.cli :refer [defclifn]])
    
    (defclifn -main
      [i input INPUT-FILE file "Input file"]
      (if input
        (println (.getAbsolutePath input))
        (println "No input file specified")))

`./build.boot -i input.txt` fails with:

    java.lang.IllegalArgumentException: No implementation of method: :as-file of protocol: #'clojure.java.io/Coercions found for class: clojure.lang.PersistentVector

Am I using `defclifn` incorrectly or it's a bug?

**Comment by alandipert** [comment]
hey @pbzdyl, try this:

```clojure
#!/usr/bin/env boot
(require '[boot.cli :refer [defclifn]])

(defclifn -main
  [i input FILE file "Input file"]
  (if input
    (println (.getAbsolutePath input))
    (println "No input file specified")))
```

I think the problem is `INPUT-FILE` - this can't have a dash.  @micha would you call this a bug or is there a reason that shouldn't work?

**Comment by micha** [comment]
Ahh! Good catch! This is [the "splitting" behavior of the optarg][1]. I'm not sure if it is a bug. The splitting thing is useful to have, and it's hard to think of a less complicated way to do it. Suggestions welcomed, of course.

[1]: https://github.com/boot-clj/boot/wiki/Task-Options-DSL#complex-options

**Comment by pbzdyl** [comment]
Thanks - after changing `INPUT-FILE` to `FILE` it works. However, it was tricky and surprising behaviour (or at least not documented :))
