### ISSUE TITLE
Standard location for additional boot task definitions

### ISSUE THREAD

**Issue by jballanc** [boot-clj/boot#192]
One of the features that I always appreciated in Ruby's `rake` was the ability to put additional task definitions in the `rakelib` directory and have them included automatically ([more info](http://docs.seattlerb.org/rake/doc/rakefile_rdoc.html#label-Multiple+Rake+Files)). I'm starting to get to the point with `boot` where putting all my task definitions in `build.boot` is getting unwieldy, and having to manually require all the extra definition files is annoying.

Could `boot` automatically search and include any `*.boot` files in some standard directory? (For arguments sake, let's say `./boot-tasks`)

**Comment by micha** [comment]
Totally. The first thing would be to just implement it in your project. How about maybe something like this:

```clojure
(require 'clojure.java.io)

(defn load-files-in-dir
  [path]
  (let [dir (clojure.java.io/file path)]
    (doseq [f (file-seq dir)]
      (when (.isFile f)
        (load-file (.getPath f))))))
```

which you put in a file named `boot-shim.clj`. Then, in your `build.boot` file you can do

```clojure
(load-files-in-dir "boot-tasks")
```

and any `.boot` files will be evaluated. You can then move things directly from your `build.boot` file into `.boot` files in the `boot-tasks` dir without needing to define namespaces, etc. This will still be repeatable because the `boot-shim.clj` file can be added to the project in SCM.

If this all works well for you we can think about adding to boot core. I'm a little hesitant to start adding magical things like this to boot so it would be nice to use it for a while before having to decide.

**Comment by jballanc** [comment]
Good idea! Just to simplify things a bit, I've just added the following directly to my project's `build.boot`:

```clojure
;; Load all "*.boot" files in "boot-tasks"
(let [dir (clojure.java.io/file "boot-tasks")]
  (doseq [f (filter (comp (partial re-find #".*\.boot$")
                          (fn [f] (.getName f)))
                    (file-seq dir))]
    (when (.isFile f)
      (load-file (.getPath f)))))
```

I added the filtering so that I could include documentation (e.g. `README.md`)  with the scripts.

Regarding the "too much magic" concern, I guess I should briefly explain my motivation. For the particular project I'm working on, I had been using boot to write individual scripts but this quickly became annoying for two reasons:

1. Every script needed to copy in the `set-env!` and possibly `task-options!` directives that were already in my `build.boot`.
2. Paths in `set-env!` are relative to where the script is run from, not where it lives. So if `script/do-stuff` works fine when run from the project root, it will fail if run from the script directory (i.e. `cd script && ./do-stuff`).

It occurs to me that both of these concerns could be handled by introducing something akin to `$BOOT_HOME/profile.boot` but for a project root, but then it occurred to me that it might just be easier to run everything as a `boot` task since `boot` is already handling dependencies and file locations in `build.boot`.

---

I'll try this little hack for a while and see how it works out. I realize there's no easy answer...even in the Ruby community some projects take full advantage of Rake tasks, some provide their own script runners (e.g. Rails), and some provide their own script-runner Rake-wrappers using Rake tasks and more (e.g. Padrino)!

**Comment by micha** [comment]
What about possibly something like this:

_build.boot_
```clojure
(merge-env! :source-paths #{"boot-tasks"})

(use 'tasks.lib1 'tasks.lib2 'tasks.lib3)
```

where you'd have namespaces defined in `boot-tasks/tasks/lib1.clj` etc. That seems like not such a pain to add to your build.boot file, and it avoids any magical path names.

**Comment by micha** [comment]
Closing this ticket for now. Please feel free to reopen if any new ideas come to light :)

**Comment by jballanc** [comment]
I've been making use of the snippet I posted before, and so far I'm reasonably happy with it. On further consideration, Clojure's facilities for pulling in files seem sufficient as to make this request un-necessary. Happy to have it be closed (and keep `boot` simple and straight-forward).
