### ISSUE TITLE
White text looks weird on black-on-white terminal

### ISSUE THREAD

**Issue by aengelberg** [boot-clj/boot#197]
I use a black-on-white terminal, and when boot loads dependencies and is downloading jars, the log message (`Retrieving xxx.jar from https://clojars.org/repo/`) seems to be displayed with a white ANSI code. Fortunately, xterm displays it not quite white, so it's still barely visible, but aesthetically it's rather unappealing.

[Here](http://bit.ly/1aZBYhZ) is a link to a screenshot.

**Comment by SevereOverfl0w** [comment]
https://github.com/boot-clj/boot/blob/8ba59a5e0272815931914822c3ea771220a6b8b5/boot/pod/src/boot/pedantic.clj#L47

This hasn't been completely resolved. Overall the better approach may be to use color1..15 throughout the application. What do you think?
