### ISSUE TITLE
Add boot.util/setenv for setting environment variables

### ISSUE THREAD

**Issue by alandipert** [boot-clj/boot#201]
It's not officially possible but is a very useful hack: http://stackoverflow.com/a/7201825

**Comment by DomKM** [comment]
At the risk of becoming known as the guy who always suggests renaming things, perhaps this should be named `set-env`?

**Comment by alandipert** [comment]
:+1:

**Comment by micha** [comment]
After some discussion I think we decided to forgo this, as it introduces platform and JVM specific code we'd have to maintain. Instead we should make tasks or functions that make it easier to work with [ProcessBuilder](http://docs.oracle.com/javase/7/docs/api/java/lang/ProcessBuilder.html) to start processes with custom enviroments.
