### ISSUE TITLE
Using wrap-resource to serve generated static files 

### ISSUE THREAD

**Issue by mhuebert** [boot-clj/boot#202]
I'm using boot for a Clojure / ClojureScript project. I've been using `wrap-resource` Ring middleware to serve static files from my back-end server written in Clojure. But wrap-resource seems to only be able to serve directories that are inside my resource path(s). If I put the boot target directory into resource-paths in set-env!, then Boot tries to read its own compiled files, which raises errors. Am I misunderstanding something?

**Comment by micha** [comment]
Do you have an example of what you're trying to do? I think you want to add the generated files to the fileset via a boot task, but I think it would be easier to show by example.

**Comment by mhuebert** [comment]
Hmm. In a handler in my back-end Clojure server, I'd like to serve a static directory:

```clj
(-> ...handler...
    (wrap-resource "public"))
```

`wrap-resource` only looks in resource directories to find the path I provide (which in this case is "public") - I cannot, for example, serve a "public" directory from the project root.

My compiled JS must reside in this public directory, so I set `:target-path` in build.boot to `resources/public` to make these files serveable by `wrap-resource`.

But the second time Boot runs, it will try to read all of these generated files which are inside of `resources/public`, because `resources` is listed as a resource-directory, and this raises errors. But I can't take `resources` out of resource-paths because `wrap-resource` relies on this to find the `public` directory.

**Comment by micha** [comment]
The target directory is in an undefined state while boot is running. [There is a discussion about this here](http://hoplon.discoursehosting.net/t/boot-tasks-interfere-with-each-other-cannot-be-run-in-parallel/350). Basically things in boot shouldn't be referencing things in named directories---they should only reference resources via the class path or the fileset. This is what makes composable tasks possible.

Your compiled JS should be on the class path, so you could serve the JS via `wrap-resource`. If you add the directory containing the static assets to the class path via `:source-paths` or `:resource-paths` you should be in business.

**Comment by micha** [comment]
If you make a repo that demonstrates the problem I can make a pull request showing what I mean.

**Comment by micha** [comment]
Please feel free to reopen this ticket if the problem persists, thanks!
