### ISSUE TITLE
Glacial jar download experience when running boot 2.0.0 on Heroku 

### ISSUE THREAD

**Issue by paxan** [boot-clj/boot#204]
This will sound spooky. Also there's a surprise in this bug report too.

When running on a Heroku dyno, `boot` version 2.0.0 takes eons to bootstrap itself. Minimal repro:

```bash
# do this in an empty directory
curl -sLO https://github.com/boot-clj/boot/releases/download/2.0.0/boot.sh && chmod +x boot.sh
BOOT_LOCAL_REPO="$(pwd)/.m2/repository" ./boot.sh help
```

@zph, who is more patient than me, reports it took about 25 minutes to finally see `help` command output.

To get yourself a one-off Heroku dyno, do this:

```bash
heroku create
# Creating gentle-tor-2746... done, stack is cedar-14
heroku run -a gentle-tor-2746 bash
# Gives the command prompt on that dyno
```

Once you're on that prompt, try the repro above.

## Surprise :tada:

`2.0.0-rc14` doesn't exhibit the same problem. It's pretty snappy at bootstrapping self. Just now it took about 31 seconds to pull all the needed jars.

## Wild Theory/Hunch

I have no standing to back the following idea up with any evidence. It's a hunch:
perhaps, `https://repo1.maven.org/maven2/` throttles unfamiliar `User-Agents` coming from EC2 IP address space?

**Comment by micha** [comment]
First of all, this is the best bug report we've received. The surprise was exciting!

I wonder if the way you set `BOOT_LOCAL_REPO` is an issue? Usually you'd do

```
BOOT_LOCAL_REPO="$(pwd)/.m2" ./boot.sh help
```

I'm thinking that maybe Heroku does some kind of JAR caching with the expected local repo location?

**Comment by micha** [comment]
Actually, @alandipert suggested that Heroku probably has some kind of Maven proxy that needs to be warmed up for the new version. That sounds like it could be what's happening, maybe?

**Comment by paxan** [comment]
@micha are you suggesting that Heroku has a proxy that somehow varies how it caches Maven artifacts based on identity of client that requests those artifacts? 

Also nope, `BOOT_LOCAL_REPO` is not a factor. This time I ran r14 without it and it's speedy:

```
~ $ curl -sLO https://github.com/boot-clj/boot/releases/download/2.0.0-rc14/boot.sh && chmod +x boot.sh 
~ $ time ./boot.sh help
Retrieving boot-2.0.0.jar from https://clojars.org/repo/
Retrieving clojure-1.6.0.jar from https://repo1.maven.org/maven2/
Retrieving pod-2.0.0.jar from https://clojars.org/repo/
... elided lots of jars ...
Retrieving jna-4.1.0.jar from https://repo1.maven.org/maven2/
Retrieving tools.namespace-0.2.7.jar from https://repo1.maven.org/maven2/
Boot App Version: 2.0.0-rc14
Boot Lib Version: 2.0.0
Clojure Version:  1.6.0

Usage:   boot OPTS <task> TASK_OPTS <task> TASK_OPTS ...

... elided the help output ...

Do `boot <task> -h` to see usage info and TASK_OPTS for <task>.

real	1m6.252s
user	0m25.563s
sys	0m7.652s
```

**Comment by paxan** [comment]
I've just tried `2.0.0` without `BOOT_LOCAL_REPO`. It is still glacial. So that var has no effect for better or worse.

**Comment by micha** [comment]
Do you know what it's doing when it's being slow? Is it downloading JARs? Is the size of the .m2 directory much larger for 2.0.0 than for rc14?

**Comment by paxan** [comment]
There's not much instrumentation. It just does this:
```
$ hk run bash
Running `bash` on desolate-gorge-1523 as run.7003:
~ $ curl -sLO https://github.com/boot-clj/boot/releases/download/2.0.0/boot.sh && chmod +x boot.sh
~ $ time ./boot.sh -v help
Retrieving boot-2.0.0.jar from https://clojars.org/repo/
Retrieving clojure-1.6.0.jar from https://repo1.maven.org/maven2/
Retrieving pod-2.0.0.jar from https://clojars.org/repo/
Retrieving dynapath-0.2.3.jar from https://clojars.org/repo/
Retrieving shimdandy-impl-1.1.0.jar from https://repo1.maven.org/maven2/
Retrieving core-2.0.0.jar from https://clojars.org/repo/
^C
real	7m3.619s
user	0m42.491s
sys	0m32.081s
```

As you see, I've just given up at about 7 minutes in.

**Comment by paxan** [comment]
BTW, I went as far as building it directly on a dyno yesterday. From source. Same slowness.
Perhaps I could sprinkle it with bunch of debug print statements. But I am not exactly familiar with the code base :disappointed:

**Comment by alandipert** [comment]
Have you considered filing a ticket with Heroku?  My best guess is that they're doing something a little too fancy with Maven repository caching.

To test this hypothesis yoy could try pulling `https://clojars.org/repo/boot/core/2.0.0/core-2.0.0.jar` from Clojars with `wget` to see if that too is slow.

Otherwise I have no idea how actual boot code could be influencing this.  Nothing has changed about the way we distribute or consume jars anywhere in the codebase... afaik.

**Comment by micha** [comment]
Oh, I totally forgot about debug output! You can see a lot of what boot is doing if you add maximum verbose level, like this:

```
$ hk run bash
Running `bash` on desolate-gorge-1523 as run.7003:
~ $ curl -sLO https://github.com/boot-clj/boot/releases/download/2.0.0/boot.sh && chmod +x boot.sh
~ $ time ./boot.sh -vvv help
```

It will be printing debug messages about what it's doing when it fetches things from clojars etc.

**Comment by alandipert** [comment]
As a workaround until we puzzle this one out, I added a minimal, pre-populated `~/.m2` to the [2.0.0 release files](https://github.com/boot-clj/boot/releases/tag/2.0.0).  To use it, run this before downloading and running `boot.sh`:

    curl -sL https://github.com/boot-clj/boot/releases/download/2.0.0/m2.tar.bz2 | tar -xj

**Comment by paxan** [comment]
@alandipert I've tested the hypothesis:
```
21:29 $ hk run bash
Running `bash` on elided-app-1234 as run.2350:
~ $ time curl -sLO https://clojars.org/repo/boot/core/2.0.0/core-2.0.0.jar
real	0m0.172s
user	0m0.008s
sys	0m0.020s

~ $ time curl -sLO https://repo1.maven.org/maven2/org/clojure/clojure/1.7.0-RC1/clojure-1.7.0-RC1.jar
real	0m0.098s
user	0m0.021s
sys	0m0.033s

~ $ ls -lh
total 4.5M
-rw------- 1 u29315 29315 3.7M May 23 04:35 clojure-1.7.0-RC1.jar
-rw------- 1 u29315 29315 780K May 23 04:35 core-2.0.0.jar
```

Direct HTTP GETs from clojars & maven are fast.
But attempts by boot.sh from 2.0.0 release continue to exhibit tremendous sluggishness.
I will contact Heroku to rule out or confirm the theory about proxying (I doubt they do anything special).

```
$ dig repo1.maven.org
repo1.maven.org.	8602	IN	CNAME	central.maven.org.
central.maven.org.	95002	IN	CNAME	sonatype.map.fastly.net.
sonatype.map.fastly.net. 30	IN	A	23.235.39.209
```

Maven repo is proxied by a serious CDN, Fastly, so if I was Heroku why would I waste my resources to proxy stuff like that. Fastly has a POP in Virginia that sits like tiny number of milliseconds away from AWS infrastructure used by Heroku.

**Comment by alandipert** [comment]
@paxan thanks for digging in.  I agree that it's highly unlikely they're doing anything fancy.  I tried to reproduce on an m3.large EC2 instance and was unable.  This leads me to consider another theory:  GC thrash and/or paging caused by flailing Maven heuristics.  Do you have any information about memory or CPU usage while it's hanging?

Perhaps something about the combination of 2.0.0 dependencies is irritating the aether/maven machinery responsible for figuring out what to download.  In the past we've seen it think too hard about version ranges and use a lot of memory to do so.

To test this theory you could try increasing the JVM's maximum heap size to 512m, which I understand is the memory allotted to 1x dynos: `export BOOT_JVM_OPTIONS="-Xmx512m"`.

The [previous reported Heroku-related bug](https://github.com/boot-clj/boot/issues/170) might have been memory related, but we never confirmed.

According to the [Heroku profiling docs](https://devcenter.heroku.com/articles/java-memory-issues#profiling-a-java-application-on-heroku)  you could also add their memory logging agent to your repo and attach it to boot with a `BOOT_JVM_OPTIONS` option.

**Comment by paxan** [comment]
On a 1X dyno, I got:
```
~ $ export BOOT_JVM_OPTIONS="-Xmx512"
~ $ time ./boot.sh help
Error occurred during initialization of VM
Too small initial heap
```

Ok! I am going to unleash our log capturing system on these dynos to grab all runtime metrics data generated by Heroku. Stand by. I'll gist it... It captures logs as EDN :smile:

**Comment by paxan** [comment]
@alandipert here it goes: https://gist.github.com/paxan/d41b83775150b0f258fb
So the memory theory seems correct. Something between rc14 and release introduced abusive memory behavior.

**Comment by alandipert** [comment]
@paxan thanks for trying it out again.

Locally, I was able to make the `Too small initial heap` error go away by adjusting both max heap and initial heap: `BOOT_JVM_OPTIONS="-Xms16m -Xmx512m"`  So, that would be something new to try.

As another data point, I tried downloading and bootstrapping in a VirtualBox (Ubuntu) VM with first 512m, then 256m memory allocated, and it took about the same amount of time -- 2 minutes -- in both configurations.  So, just simulating low memory doesn't seem to necessarily reproduce the problem.  This was with `BOOT_JVM_OPTIONS="-Xms16m -Xmx512m"` both times.

I'm curious to know, does downloading and unpacking the pre-rolled `~/.m2` mitigate the issue?

**Comment by paxan** [comment]
It might be possible to repro using [cedar-14 Docker image,][cedar] and fiddling with the container [memory constraints.][run]

[cedar]: https://registry.hub.docker.com/u/heroku/cedar/
[run]: https://docs.docker.com/reference/run/#memory-constraints

**Comment by paxan** [comment]
@alandipert Hooray! The `Xms` & `Xmx` workaround helps!
I've tried both:
 - Xms/Xmx as you suggested: `export BOOT_JVM_OPTIONS="-Xms16m -Xmx400m"`
 - Xmx/Xss as we do with some of our Clojure apps: `export BOOT_JVM_OPTIONS="-Xmx300m -Xss512k"`

Both ways make `boot` complete successfully.

```
$ hk run  bash
Running `bash` on elided-app-1234 as run.3603:
~ $ curl -sLO https://github.com/boot-clj/boot/releases/download/2.0.0/boot.sh && chmod +x boot.sh
~ $ export BOOT_JVM_OPTIONS="-Xms16m -Xmx400m"
~ $ time ./boot.sh help
Retrieving boot-2.0.0.jar from https://clojars.org/repo/
Retrieving clojure-1.6.0.jar from https://repo1.maven.org/maven2/
Retrieving pod-2.0.0.jar from https://clojars.org/repo/
Retrieving dynapath-0.2.3.jar from https://clojars.org/repo/
Retrieving shimdandy-impl-1.1.0.jar from https://repo1.maven.org/maven2/
...
Retrieving data.xml-0.0.8.jar from https://repo1.maven.org/maven2/
Retrieving data.zip-0.1.1.jar from https://repo1.maven.org/maven2/
Retrieving tools.namespace-0.2.7.jar from https://repo1.maven.org/maven2/
Boot App Version: 2.0.0
Boot Lib Version: 2.0.0
Clojure Version:  1.6.0

Usage:   boot OPTS <task> TASK_OPTS <task> TASK_OPTS ...
...
Do `boot <task> -h` to see usage info and TASK_OPTS for <task>.

real	1m53.683s
user	1m17.097s
sys	0m6.825s
```

I am pretty sure I ran into this trouble because I am making a specialized buildpack that uses boot. So I am starting with a naked cedar-14 container and building on top of that. Containers that were primed with Heroku's standard JVM buildpacks automatically preset env vars with Xms and so on.

**Comment by alandipert** [comment]
Cool, good to hear!  Please close this issue unless you have other questions or findings.

Also, it would be super awesome of you to fire up a Heroku wiki page with your learnings :confetti_ball:

**Comment by paxan** [comment]
It would be still great to get to the bottom of why rc14 was fine and 2.0.0 isn't.

**Comment by paxan** [comment]
The diff between rc14 and 2.0.0 ain't trivial unfortunately:
https://github.com/boot-clj/boot/compare/2.0.0-rc14...2.0.0

**Comment by alandipert** [comment]
It is, as we can restrict our attention to App.java, the only code that
runs during bootstrap.

**Comment by micha** [comment]
One more possibly useful data point:

```
$ jar tf ~/bin/boot
META-INF/
META-INF/MANIFEST.MF
boot/
boot/base/
boot/App$1.class
boot/App.class
boot/App$Exit.class
boot/base/version.properties
boot/App$2.class
aether.uber.jar
org/
org/projectodd/
org/projectodd/shimdandy/
org/projectodd/shimdandy/ClojureRuntimeShim.class
META-INF/maven/
META-INF/maven/org.projectodd.shimdandy/
META-INF/maven/org.projectodd.shimdandy/shimdandy-api/
META-INF/maven/org.projectodd.shimdandy/shimdandy-api/pom.xml
META-INF/maven/org.projectodd.shimdandy/shimdandy-api/pom.properties
```

Note the `aether.uber.jar` that's contained as a resource of the boot.sh uberjar. This jar is unpacked into a temp dir the first time boot is run. It contains the Aether machinery needed to fetch boot's own dependencies. (The boot.sh jar is just a minimal java bootstrapping shell--boot's implementation is in jars on Clojars, so you can update boot in place without messing with boot.sh.) It's possible that the boot.sh uberjar build was bungled when we forgot to do `lein clean` before building the release. I'll clean everything and rebuild the executable and re-upload to github releases.

**Comment by micha** [comment]
Can you try this one please? https://github.com/boot-clj/boot/releases/download/2.0.0/disregard-this.sh

**Comment by paxan** [comment]
Sorry to report @micha but that didn't help.
```
...
2015-05-26T05:51:09.409098+00:00 heroku[run.5600]: source=run.5600 dyno=heroku.37118756.ebf775cc-2d68-4226-80f9-099e4b26cba3 sample#memory_total=1129.57MB sample#memory_rss=511.39MB sample#memory_cache=0.37MB sample#memory_swap=617.80MB sample#memory_pgpgin=939017pages sample#memory_pgpgout=808005pages
2015-05-26T05:51:09.410240+00:00 heroku[run.5600]: Process running mem=1129M(220.6%)
2015-05-26T05:51:09.410385+00:00 heroku[run.5600]: Error R14 (Memory quota exceeded)
```

But that `export BOOT_JVM_OPTIONS="-Xmx300m -Xss512k"` setting continues to work as mitigation.
