### ISSUE TITLE
clojure.lang.Compiler$CompilerException: clojure.lang.ArityException: Wrong number of args (4) passed to: StringReader, compiling:(abnf.clj:186:28)

### ISSUE THREAD

**Issue by alandipert** [boot-clj/boot#210]
```
boot.user=> (set-env! :dependencies '[[org.clojure/clojurescript "0.0-3211"] [instaparse "1.4.0"]])
nil
boot.user=> (require 'instaparse.core)

clojure.lang.Compiler$CompilerException: clojure.lang.ArityException: Wrong number of args (4) passed to: StringReader, compiling:(abnf.clj:186:28)
            clojure.lang.ArityException: Wrong number of args (4) passed to: StringReader
```

`boot.core/add-dependencies!` was attempting to strip Clojure dependencies from dependency vectors before resolving dependencies.

This influenced the version of the dependencies selected in a way that diverged from Lein/aether, and the end result was that two different Clojure versions were on the classpath at the same time.

This caused instaparse's Clojure version sniffing hack in `instaparse.cfg` to think it was on 1.7 when it was actually on 1.6.

**Comment by borkdude** [comment]
Thanks for fixing!

**Comment by martinklepsch** [comment]
Great you figured it out! :+1:
