### ISSUE TITLE
Merge should work for projects own resources too

### ISSUE THREAD

**Issue by kul** [boot-clj/boot#217]
Here is the problem i am facing which i think would be pretty common for others too.
One of the `data_readers.clj` is inside one of the jar files and other is in my resources folder.
Since resources gets copied in a different step from `uber` step, the `.exists` method in `unpack-jar` will return false for it causing the uber step to overwrite the fileset without actually merging.

I guess the mergers would need to be applied at `commit!` too. WDYT?

**Comment by micha** [comment]
Nice! Thanks for reporting this! It sounds totally reasonable to me. I'll work up a patch and run it by @tobias for review.

Are you also recommending that we merge `data_reader.clj` files? What about `deps.cljs`? Are there any other non-namespaced Clojure/ClojureScript files in JARS that we need to merge when uberizing? A separate ticket for those would be appropriate, probably.

**Comment by micha** [comment]
Whoops, my bad, `data_readers.clj` is already in the merge list, please disregard that part :smile:

**Comment by kul** [comment]
Works Perfectly! Thanks @micha

**Comment by tobias** [comment]
Thank you @kul for catching this, and thank you @micha for fixing it.
