### ISSUE TITLE
Problem publishing jar

### ISSUE THREAD

**Issue by podviaznikov** [boot-clj/boot#219]
Hi, I’m having trouble publishing jar to clojars using boot task. `build.boot` looks like
```
(set-env!
  :source-paths #{"src"}
  :resource-paths #{"resources"}
  :dependencies '[[org.clojure/clojure "1.6.0"]
                  [adzerk/bootlaces "0.1.9" :scope "test"]
                  [clj-aws-s3 "0.3.10"]
                  [pandect "0.5.2"]])

(require '[adzerk.bootlaces :refer :all])

(def +version+ "0.1.0-SNAPSHOT")
(bootlaces! +version+)

(task-options!
  pom {:project 'hashobject/boot-s3
       :version +version+
       :description "Boot task for syncing local directory with AWS S3 bucket"
       :url         "https://github.com/hashobject/boot-s3"
       :scm         {:url "https://github.com/hashobject/boot-s3"}
       :license     {"name" "Eclipse Public License"
                     "url"  "http://www.eclipse.org/legal/epl-v10.html"}})


(deftask install-locally
  "Install locally"
  []
  (comp (pom) (jar) (install)))

(deftask release-snapshot
  "Release snapshot"
  []
  (comp (pom) (jar) (push-snapshot)))
```
so when I call `release-snapshot` I’m getting error:

```
boot release-snapshot
Writing pom.xml and pom.properties...
Writing boot-s3-0.1.0-SNAPSHOT.jar...
CLOJARS_USER and CLOJARS_PASS were not set; please enter your Clojars credentials.
Username: hashobject
Password:
             clojure.lang.ExceptionInfo: java.lang.AssertionError: Assert failed: project repo is not clean
                                         (or (not ensure-clean) clean?)
    data: {:file
           "/var/folders/7d/9c32qg7x2_z9slnznbhq2dg80000gn/T/boot.user9060217544532512127.clj",
           :line 19}
java.util.concurrent.ExecutionException: java.lang.AssertionError: Assert failed: project repo is not clean
                                         (or (not ensure-clean) clean?)
               java.lang.AssertionError: Assert failed: project repo is not clean
                                         (or (not ensure-clean) clean?)
     boot.task.built-in/fn/fn/fn/fn                      built_in.clj:  622
  adzerk.bootlaces/eval123/fn/fn/fn                     bootlaces.clj:   45
     boot.task.built-in/fn/fn/fn/fn                      built_in.clj:  496
     boot.task.built-in/fn/fn/fn/fn                      built_in.clj:  239
                boot.core/run-tasks                          core.clj:  669
                                ...
               boot.user/eval294/fn  boot.user9060217544532512127.clj:   21
clojure.core/binding-conveyor-fn/fn                          core.clj: 1910
```
Maybe someone can help. I'm not really sure why I'm getting this error message.

**Comment by mynomoto** [comment]
Hi, you need to export your clojars username and password to env vars.
```
export CLOJARS_USER=foo
export CLOJARS_PASS=bar
```
The error message is saying that those were not set.
HTH

**Comment by micha** [comment]
Also, bootlaces configures the `push` task to [ensure that your project git repository has no uncommitted changes][1]. It looks like the assertion

```
Assert failed: project repo is not clean
```

is failing. If you commit or stash your changes you should be good to go.

If you don't like that assertion you can disable it by overriding the `:ensure-clean` option to the `push` task set by the `bootlaces!` function, setting it to `false`. Of course, you'd want to do this _after_ calling the `bootlaces!` function.

[1]: https://github.com/adzerk-oss/bootlaces/blob/master/src/adzerk/bootlaces.clj#L35

**Comment by podviaznikov** [comment]
My git repository has no uncommitted changes:
```
➜  boot-s3 git:(master) git status
On branch master
nothing to commit, working directory clean
➜  boot-s3 git:(master)
```
but adding `:ensure-clean` helped.

**Comment by timothypratley** [comment]
Just as a data point, this happened to me too.

    # On branch: master  |  No changes (working directory clean)

so had to :ensure-clean false as a workaround

**Comment by anmonteiro** [comment]
FWIW this happened to me as well, and the problem was caused by having a global gitignore. So even though the repo looked clean _globally_, it wasn't _locally_ (in my case, due to a `.DS_STORE` file

**Comment by timothypratley** [comment]
OOoo good tip thank you @anmonteiro

**Comment by sundbp** [comment]
ran into this - I thought clean meant "no uncommitted changes", but in fact it also includes having any unknown files not in .gitignore present. Just mentioning it in case others find this thread - ensure any log files or similar are in .gitignore for repo to be deemed "clean".
