### ISSUE TITLE
Add support for BOOT_JAVA_CMD

### ISSUE THREAD

**Issue by aaronc** [boot-clj/boot#222]
It would be nice to be able to choose the java command that boot uses.

It would seem that this may be as simple as changing the last line of `head.sh` to:

```sh
exec ${BOOT_JAVA_CMD:-java} $BOOT_JVM_OPTIONS -Dboot.app.path="$selfpath" -jar "$0" "$@"
```

When I try this, it seems to work but I get this warning:

```
warning [/usr/local/bin/boot]:  219 extra bytes at beginning or within zipfile
  (attempting to process anyway)
```

**Comment by micha** [comment]
@aaronc I remember getting this warning when i tried to run boot in [drip](https://github.com/ninjudd/drip) once. What are you using for your `BOOT_JAVA_CMD`?

Also the env var sounds good to me.

**Comment by aaronc** [comment]
I was trying to use drip too. Maybe it's a drip issue. Everything still
worked normally, but i didn't notice any speed-up.

**Comment by micha** [comment]
I think most of the time is spent starting Clojure core; drip only helps with the JVM startup time.

**Comment by aaronc** [comment]
Okay, well I guess drip won't help much here. I see startup time is discussed in #106 - the boot server sounds like a great idea if there's ever time to revisit it.

The env var would still be nice as I sometimes switch JDK's.
