### ISSUE TITLE
Example of loading a local jar file dynamically using boot-clj

### ISSUE THREAD

**Issue by paxan** [boot-clj/boot#225]
@micha, we've talked yesterday about a situation where I needed to execute some code from a non-released jar sitting in the local filesystem (e.g. stored as a tempfile after downloading jar from S3 or whatever). You've suggested `add-classpath` as a solution. Here's a working example:

https://gist.github.com/paxan/2a6491959e4ce16e75a6

**Comment by paxan** [comment]
Closing, because it's not an issue... but an observation/example type of thing.

**Comment by martinklepsch** [comment]
@paxan consider adding this to the wiki :)
