### ISSUE TITLE
Utility functions for version comparison

### ISSUE THREAD

**Issue by Deraen** [boot-clj/boot#240]
Both boot-cljs and boot-cljs-repl need to do version comparisons.  Would be useful if boot included functions for these, or maybe bundled https://github.com/xsc/version-clj for this.

adzerk-oss/boot-cljs-repl#21

**Comment by pkobrien** [comment]
Even though it is js, we should at least consider the Google Closure compareVersions function as a reference implementation: http://google.github.io/closure-library/api/source/closure/goog/string/string.js.src.html#l1190

**Comment by jeluard** [comment]
Note that maven version numbers have specific semantic. Apparently [version-clj](https://github.com/xsc/version-clj) implement those.

**Comment by micha** [comment]
This seems like a good thing to include in boot itself, perhaps?

**Comment by Deraen** [comment]
@micha Yes, that's the idea :D

**Comment by pkobrien** [comment]
There is also this library: https://github.com/grimradical/clj-semver

**Comment by Deraen** [comment]
Maven libraries do no necessarily adhere to semver spec so probably version-clj should be a better choice.

**Comment by micha** [comment]
Ok, cool, we do it.

**Comment by Deraen** [comment]
Qualifiers can also matter. Version-clj seems to do that.

**Comment by piranha** [comment]
That's sorely needed now, as `(compare "1.7.48" "1.7.107")` returns -3 and boot-cljs complains about 1.7.107 being older than 1.7.48. :)

**Comment by micha** [comment]
The main reason for this ticket was `boot-cljs`, which now has a better way to track dependencies that doesn't involve version comparisons.
