### ISSUE TITLE
Spurious FSEventStreamStart log messages on OS X

### ISSUE THREAD

**Issue by aaronc** [boot-clj/boot#248]
See this thread for details: https://groups.google.com/forum/#!topic/clojurescript/KUcELEvX18A

**Comment by alandipert** [comment]
Can you please provide the OS X point version and output of `boot -V`?

**Comment by aaronc** [comment]
OS X 10.10.3 (14D136)

```
#https://github.com/boot-clj/boot
#Fri Jul 10 21:42:45 EDT 2015
BOOT_CLOJURE_VERSION=1.7.0
BOOT_VERSION=2.1.2
#App version: 2.0.0
```

There is a pending update to 10.10.4 from the App Store - maybe I should install that.

**Comment by alandipert** [comment]
@aaronc Thanks, and yes if you can test on 10.10.4 that would be helpful as well.

**Comment by drakezhard** [comment]
I have the same problem with the same boot version and OS X version. The update to 10.10.4 didn't fix it.

**Comment by kirked** [comment]
Replied in the group thread, but I found [this PR](https://github.com/joyent/libuv/pull/894) for libuv from 2013 when they had the issue, and an [older post](https://lists.apple.com/archives/darwin-dev/2008/Feb/msg00043.html) that describe the problem.

Apparently there are too many filesystem-change watch processes with large file sets on the same device. The fix implemented in libuv appears to be to use a single watcher for a device and filter the changes on notification to the ones you're really interested in.

**Comment by drakezhard** [comment]
Yeah I figured it out myself just now, I added "target" to resources to serve files properly with pedestal, and triggered an infinite watch loop. (set-env! :resource-paths #(disj % "target")) before the development task fixed it. Thanks anyway kirked.

**Comment by piranha** [comment]
Same thing for me when I'm building uberjar! Though removing "target" from `:resource-paths` doesn't really help, I'm pointing to different `:target-path` when building uberjar now.

**Comment by cigitia** [comment]
I’m encountering the same problem for all boot tasks, including `boot` only and `boot repl`. No tasks are able to run at all. The error’s output is identical with that in the Google Groups thread.

Restarting my computer does not resolve the problem; clearing the `build.boot` file does not resolve the problem. I was able temporarily to resolve the problem by clearing all files from `~/.boot/tmp` and clearing my `build.boot` file to have blank content, but restoring my old `build.boot` file made the problem reoccur. 

I'm using OS X 10.11 (15A284). `boot -v` outputs:

    #https://github.com/boot-clj/boot
    #Wed Oct 21 21:36:26 CDT 2015
    BOOT_CLOJURE_VERSION=1.7.0
    BOOT_VERSION=2.3.0
    #App version: 2.2.0

**Comment by cigitia** [comment]
I've determined the problem after finding a [related node.js issue](https://github.com/nodejs/node-v0.x-archive/issues/5463). Three days ago, I installed two NPM modules into a node_modules subfolder within my source tree, in order to have them appear in my target directory. Removing the node_modules folder and, once more, clearing `~/.boot/tmp` together solved my issue: it probably is due to how many files the NPM modules contain.

I’m able to get around this problem by installing the NPM globally, but it would be nice if the problem did not occur at all. Is it possible to exclude specific source subfolders from Boot’s file monitoring?

**Comment by martinklepsch** [comment]
> As a stopgap, it possible to exclude specific source subfolders from Boot’s file monitoring?

I'm looking into this right now and it seems very much possible.

**Comment by micha** [comment]
Wouldn't the best fix be to prevent watching directories that contain too many files? Rather than forcing the user to explicitly exclude them?

**Comment by thedavidmeister** [comment]
FYI i'm seeing this on OS X 10.12.3

```
$ boot -V
#http://boot-clj.com
#Fri Mar 24 12:58:43 AEDT 2017
BOOT_CLOJURE_NAME=org.clojure/clojure
BOOT_CLOJURE_VERSION=1.8.0
BOOT_VERSION=2.5.5
```

**Comment by martinklepsch** [comment]
[This PR](https://github.com/boot-clj/boot/pull/663) allows exclusion of certain directories from being watched. These changes could probably affect the issues outlined here.

**Comment by martinklepsch** [comment]
> Apparently there are too many filesystem-change watch processes with large file sets on the same device. The fix implemented in libuv appears to be to use a single watcher for a device and filter the changes on notification to the ones you're really interested in.

FWIW this also seems like an interesting observation but not sure how applicable that is to Boot.

**Comment by flyboarder** [comment]
Is this happening for anyone? I am on 10.14.2 with no issues and large directories.

**Comment by flyboarder** [comment]
Closing for now, please reopen if still an issue.
