### ISSUE TITLE
Add Boot support to stuff which needs to know about classpath

### ISSUE THREAD

**Issue by Deraen** [boot-clj/boot#249]
Because Boot manages the classpath dynamically through [filesets](https://github.com/boot-clj/boot/wiki/Filesets#the-task-model), the value of `java.class.path` doesn't contain the source paths.

Boot provides two alternative properties:
- `fake.class.path` contains the original directories (which are not on the class path and so are "fake")
- `boot.class.path` contains the directories actually on the classpath (which are temporary and dynamically allocated, so not part of java.class.path which is static)

Projects doing something with classpath:

- [x] [vim-fireplace](https://github.com/tpope/vim-fireplace/commit/5866d0017a7f544a27c3f60045958d6d7759b1a8)
- [ ] [java.classpath](https://github.com/clojure/java.classpath/blob/master/src/main/clojure/clojure/java/classpath.clj#L55)
- [ ] [tools.namespace](https://github.com/clojure/tools.namespace/blob/master/src/main/clojure/clojure/tools/namespace/dir.clj#L47)
- [ ] [Cider-nrepl refresh op](https://github.com/clojure-emacs/cider-nrepl/blob/master/src/cider/nrepl/middleware/refresh.clj), through tools.namespace
- [ ] [Refactor-nrepl rename-file-or-dir op](https://github.com/clojure-emacs/refactor-nrepl/blob/master/src/refactor_nrepl/rename_file_or_dir.clj#L30), through tools.namespace (clojure-emacs/refactor-nrepl#97)

Notes:

- It is probable that it is not desirable for java.classpath or tools.namespace to know about Boot
- Even if they could be changed, which one should they use?

**Comment by micha** [comment]
@Deraen I believe it's the other way around:

- `fake.class.path` contains the original directories (which are not on the class path and so are "fake")
- `boot.class.path` contains the directories actually on the classpath (which are temporary and dynamically allocated, so not part of `java.class.path` which is static

**Comment by Deraen** [comment]
Yes, I noticed that and fixes elsewhere but forgot to edit this.

**Comment by micha** [comment]
:beers: I figured as much, sorry :)

**Comment by mitchelkuijpers** [comment]
Can I help with this? I would not mind creating a pull request for clj-refactor. Or do you guys wanna fix it elsewhere?

**Comment by micha** [comment]
A ticket has been created for discussion regarding the concrete needs of these tools here: #251

**Comment by micha** [comment]
I think we can close this one as there aren't any actionable tasks here. Feel free to reopen :)
