### ISSUE TITLE
Set some guidelines regarding build-time dependencies

### ISSUE THREAD

**Issue by Skinney** [boot-clj/boot#253]
I've been frustrated lately. I've found it important to reduce the size of my uberjar to a minimum (this has to do with using the free plan on Heroku, where lower slug-sizes makes your app start up faster), but when I look at what is actually included in the uberjar, I find dependencies that (i think) are only used at compile-time. Dependencies like Clojurescript.

In fact, It's impossible to use any cross-platform dependency without ClojureScript and Google Closure finding their way into your uberjar, which is often completely unnecessary as my frontend code is compiled before being inserted into the uberjar.

Could we set some guidelines regarding use of build-time dependencies (like cljs)? Add some information to the README or make minor changes which makes this easy to manage? I don't know exactly this should be like, but would at least like to start the discussion. I think small uberjars is a good goal in general, not only for my use-case.

**Comment by martinklepsch** [comment]
When you use `:scope "test"` dependencies won't end up in your uberjar. The problem remains though if any of your dependencies didn't specify ClojureScript with `:scope "test"`.

What I often do is not adding ClojureScript dependencies via a top level `set-env!` call but instead inside a task like this:
```clj
(deftask add-cljs-deps []
  (comp
     (set-env! :dependencies #(concat % '[[cljs-time "0.1.0"] [datascript "0.1.0"]])))
```

**Comment by Skinney** [comment]
True, but this tends to fall apart if you pull in a library that also supports clojurescript. This is why it is important to point this out in a readme.

**Comment by martinklepsch** [comment]
Do you have a suggestion what that message might look like?

**Comment by Skinney** [comment]
I'll make a PR tomorrow.

**Comment by micha** [comment]
You can use the global exclusions key in the env, like this:

```
(set-env!
  ...
  :exclusions '[org.clojure/clojurescript]
  ...)
```

That will exclude cljs when resolving transitive dependencies (that is to say, `org.clojure/clojurescript` will be ignored even if other dependencies specify it as a transitive dependency).
