### ISSUE TITLE
Push task makes assumptions regarding pgp setup which negate best practices

### ISSUE THREAD

**Issue by danielsz** [boot-clj/boot#254]
First, the problem statement:

[boot.pgp/get-pubkey](https://github.com/boot-clj/boot/blob/c244cc6cffea48ce2912706567b3bc41a4d387c7/boot/worker/src/boot/pgp.clj#L25) selects the first keypair in the secret keyring regardless of whether this is a signing key or not. 

Actually, it shouldn't be (according to best practices). 
If you work on a machine with your master keypair, you will see no error, because in this setup the first keypair in the secret keyring corresponds to a signing key. However, if you follow best practices, and your master keypair is safely tucked on a usb stick and stored in the basement of your grandma's home, and you're using subkeys derived from the master keypair, then `get-pubkey` will blow in your face, because the first keypair has a dummy secret key, and what you want is your signing key. 

OK, so that was the bad news. The good news is that I know how to fix this. But I would like to know how important this is from your perspective, because I would need to talk with you about changing a couple more things to make pgp handling better.

References:
* [OpenPGP Best Practices] (https://alexcabal.com/creating-the-perfect-gpg-keypair/)
* [Best practices] (https://help.riseup.net/en/security/message-security/openpgp/best-practices#only-use-your-primary-key-for-certification-and-possibly-signing-have-a-separate-subkey-for-encryption)

**Comment by micha** [comment]
looks like a duplicate, can we close this one?

**Comment by danielsz** [comment]
Sure.
