### ISSUE TITLE
Push task makes assumptions regarding pgp setup which negate best practices

### ISSUE THREAD

**Issue by danielsz** [boot-clj/boot#255]
First, the problem statement:

[boot.pgp/get-pubkey](https://github.com/boot-clj/boot/blob/c244cc6cffea48ce2912706567b3bc41a4d387c7/boot/worker/src/boot/pgp.clj#L25) selects the first keypair in the secret keyring regardless of whether this is a signing key or not. 

Actually, it shouldn't be (according to best practices). 
If you work on a machine with your master keypair, you will see no error, because in this setup the first keypair in the secret keyring corresponds to a signing key. However, if you follow best practices, and your master keypair is safely tucked on a usb stick and stored in the basement of your grandma's home, and you're using subkeys derived from the master keypair, then `get-pubkey` will blow in your face, because the first keypair has a dummy secret key, and what you want is your signing key. 

OK, so that was the bad news. The good news is that I know how to fix this. But I would like to know how important this is from your perspective, because I would need to talk with you about changing a couple more things to make pgp handling better.

References:
* [Creating the perfect GPG keypair] (https://alexcabal.com/creating-the-perfect-gpg-keypair/)
* [OpenPGP Best Practices] (https://help.riseup.net/en/security/message-security/openpgp/best-practices#only-use-your-primary-key-for-certification-and-possibly-signing-have-a-separate-subkey-for-encryption)

**Comment by danielsz** [comment]
I would like to lay out the vision for the PGP redesign I have in mind in the shape of guiding principles:

* Client libraries like `bootlaces` should not have to configure anything. 
* Signing and encrypting in Boot-clj works out of the box, with no configuration. This can be made to work because we are going to make assumptions about the end user's environment. In turn, those defaults will be capable of being overridden with environment variables. 
  1. Secret keyring location is the default one (`$HOME/.gnupg/secring.pgp`). Can be overridden with `BOOT_GPG_SECRING`
  2. Name/Email is the one we find. Provided the secret keyring has only one user, we can be sure that we have the correct one. If more than one are found, we throw an error. Name/Email can be set with `BOOT_GPG_USER`
 3, Default signing key is the first one returned by `(keyring/list-public-keys keyring)`. This will work on a straightforward GPG setup. If the user follows best practices and has derived subkeys from his master keypair, he can set those  with `BOOT_GP_SIGNING_KEY_ID`  and `BOOT_GP_ENCRYPTING_KEY_ID`.


How does this sound?

**Comment by danielsz** [comment]
https://github.com/boot-clj/boot/pull/274

**Comment by Deraen** [comment]
https://github.com/boot-clj/boot/pull/311/files is now merged

**Comment by micha** [comment]
This ticket is ready to close?

**Comment by Deraen** [comment]
I think so.

**Comment by micha** [comment]
Sweet!
