### ISSUE TITLE
boot -u downgrades the clojure version

### ISSUE THREAD

**Issue by schmir** [boot-clj/boot#256]
After running boot -u I ended up with the wrong clojure version. It
"downgraded" the used version from 1.7 to 1.6:

    (local) ~ % boot -V
    #https://github.com/boot-clj/boot
    #Wed Jul 15 16:11:10 CEST 2015
    BOOT_CLOJURE_VERSION=1.7.0
    BOOT_VERSION=2.1.2
    #App version: 2.0.0
    (local) ~ % boot -u
    #https://github.com/boot-clj/boot
    #Wed Jul 15 16:11:23 CEST 2015
    BOOT_CLOJURE_VERSION=1.6.0
    BOOT_VERSION=2.1.2
    #App version: 2.0.0
    (local) ~ % boot -V
    #https://github.com/boot-clj/boot
    #Wed Jul 15 16:11:28 CEST 2015
    BOOT_CLOJURE_VERSION=1.6.0
    BOOT_VERSION=2.1.2
    #App version: 2.0.0

That's a bit surprising.

Then next problem I ran into is, that I've got [org.clojure/clojure
"1.7.0"] in my project dependencies. boot didn't complain and happily
put two versions of clojure on the classpath.

With that classpath I ran into the same error like in
https://github.com/boot-clj/boot/issues/210.

**Comment by martinklepsch** [comment]
@schmir do you have a `boot.properties` file? AFAIK `boot.properties` is the only reliable way to pin the used Clojure version.

**Comment by schmir** [comment]
yes, I had a boot.properties file.

**Comment by micha** [comment]
The version downgrading behavior has been fixed; I can't reproduce it in master. Feel free to reopen if this isn't the case.
