### ISSUE TITLE
Repl result colour is illegible in a terminal with a dark background

### ISSUE THREAD

**Issue by nogden** [boot-clj/boot#263]
The following should demonstrate the problem.
<img width="345" alt="velody-friend1" src="https://cloud.githubusercontent.com/assets/3968417/9070235/4e3feeb2-3ae6-11e5-9187-7fcf01753454.png">
I haven't found any way of customising the colour used. Currently, my only option seems to be to use the `--no-color` flag, which is less than ideal.

**Comment by Deraen** [comment]
You should check your terminals preferences. Command line apps don't directly set the color but use general colors (e.g. "blue") which is defined by the terminal app.

**Comment by martinklepsch** [comment]
Looks like this for me: 
![screenshot 2015-08-04 21 34 52](https://cloud.githubusercontent.com/assets/97496/9070565/b15e5042-3af0-11e5-8ec8-888db267376e.png)

**Comment by nogden** [comment]
My bad. I hadn't realised this. Thanks for your help.
