### ISSUE TITLE
uber task doesn't handle pom dependencies properly

### ISSUE THREAD

**Issue by aaronc** [boot-clj/boot#272]
`boot.pod/resolve-dependency-jars` also returns `pom` dependencies and these are passed to `boot.pod/unpack-jar` which causes a `java.util.zip.ZipException` when trying to open the pom as a zip file. Should be just a matter of putting a simple exclusion filter somewhere but not sure where the best place to put it is.

**Comment by micha** [comment]
I think #291 is reporting the same issue, fixed in #292 and merged with master. If this isn't the case please feel free to reopen :)
