### ISSUE TITLE
Dependency retrieval fails when moving to 2.2.0

### ISSUE THREAD

**Issue by kgxsz** [boot-clj/boot#273]
I recently did a `boot -u` which moved me to `2.2.0` and I noticed that my build task fails on dependency retrieval:

```
...

Retrieving js-1.6R7.jar from https://repo1.maven.org/maven2/
             clojure.lang.ExceptionInfo: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: boot.App.getClojureName()Ljava/lang/String;
    data: {:file
           "/var/folders/3j/nly7k42d7djcyy011vp70cdr0000gn/T/boot.user5563009777290404995.clj",
           :line 17}
java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: boot.App.getClojureName()Ljava/lang/String;
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: boot.App.getClojureName()Ljava/lang/String;
            java.lang.NoSuchMethodError: boot.App.getClojureName()Ljava/lang/String;
                  boot.pod/make-pod        pod.clj:  458
     adzerk.boot-cljs/eval432/fn/fn  boot_cljs.clj:  150
clojure.core/binding-conveyor-fn/fn       core.clj: 1916
```
So I set the following environment variables:
```
export BOOT_CLOJURE_VERSION=1.7.0
export BOOT_VERSION=2.0.0
```
I then nuke my `~/.m2` directory and rerun my build task, and all is well.

Here are my dependencies in my `boot.build`:
```
  :dependencies '[[org.clojure/clojure "1.7.0"]
                  [org.clojure/clojurescript "0.0-3308"]
                  [adzerk/boot-cljs "0.0-3308-0"]
                  [adzerk/boot-cljs-repl "0.1.10-SNAPSHOT"]
                  [adzerk/boot-reload "0.3.0"]
                  [pandeiro/boot-http "0.6.2"]
                  [org.martinklepsch/boot-garden "1.2.5-4"]
                  [org.omcljs/om "0.8.8"]
                  [cljsjs/d3 "3.5.5-3"]
                  [prismatic/om-tools "0.3.10" :exclude [prismatic/schema
                                                         prismatic/plumbing]]
                  [prismatic/schema "0.4.2"]
                  [prismatic/plumbing "0.4.3"]
                  [prismatic/dommy "1.0.0"]
                  [garden "1.2.5"]])


```

Not sure what is going on here. Any ideas?

**Comment by martinklepsch** [comment]
You need to update your `boot` binary. The download link for 2.2.0 can be found here: https://github.com/boot-clj/boot/releases/tag/2.2.0

From the Readme:

> **Note:** The following instructions will install the boot.sh/boot.exe wrapper, i.e., a very thin shim on top of Maven to load "the real Boot." After you have the wrapper installed, you can run boot -u at any time to update Boot's JAR files and keep up to date. The wrapper itself changes (and thus requires an update) much less frequently.

**Comment by martinklepsch** [comment]
The error is caused by using the `2.2.0` JARs and the older `2.0.0` binary. Pinning to `2.0.0` through `$BOOT_VERSION` fixes the problem because it instructs the binary (`2.0.0`) to use the JARs in `2.0.0`.

Hope this helps :)

**Comment by kgxsz** [comment]
That did the job - cheers @martinklepsch.
