### ISSUE TITLE
[uber] Some dependencies require their pom.properties file

### ISSUE THREAD

**Issue by martinklepsch** [boot-clj/boot#278]
[Postal](https://github.com/drewr/postal) looks up it's version [at runtime](https://github.com/drewr/postal/blob/master/src/postal/support.clj#L58-L62) be looking at `META-INF/maven/com.draines/postal/pom.properties` which is excluded by the uberjar task by default:

```clj
#{#"(?i)^META-INF/[^/]*\.(MF|SF|RSA|DSA)$"
  #"^((?i)META-INF)/.*pom\.(properties|xml)$"
  #"(?i)^META-INF/INDEX.LIST$"}
```

Postal function for reference:
```clj
(defn pom-version []
  (let [pom "META-INF/maven/com.draines/postal/pom.properties"
        props (doto (Properties.)
                (.load (-> pom io/resource io/input-stream)))]
    (.getProperty props "version")))
```

**Comment by martinklepsch** [comment]
In this regard the docstring for the `uber` task are also a bit confusing.
```
Conj MATCH onto the set of regexes that paths must not match.
```
makes one think that the things mentioned as default will be the "base set" for the mentioned conj operation.

**Comment by martinklepsch** [comment]
I’m thinking we should include all `pom.properties` files but that would require a more strict rule to find the right `.properties` file in the fileset. Currently the following is used, causing my jar to build as tools.namespace :smile: 
```clj
(->> (core/output-files fileset)
                 (map core/tmp-file)
                 (core/by-name ["pom.properties"])
                 first)
```
[source](https://github.com/boot-clj/boot/blob/master/boot/core/src/boot/task/built_in.clj#L595-L619)

**Comment by martinklepsch** [comment]
There's https://github.com/drewr/postal/issues/66 tracking this in postal. I'm not sure if reaching for `pom.properties` is something jars are "allowed" to do. Someone who knows please step up :)

**Comment by micha** [comment]
Regarding the `uber` docstring: how about

```
Conj MATCH onto the set of regexes that paths must not match, replacing the default set.
```

**Comment by micha** [comment]
@martinklepsch The only thing it's getting from the pom.properties file is the info it uses to generate the name of the jar file. You can use the `-f` option to the `jar` task to name your uberjar something other than `tools.namespace.jar` :)

**Comment by martinklepsch** [comment]
Right! How did I not check task options here...?
The docstring suggestion sounds good to me.
Guess we can close this then?

**Comment by micha** [comment]
@martinklepsch i think it's still a bug...

I think the `jar` task is trying to be too smart when it sniffs for pom.properties files just to make a pretty jar name. I think the jar should just be called "project.jar" unless you give the `-f` option.

Similarly, I think the `install` and `push` tasks aren't being smart enough--they should accept an optional `--pom` option where you can specify the specific pom.xml file they should use to install/deploy when there are multiple poms in the jar.

So I think you're right, we should remove the pom.properties regex from the default excludes and modify some tasks. Does that seem right?

**Comment by martinklepsch** [comment]
> I think the jar task is trying to be too smart when it sniffs for pom.properties files just to make a pretty jar name. I think the jar should just be called "project.jar" unless you give the -f option.

:+1: 

> Similarly, I think the install and push tasks aren't being smart enough--they should accept an optional --pom option where you can specify the specific pom.xml file they should use to install/deploy when there are multiple poms in the jar.

Makes sense :+1: 

> So I think you're right, we should remove the pom.properties regex from the default excludes and modify some tasks. Does that seem right?

If the jar task outputs `project.jar` by default seems fine. What other tasks would need to be modified?

**Comment by Deraen** [comment]
This should work with the default options.

**Comment by Deraen** [comment]
This is fixed in master.
