### ISSUE TITLE
Can't run boot at all. Strange DependencyResolutionException.

### ISSUE THREAD

**Issue by emiln** [boot-clj/boot#280]
Hi. I've been using boot since its launch without any major issues, but today I had to reinstall everything on my laptop including the OS, and after installing OpenJDK and boot, I'm unable to use boot at all.

[Here's what happens.](https://www.refheap.com/108951)

Do you have any idea what's going on? I'm using Ubuntu 15.04, OpenJDK 1.8.0_45, and boot downloaded from your website today.

**Comment by emiln** [comment]
Never mind. Apparently I was lacking most of the CA Certs you'd expect. Running `update-ca-certificates -f` fixed everything.

**Comment by micha** [comment]
Happy to see the issue resolved, and it's great to have it recorded here in case others have the same problem. Thanks for taking the time to report! :+1:
