### ISSUE TITLE
New install error on Ubuntu 15.04: "the trustAnchors parameter must be non-empty"

### ISSUE THREAD

**Issue by optevo** [boot-clj/boot#281]
I have a fresh install of ubuntu 15.04 (command line only), with openjdk-8-jre-headless installed. When I installed boot and ran it the first time, I received a stack trace with a nested exception message:

"the trustAnchors parameter must be non-empty"

After searching stackoverflow, I found the following command needed to be run beforehand:
sudo update-ca-certificates -f

This is probably an edge case and more of an ubuntu/java config error but you may want to consider adding a note in the install section.

**Comment by micha** [comment]
Thanks for taking the time to report this! Perhaps a *Troubleshooting Installation* section of the wiki that links here?
