### ISSUE TITLE
Pod dependencies can't be downloaded in advance

### ISSUE THREAD

**Issue by Deraen** [boot-clj/boot#282]
In some environments (e.g. CircleCI) all the dependencies should be downloaded first for caching to work. E.g. boot-test depends on humane-test-output which will downloaded once the `test` task is run. Because CircleCI requires that all resources to be cached are downloaded in dependencies step, before test step, humane-test-output jar is on cached and will be downloaded for each build.

A solution could be to allow tasks to specify their dependencies using metadata and provide `deps` task to download all the dependencies.

**Comment by micha** [comment]
The way we do it eg. for docker (but it would also work for CI I'm sure) is pretty simple. Consider the case of the `repl` task which loads its dependencies lazily. We wanted to include the repl deps in the docker image at build time, so we did this:

```
export BOOT_LOCAL_REPO=/m2
boot repl -s
```

We set the local maven repo to the cache dir and then run the task. Since tasks don't block the pipeline this has the effect of simply downloading all the dependencies for the repl task, starting a server momentarily and then immediately exiting.

**Comment by Deraen** [comment]
I don't think there is an option in `test` task which wouldn't run the tests?

Besides, I'm thinking listing tasks which need to download additional dependencies is just a workaround.

**Comment by micha** [comment]
What about telling the test task to test no namespaces?

The problem is that the boot build is a program, not a static configuration map, so dependencies can be added dynamically at runtime. It seems like static metadata could never be a general solution.

**Comment by Deraen** [comment]
It's not possible to run `test` without namespaces and using non-existing namespace will fail.

**Comment by myguidingstar** [comment]
do you guys think this issue is related? https://github.com/adzerk-oss/boot-cljs/issues/97

**Comment by martinklepsch** [comment]
What about a convention for tasks that when invoked with --deps true they download all dependencies they could need and return the given fileset. This way the behavior can be as task specific as needed. Adding it to existing tasks also wouldn't be very hard.

**Comment by Deraen** [comment]
I opened an topic on CircleCI discussion board to find out if there is some way to cache files installed during test step there: https://discuss.circleci.com/t/unable-to-cache-dependencies-installed-during-test-step/1402

**Comment by Deraen** [comment]
I have solved this by running the build in CircleCI dependencies step instead of test step: https://github.com/cljsjs/packages/blob/master/circle.yml#L22

I have documented this on Wiki: https://github.com/boot-clj/boot/wiki/Running-Boot-on-CI-systems
