### ISSUE TITLE
Show task downloads all the dependencies

### ISSUE THREAD

**Issue by Deraen** [boot-clj/boot#283]
By the task name I would think this task should only display the dependencies. Instead it also downloads all the jars.

I think the dependency downloading should be provided as separate task.

**Comment by micha** [comment]
The show task simply resolves the dependencies. I think Aether is downloading things like poms and whatnot so it can trace versions and dependencies.

**Comment by Deraen** [comment]
Leiningen afaik only downloads pom but not jars.

**Comment by micha** [comment]
Does `:offline?` not prevent the downloading of the poms?

**Comment by Deraen** [comment]
Now I'm not sure if it even uses `:offline?` option. I'll check it even works like I think it does.

**Comment by Skinney** [comment]
Can confirm that `boot show -u` downloads all outdated dependencies (jars).

**Comment by micha** [comment]
Oh, that does make sense, because your build.boot script runs, so any dependencies the build.boot needs will be downloaded. I don't think this is a bug, after all. Is there any reason why downloading the project dependencies as they are in the `:dependencies` setting is unacceptable?

**Comment by micha** [comment]
I don't think this is actually a bug. Feel free to reopen if I'm wrong about that.
