### ISSUE TITLE
Improve error message when "optarg" is missing

### ISSUE THREAD

**Issue by pandeiro** [boot-clj/boot#285]
If you write a task like this:

```
(deftask do-something
  [s some-arg str "This is some arg"]
  ...)
```

...and pass it a string with `--some-arg`, Boot will error out, saying "Option :some-arg must be a string" -- even though you passed it a string.

It seems the problem is actually that the third arg should be the [optarg](https://github.com/boot-clj/boot/wiki/Task-Options-DSL#anatomy), unless I'm mistaken. If that is the case, a better error message would be helpful.

**Comment by martinklepsch** [comment]
Especially when users specify anything but `bool` as type for the option this should be warned about.
