### ISSUE TITLE
Improve error message

### ISSUE THREAD

**Issue by jtollison78** [boot-clj/boot#286]
It was suggested (on slack) that I open an issue here. This is my first one...

I'm still feel like a total beginner with build tools. I'm trying to use clj-firmata, so I started a test project and added 2 dependencies to both .boot and project.clj files. The .boot is here: https://gist.github.com/jtollison78/25f012406746e700970d

Things work fine with "lein repl", "boot repl", or "lein deps"...

But when I try "boot development" or "boot deps", I get: 
"? Caused by: Could not find artifact com.sparetimelabs:purejavacomm:jar:0.0.22 in http://repo1.maven.org/maven2/ (http://repo1.maven.org/maven2/)"

Any help would be appreciated. Thanks, John

**Comment by alandipert** [comment]
Hey @jtollison78 sorry for the late reply on this!

Boot2 isn't compatible with Boot1 `.boot` files, which it looks like the build.boot you posted is for.  Here is an example of a Boot2 build.boot: https://github.com/alandipert/hoplon-contacts-demo/blob/master/build.boot

Feel free to ping me on GChat when you get this, happy to help further.

**Comment by jtollison78** [comment]
Hmm... I know the 2 aren't compatible, and I feel like I should've seen that if that was the reason. But the person with the potential project stopped communicating shortly after I posted, and I haven't touched it since. Likewise, the delay in your response wasn't a problem. I guess I'll close this, and if I have the same problem in the future, and it's not a boot version problem, I'll come back.

Thank you.
