### ISSUE TITLE
Uber task doesn't include dependency pom files and jar task doesn't work if there are multiple pom files

### ISSUE THREAD

**Issue by Deraen** [boot-clj/boot#301]
Uberjars should contain pom files for all dependencies because the dependencies can and will presume that they can access their own pom files in classpath. E.g. https://github.com/drewr/postal/blob/master/src/postal/support.clj#L88
(Leiningen includes pom files for all dependencies in uberjars).

Uber task can be fixed by removing exclude here: https://github.com/boot-clj/boot/blob/master/boot/pod/src/boot/pod.clj#L321

Second problems is that once uber task adds all the pom files to fileset, jar task wont work as it tries to use the first pom file in fileset form jar name etc.

**Comment by martinklepsch** [comment]
See https://github.com/boot-clj/boot/issues/278

**Comment by Deraen** [comment]
Ah, thanks
