### ISSUE TITLE
Null task does not copy output-files

### ISSUE THREAD

**Issue by martinklepsch** [boot-clj/boot#304]
```clojure
;; https://github.com/boot-clj/boot/wiki/Tasks#the-null-task
(deftask null [] identity)
```
I'd expect `boot null` to just copy all files in `:resource-paths` and `:asset-paths` into `target/` but it doesn't because `boot.core/sync-target` only syncs files when there's a difference between the initial and the result fileset. When there's no transformation (i.e. null task) on the fileset there is no difference of course.

```clojure
(defn- sync-target
  "FIXME: document"
  [before after]
  (let [tgt  (get-env :target-path)
        diff (fileset-diff before after)]
    (when (seq (output-files diff)) ; <------------------------- false with null-task 
      (binding [file/*hard-link* false]
        (apply file/sync! :time tgt (output-dirs after)))
      (file/delete-empty-subdirs! tgt))))
```

I'm not sure what the best way to support this would be but one way could be to check if there's a `target/`dir already with files with an mtime before the boot invocation. All other ideas I had involve some sort of tracking if it's an "initial run" which seems clumsy as it would need to couple to the `watch` task somehow.

**Comment by alandipert** [comment]
From the [Target Directory](https://github.com/boot-clj/boot/wiki/Target-Directory) wiki page:

> ...if no task in the pipeline committed any new file to the fileset, then the target directory will not be modified at all—tasks that only read things from the fileset or use their own private temp directories will not affect the target directory. This is to prevent boot repl and similar tasks from wiping the target directory every time they're run.

**Comment by micha** [comment]
Discussion moved to #305
