### ISSUE TITLE
[wishlist] clojurescript-hosted boot with full support for clojurescript

### ISSUE THREAD

**Issue by benwbooth** [boot-clj/boot#306]
Now that clojurescript is [self-hosting](https://swannodette.github.io/2015/07/29/clojurescript-17/) and largely shares the same code base as clojure, would it be possible to compile boot to JS code using clojurescript and host it using node.js? This might allow running a clojurescript REPL and using boot to run clojurescript scripts. I have seen these projects:

https://github.com/adzerk-oss/boot-cljs-repl
https://github.com/kanaka/cljs-bootstrap

Do any of these help? I guess what I'm asking is, could native support for writing clojurescript projects and running scripts be implented more easily now that clojurescript is self-hosting?

**Comment by martinklepsch** [comment]
@benwbooth There are parts of boot that could probably be implemented in ClojureScript and Clojure. However a very significant ingredient is the Java Classpath and all things associated with it. Due to that I don't think porting boot to ClojureScript is going to be feasable/practical anytime soon.

Out of curiosity, where do you see the benefits of Boot-in-CLJS?

**Comment by arichiardi** [comment]
@martinklepsch one of the benefits that I see is speed for scripting, I know this is more like a build tool than a scripting tool, but I wish I could have both :+1: I so like the task and the fileset abstraction and would love to have a fast scripting tool that gives me that.

I know Micha's suggestion is basically to use `bash` where possible, but I am more lazy maybe, and usually if I can use boot for every task I tend to do it.

Also, I have noticed some people really dislike having to deal with the JVM when developing cljs apps (why do I need to pay the high price of the JVM for that?). I know I know, but it is what it is.

I am actually looking more and more at "cljs-only alternatives" like [calvin](https://github.com/eginez/calvin).

Anyways, my 2 cents here.

**Comment by martinklepsch** [comment]
Porting Boot to CLJS is a huge project and probably it would be much easier to rebuild something like Boot in ClojureScript from scratch. For some simpler things there's [mach](https://github.com/juxt/mach) now as well.

I will close this just to clear out older issues without clear actions to take, feel free to reopen if you want to work on this. 🙂
