### ISSUE TITLE
boot Script format and refer-clojure

### ISSUE THREAD

**Issue by zeneofa** [boot-clj/boot#307]
Hi,

I am new to clojure and I really like the boot scripting way of doing things, as I primarily know python, this feels more at home. I am trying to reconcile some of the differences between lein, boot and the different ways of doing things with clojure. 
The script format does not require the namespace identification, but in this namespace identification from lein and other boot code I see you can do the following:

    (ns somename
        (:refer-clojure :exclude [* - + / == min max])
        (:require [clojure.core.matrix.operators :refer :all]))

To suppress the warnings from overwriting/replacing the given commands, what is the boot scripting equivalent to this, where you use:

    (set-env! :dependencies '[[net.mikera/core.matrix "0.42.0"]])
    (require '[clojure.core.matrix.operators :refer :all])

I have tried using the namespace method above, but then running as a script does not work:
    
    chmod u+x my_cool_clojure_script.clj
    ./my_cool_clojure_script.clj

**Comment by alandipert** [comment]
Hello, here's something to try:

```clojure
(set-env! :dependencies '[[net.mikera/core.matrix "0.42.0"]])

(doseq [sym '(* - + / == min max)]
  (ns-unmap 'boot.user sym))

(require '[clojure.core.matrix.operators :refer :all])
```

**Comment by zeneofa** [comment]
That worked perfectly, thnx!
