### ISSUE TITLE
Error: Could not find or load main class boot.App

### ISSUE THREAD

**Issue by alvipeo** [boot-clj/boot#308]
This is on Windows 10.

I'm new to all this so I copied boot.exe to system32 and run it as boot -h. And I got this error.

**Comment by micha** [comment]
@alvipeo Can you please re-download boot.exe and try again?

**Comment by alvipeo** [comment]
Looks like it works now.

**Comment by micha** [comment]
Good to hear it! Thanks for reporting back :)
