### ISSUE TITLE
standard-jar-exclusions don't work on Windows

### ISSUE THREAD

**Issue by ajoberstar** [boot-clj/boot#316]
The [standard-jar-exclusions](https://github.com/boot-clj/boot/blob/master/boot/pod/src/boot/pod.clj#L319) (used by uber), don't work on Windows (seemingly due to slash direction). I had to do [this](https://github.com/ajoberstar/clj-dotfiles/blob/89e435d7daf1845225ee0ceb75a4a3b3cf597600/build.boot#L16) to get it to work.

Would you accept a PR to handle both forward and backslashes in those exclusions? Or is there somewhere more general that those paths could be normalized? (which would seem preferable)

**Comment by micha** [comment]
@ajoberstar Thanks for the report! A PR would be most welcome!

**Comment by ajoberstar** [comment]
Sounds good. I'll plan to send one this week. Do you have a preference between these two options?

1. Update `standard-jar-exclusions` to handle both forward and back slashes
2. Update [match-filter](https://github.com/ajoberstar/boot/blob/master/boot/pod/src/boot/file.clj#L202) to normalize the paths (to forward slashes) before trying to match them

My preference would be number 2, but I wonder if it would be considered a breaking change.

**Comment by ajoberstar** [comment]
Sorry for the long delay, but I put together a PR now using approach number 2 from above.
