### ISSUE TITLE
Include more :src-paths examples in documentation

### ISSUE THREAD

**Issue by joshhead** [boot-clj/boot#32]
If I have a build.boot file that references my src directory, I can require and use namespaces from that code.

For example, with these files

    .
    ├── build.boot
    └── src
        └── my_namespace
            └── app.clj

src/my_namespace/app.clj

    (ns my-namespace.app)
    
    (defn start []
      (println "Hello World"))

build.boot

    (set-env! :src-paths #{"src"})
    
    (require '[my-namespace.app :as app])
    
    (deftask run
      "Run my app"
      []
      (app/start))

I can execute `boot run` and it will print Hello World

    $ boot run
    Hello World

It wasn't obvious to me from the docs that this would work.

From the docs I can see three ways to run Clojure code in boot:
* Pull in a dependency from Maven
* Include the source code directly in a .boot script.
* Build a jar

I initially assumed source paths were just referenced by build tasks, which consume Clojure or ClojureScript source code. But it looks like the source is actually compiled and available within .boot scripts.

I was looking for something like "lein run" to load code from a source path and execute it, but it took me a while to figure out how to do it.

I think some more explanation and examples about :src-paths would be helpful in understanding boot.

**Comment by micha** [comment]
Fixed in 5543ab89322357440458dc7058d579dc1b1c9e5e

**Comment by joshhead** [comment]
Dig the new example! Thanks!

**Comment by micha** [comment]
Thank you, it took a little while but it finally got done :)
