### ISSUE TITLE
Watch task should merge new fileset with the one passed to watch task

### ISSUE THREAD

**Issue by martinklepsch** [boot-clj/boot#330]

**Comment by micha** [comment]
I can't reproduce this. See https://github.com/boot-clj/boot/blob/master/boot/core/src/boot/core.clj#L658 and https://github.com/boot-clj/boot/blob/master/boot/core/src/boot/task/built_in.clj#L232.

**Comment by martinklepsch** [comment]
@pandeiro reported this in combination with boot reload and boot cljs repl. Some specific ordering was needed. I think things didn't work if repl task came before watch.

**Comment by pandeiro** [comment]
I can come up with a minimal repro next week. Thanks for looking into this
guys.

**Comment by pandeiro** [comment]
So here's an example: https://github.com/pandeiro/jamal/tree/cljs-repl-before-watch

If you compare that branch with `master`, the only difference is where the `cljs-repl` task it placed: before and after `(watch)` , respectively.

**Comment by martinklepsch** [comment]
I created a more minimal reproduction case, will try to figure out what's going wrong.
https://github.com/martinklepsch/watch-bug 

@micha let me know if this is expected for some reason.

**Comment by micha** [comment]
@martinklepsch thanks for the repro case, I see what the problem is now. :+1: :rocket:

**Comment by martinklepsch** [comment]
@micha I just found it too! :smile:

**Comment by micha** [comment]
```
(defn reset-fileset
  "Updates the user directories in the fileset with the latest project files,
  returning a new immutable fileset. When called with no args returns a new
  fileset containing only the latest project files."
  [& [fileset]]
  (let [fileset (when fileset (rm fileset (user-files fileset)))]
    (sync-user-dirs!)
    (-> (new-fileset)
        (add-user-asset (first (user-asset-dirs)))
        (add-user-source (first (user-source-dirs)))
        (add-user-resource (first (user-resource-dirs)))
        (update-in [:tree] merge (:tree fileset)))))
```
