### ISSUE TITLE
Discussion: Should Boot track some usage data?

### ISSUE THREAD

**Issue by martinklepsch** [boot-clj/boot#332]
To better understand how people use Boot it would be helpful to track some data when Boot is being used.

##### Some examples for data that would be interesting to track:

- Version of Boot being used
- Version of Clojure being used
- Number of files in fileset
- Loaded/Used namespaces

##### Regardless of the way we choose to implement this or not the following things are important:

- Fully Opt-In
- Data must be fully anonymous
- Tracking should not have any performance impact
- Easy visibility on what exactly is being tracked

I assume there are many people with strong feelings with regards to something like this so communicating and getting people's feedback is probably a very important part of this.

That said my personal opinion is that with more information we can make better tools.
OSS should not pass up on the opportunities created by insight through additional data (within reason of course).

**Comment by Deraen** [comment]
I don't have much preferences to either option but: We shouldn't make the same mistake as Bower did.

They asked user to opt-in on the first run, but didn't check if it was being running on CI system, so loads of automated builds broke because they were waiting for user input.

Also, loaded/used namespaces information could contain secret data if the namespace contains reference to customer or the project name.

**Comment by alandipert** [comment]
I would rather we didn't collect any information.  I don't think the potential benefit of collecting this kind of data outweighs the risk and effort associated with anonymizing it and maintaining the code needed to collect the data responsibly.

Moreover, there is risk associated with just having the data, even if we managed to collect it with some degree of anonymity and without introducing the kinds of bugs @Deraen mentioned.  Where would we aggregate it?  Who would be legally responsible for it?  Personally, I am unwilling to be responsible for retaining data about peoples' software habits.  Data of all types is prone to unknowable abuses in the future, and the act of retention is what opens the door.

I can understand why proprietary software for non-technical end-users would be useful to collect and analyze.  But Boot is in a different boat.  We are an open project with a highly technical and communicative userbase.  I don't think we suffer from a lack of information about how people are using Boot and what problems they are having.

All of that said, like @martinklepsch I'm very interested in hearing other peoples' thoughts.  I am always happy to revise my opinion.  The only thing I'm not open to is being responsible for keeping the data.  Presumably, for this to happen, someone would need to be.

**Comment by micha** [comment]
I think @alandipert made some good points. Let's close this for now, unless there is interest in pursuing it further.

**Comment by martinklepsch** [comment]
I think I also agree with what Alan and also some others said to me when I asked them. There are plenty of potential downsides and less upsides. 

That said I find it unfortunate that for open source projects it seems generally troublesome to collect data. Would be interested in further discussion of the general idea.

**Comment by alandipert** [comment]
@martinklepsch maybe we can make tools to make it easier for people who want to provide us information to do so?

For instance, we could make a task that prints some standard diagnostic output people could add to issues.  I have imagined a `boot doctor --diagnostics` or similar that prints OS, profile, build.boot, env vars, etc.

Another way we can collect data from the community is with a regular survey.
