### ISSUE TITLE
~/.boot/boot.properties required?

### ISSUE THREAD

**Issue by martinklepsch** [boot-clj/boot#337]
So `boot -u` writes to `~/.boot/boot.properties`. Without having this file any boot invocation will result in:
```
Retrieving boot-2.4.2.jar from https://clojars.org/repo/
Please download latest Boot binary: https://github.com/boot-clj/boot#install
```
If no `$BOOT_VERSION` is given or `~/.boot/boot.properties` does not exist I think it would make most sense to just use the version of the binary that's being used?

**Comment by micha** [comment]
I just tested with the latest `boot.sh` and I get the following:

```
$ rm -rf ~/.boot
```
```
$ boot
```
```
Downloading https://github.com/boot-clj/boot/releases/download/2.5.2/boot.jar...
Running for the first time, BOOT_VERSION not set: updating to latest.
#http://boot-clj.com
#Thu Dec 24 12:56:28 EST 2015
BOOT_CLOJURE_NAME=org.clojure/clojure
BOOT_VERSION=2.5.2
BOOT_CLOJURE_VERSION=1.7.0
```

I think this does the right thing now when `BOOT_HOME/boot.properties` doesn't exist.
