### ISSUE TITLE
boot.pod/with-eval-in -> Method code too large! 

### ISSUE THREAD

**Issue by podviaznikov** [boot-clj/boot#339]
I'm getting 
```
clojure.lang.ExceptionInfo: java.lang.RuntimeException: Method code too large!, compiling:(NO_SOURCE_PATH:0:0)
```

When calling `(boot.pod/with-eval-in (boot.pod/make-pod) ...)` with moderate size function.

More details https://github.com/hashobject/perun/issues/49.

What would be the best way to fix this?

**Comment by micha** [comment]
@podviaznikov hi! i was just starting to work on this!

**Comment by micha** [comment]
I'm going to try using input streams instead of strings to pass the information from pod to pod.

**Comment by podviaznikov** [comment]
@micha thanks! good to hear

**Comment by nicorikken** [comment]
+1

**Comment by micha** [comment]
@podviaznikov Can you please try with latest master branch? See commit message for how to do it. Is this solution acceptable?

**Comment by podviaznikov** [comment]
@micha how can I run boot#master locally?

**Comment by podviaznikov** [comment]
I see, there are instructions for that https://github.com/boot-clj/boot#hacking-boot

**Comment by podviaznikov** [comment]
Hmm,

I'm still getting:
```
clojure.lang.Compiler$CompilerException: java.lang.RuntimeException: Method code too large!, compiling:(NO_SOURCE_PATH:0:0)
             java.lang.RuntimeException: Method code too large!
    clojure.asm.MethodWriter.getSize                 MethodWriter.java: 1872
 clojure.asm.ClassWriter.toByteArray                  ClassWriter.java:  775
                                 ...
                   clojure.core/eval                          core.clj: 3081
                   boot.pod/eval-in*                           pod.clj:  224
                                 ...
                   boot.pod/eval-in*                           pod.clj:  227
              io.perun/render-in-pod                         perun.clj:  376
```

Not sure if I updated boot correctly, but it seems that I'm.
```
boot -V
#http://boot-clj.com
#Wed Nov 11 20:38:38 PST 2015
BOOT_CLOJURE_NAME=org.clojure/clojure
BOOT_CLOJURE_VERSION=1.7.0
BOOT_VERSION=2.5.0-SNAPSHOT
```

**Comment by micha** [comment]
@podviaznikov and you're using the new `boot.pod/send!` function to wrap the large data?

**Comment by podviaznikov** [comment]
@micha no, I didn't. Missed that part. Trying now

**Comment by podviaznikov** [comment]
It works now!

**Comment by micha** [comment]
Great! I'll close this ticket. I think there might be a more clever way to do this so that you don't need to explicitly call the `send!` function, but I don't quite have it yet.

**Comment by podviaznikov** [comment]
Yeah, that works for me. That is why I didn't try to use `send!` at the first place. Didn't expect that to be change of the interface. Thank you again
