### ISSUE TITLE
Default push task options / default deploy repository

### ISSUE THREAD

**Issue by Deraen** [boot-clj/boot#341]
Should we set some defaults? What would be the correct place to set these settings? Do we just leave it to user or project to set the values?

Current push task doesn't have either default deploy repository name (usually clojars) or default credentials (I think `:gpg` would be the most useful default).

I think usually it's user's (not project's) choice to select source for credentials. One way to do this would be for user to call `task-options!` from `profile.boot`. However, I don't think this is a perfect solution as it doesn't allow setting default sources for different repositories. I think that would require separate `:deploy-repositories` property on Boot env?

```clj
;; Everything set on build.boot
(push :repo "clojars" :repo-map {:username :gpg :password :gpg})

;; Setting default credential source on profile.boot
(task-options! push {:repo-map {:username :gpg :password :gpg}})

;; Setting different credential sources for different deploy repos?
???
```

**Comment by micha** [comment]
@Deraen It seems like we want to separate the credentials from the repository spec. This makes sense to me. I think maybe we want to add `:repo-username`, `:repo-password`, and (perhaps) `:repo-passphrase` options to the task? I'm not really sure what the difference between password and passphrase is, but I'm pretty sure you sometimes need one and sometimes the other.

Anyway, these options could have the special keyword things, too:

```
(task-options!
  push {:repo-username :env
        :repo-password :env}
  ...
```

**Comment by micha** [comment]
@Deraen does the `configure-repositories!` function satisfy these requirements?

**Comment by Deraen** [comment]
I think so.
