### ISSUE TITLE
[feature request] [watch task] ignore dotfiles

### ISSUE THREAD

**Issue by jaredly** [boot-clj/boot#348]
vim creates temporary files (prefixed with a `.`) while editing, which cases the `(watch)` task to needlessly fire. It would be great to have watch ignore dotfiles altogether, and it would also be nice to be able to specify a whitelist or blacklist of files to care about.

**Comment by Deraen** [comment]
For now, the preferred solution is to configure your editor to write tempfiles and backups elsewhere.

For Vim this should disable these temp files:
```vim
set noswapfile
```

**Comment by daveyarwood** [comment]
You can also configure Vim to put its swap files elsewhere:

```
" keeps vim swap files from interfering w/ boot-clj
set backup
set swapfile
set backupdir=~/.vim-tmp
set directory=~/.vim-tmp
```

**Comment by jaredly** [comment]
yeah, that's one way to do it. But would it be too difficult to add a config option to boot as well? I like having the tmpfiles in the same directory so that I can easily `rm` them when necessary

**Comment by micha** [comment]
There are performance implications, and it adds complexity. It would need to be carefully designed.
