### ISSUE TITLE
Wildcard short option name stops validating in 2.5.0-SNAPSHOT

### ISSUE THREAD

**Issue by jaen** [boot-clj/boot#350]
I've updated boot locally to `c210c5be160298177843493fa767454fc6cf4b60` to play with it, but it didn't seem to work with some plugins. It turned out stricter task DSL argument validation marks some currently valid task options invalid.

One example are `boot-immutant` tasks (parts ommited for clarity):

```
[_ guide                bool  "Display the usage guide. All other options ignored [false]"
 i init-fn         FN   sym   "The 'main' function to call on deploy [nil]"
 d dev                  bool  "Generate a 'dev' war [false]"
 ...
 _ nrepl-start          bool  "Request nrepl to start [dev]"
 _ nrepl-host      HOST str   "Host for nrepl to bind to [\"localhost\"]"
 ...]
```
which throws `java.lang.Exception: malformed cli option: guide`.

It turned out that `_` wildcard short option name is responsible for that - when I give short name to the `guide` options it starts complaining about the next option with a wildcard for short name. When all options have short name, the validations passed.  
As far as I understand `_` is still a valid DSL value to signify the option doesn't have a short names, so this validation is probably wrong.

**Comment by Deraen** [comment]
This is probably the only commit which has changed task option stuff in a while: https://github.com/Deraen/boot/commit/1476952fece0b732492b836ec1bff362368ac2ed

**Comment by martinklepsch** [comment]
Or this one: https://github.com/boot-clj/boot/commit/a4db0ed9c88acae25e7995da420f46dbec78864d#diff-d0b4da22b2b13c478608b3b47f39b042R187

**Comment by Deraen** [comment]
Oh right, that looks more suspicious. Looks like a was looking at a fork so missed that.

**Comment by jaen** [comment]
Seems to have fixed the issue for me, thanks!.
