### ISSUE TITLE
Latest CIDER connection to repl -- ~/.boot/profile.boot settings that work.

### ISSUE THREAD

**Issue by Naomarik** [boot-clj/boot#352]
It took awhile for me to get CIDER working properly, and between the documentation here and CIDER's own, my `~/.boot/profile.boot` appears like below.

``` clojure
(require 'boot.repl)

(swap! boot.repl/*default-dependencies*
       concat '[[cider/cider-nrepl "0.10.0"]
                [refactor-nrepl "2.0.0-SNAPSHOT"]])

(swap! boot.repl/*default-middleware*
       conj 'cider.nrepl/cider-middleware)

(swap! boot.repl/*default-middleware*
       conj 'refactor-nrepl.middleware/wrap-refactor)

```
 
Make sure this is in your build.boot dependencies.
```
                 [adzerk/boot-cljs-repl     "0.3.0"      :scope "test"]
                 [weasel                  "0.7.0"  :scope "test"]
                 [com.cemerick/piggieback "0.2.1"  :scope "test"]
                 [org.clojure/tools.nrepl "0.2.12" :scope "test"]
```

Just thought this might benefit someone since the current documentation refers to an older CIDER.

**Comment by Deraen** [comment]
https://github.com/boot-clj/boot/wiki/Cider-REPL is now updated.

**Comment by hlolli** [comment]
Took me a while too to find out how to harvest the emacs command cider-jack-in-clojurescript so this helped.
