### ISSUE TITLE
windows boot.exe start failed

### ISSUE THREAD

**Issue by nsfan** [boot-clj/boot#353]
"This application requires a Java Runtime Environment 1.7.0"
Maybe the check method is not correct.

I dont have installed jre or jvm. But I use java apps with my "portable" jvm.
(I installed it a long time ago, and I copied from 'Program files' to other location/folder and then I uninstalled jdk)

So, I set the windows path to my jvm:
>> set path=D:\java\java8\jdk1.8.0_25\bin;%path%

But boot.exe did not recognize that.

I could start boot with:
>> java -jar boot.jar 

It downloaded all dependency jars.

>> java -jar boot.jar repl

and REPL is working fine

**Comment by micha** [comment]
Boot.exe is built with launch4j. Perhaps setting an environment variable will help it to find where you've installed Java--check out the [launch4j configuration docs][1] for more info.

[1]: http://launch4j.sourceforge.net/docs.html#Additional_jvm_options

**Comment by nsfan** [comment]
Ok. 
I checked launch4j. It is checking jre, jdk with regestry settings. 
(see: launch4j-3.8-win32.zip\launch4j\head_src\head.c file)
So, I can hack it from registry, but I dont want that.

Maybe a boot.bat file with this content is enough for me:
@echo off;
set path=D:\java\java8\jdk1.8.0_25\bin;%path%
java -jar boot.jar %*
