### ISSUE TITLE
Misleading warning about BOOT_EMIT_TARGET

### ISSUE THREAD

**Issue by jgrimes** [boot-clj/boot#356]
Implicit target dir is deprecated, please use the target task instead.
    Set BOOT_EMIT_TARGET='no' to disable implicit target dir.

should be

    Implicit target dir is deprecated, please use the target task instead.
    Set BOOT_EMIT_TARGET=no to disable implicit target dir.

**Comment by martinklepsch** [comment]
Closed via #357

**Comment by pate** [comment]
What should I do about this warning? I can't find a clear doc about it anywhere. How do I set an explicit target directory?

**Comment by mobileink** [comment]
Use the target task.  See [https://github.com/boot-clj/boot/wiki/FAQ](url)

**Comment by pate** [comment]
Thanks, @mobileink. (broken href, btw)
