### ISSUE TITLE
Push repo-map option doesn't work

### ISSUE THREAD

**Issue by Deraen** [boot-clj/boot#358]
Repo-map is being merged with `r` which will be a string in case of default Clojars repo.

**Comment by micha** [comment]
Ah, the default repos should really be in "canonical" format (i.e. maps). The `canonical-repo` function will handle any repos added by the user, guaranteeing that the repos in `:repositories` are always in canonical form.

**Comment by micha** [comment]
https://github.com/boot-clj/boot/blob/master/boot/core/src/boot/core.clj#L617

**Comment by micha** [comment]
and https://github.com/boot-clj/boot/blob/master/boot/core/src/boot/core.clj#L637 where this function is used to ensure repos are in map form when setting `:repositories`

**Comment by Deraen** [comment]
I updated PR to change the default repos to canonical form.

**Comment by micha** [comment]
Thanks! Do you think we should wrap the `pre-env!` with another call to `canonical-repo` just in case the user's `repo-config-fn` returns a bare url?

```clojure
(defmethod pre-env! :repositories   [key old new env] (->> new (mapv (fn [[k v]] [k (canonical-repo (@repo-config-fn (canonical-repo v)))]))))
```

**Comment by Deraen** [comment]
Wouldn't hurt but I think it's unnecessary.
