### ISSUE TITLE
jar task does not generate manifest

### ISSUE THREAD

**Issue by instilled** [boot-clj/boot#360]
Hi, 

I've been experimenting with `uber` and `jar` tasks in boot. It seems to me that `META-INF/MANIFEST.MF` may get overwritten if one already exists in the file-set in the `jar` task. This may happen if a library provides a manifest and is exploded in the `uber` task.

Example `bulid.boot`:

```clj
...
(deftask standalone
  "Build selfcontained, executable jar."
  []
  (comp
   (pom)
   (javac)
   (aot :namespace '#{my.ns})
   (uber :exclude #{#"(?i)meta-inf/.*\.(SF|DSA|RSA)"
                              #".*/test/.*"}))
   (jar :main 'my.ns.main)))
...
```

Running `boot standalone` I would expect a manifest entry with only the required properties, i.e `Manifest-Version: ...` and `Main-Class: my.ns.main`. But that does not happen if I depend on a library with existing Manifest. I assume this is due to how [update-jar#L74](https://github.com/boot-clj/boot/blob/master/boot/pod/src/boot/jar.clj#L74) works:

```clj
(defn update-jar!
  [jarfile old-fs new-fs attr main]
  (with-open [fs (fs/mkjarfs jarfile)]
    (fs/write! fs (create-manifest main attr) (io/file "META-INF" "MANIFEST.MF"))
    (fs/patch! fs old-fs new-fs)))
```

shouldn't it be: 

```
(defn update-jar!
  [jarfile old-fs new-fs attr main]
  (with-open [fs (fs/mkjarfs jarfile)]
    ;; lines swapped
    (fs/patch! fs old-fs new-fs))
    (fs/write! fs (create-manifest main attr) (io/file "META-INF" "MANIFEST.MF")))
```

If that's really the issue I'll happily provide a pull request.

Fabio

**Comment by micha** [comment]
@instilled Thanks for reporting the issue, and for taking the time to investigate. This is a bug, exactly as you describe. I'll add your fix to the 2.5.1 release we'll do today.
