### ISSUE TITLE
Invalid cross-device link when using uber-task

### ISSUE THREAD

**Issue by bonega** [boot-clj/boot#362]
I have confirmed that it works on `2.4.2` but not on `2.5.0`.  

System root is on a different device.
`~/.boot`, `~/.m2` and `~/git/projectdir` are all one the same device.

Howto reproduce. 

Simplified [boot.build](http://pastebin.com/T7UqnEae)
`boot uber`

It will work if `export BOOT_VERSION=2.4.2` is executed before boot cmd.

[traceback](http://pastebin.com/ieRfSvue)

`/tmp` is referenced in the traceback, shouldn't it be something like `~/.boot/cache/tmp/...`?

**Comment by micha** [comment]
@bonega i think i see the problem, and can make a fix for it in 2.5.1. Thanks for the detailed info!

**Comment by micha** [comment]
@bonega if you could test this to confirm the fix that would be awesome

**Comment by bonega** [comment]
@micha thanks for the speedy response.

Confirmed to be working.
But one thing is strange, but probably unrelated.

The uberjar in `target/` isn't named myproject-x.x.x.jar anymore.
`2.4.2` produces `target/myproject-0.1.0.jar`
 `2.5.1-SNAPSHOT` produces `target/project.jar`

**Comment by micha** [comment]
This change results from issues that arose around default uberjar exclusions and the logic that was previously in place to determine the "friendly name" of the jar file (see #278). In your case there is now more than one `pom.xml` file in your jar, so it doesn't know which one to use to get the project name and version from. You could use `sift` task to filter those out, or use the `--file` option of the `jar` task to set the name manually.

**Comment by bonega** [comment]
Thanks, you have been most helpful.
