### ISSUE TITLE
How do I use boot with submodule dependencies?

### ISSUE THREAD

**Issue by dustingetz** [boot-clj/boot#365]
Similar to lein checkouts. I don't want to run `lein install` in all my submodules - I want to be able to `git clone --recursive` and then run the build with no ceremony. Please forgive me if I have missed some documentation somewhere.

**Comment by dustingetz** [comment]
The submodules are forks of dependencies in the root project.

**Comment by martinklepsch** [comment]
Check `boot checkout --help`

**Comment by dustingetz** [comment]
Is it possible to do this without adding things to my local maven repo? I have multiple root projects each tracking the fast-moving subproject dependencies as a submodule/git sha, so they need to use their own copy, not some shared local maven version.

**Comment by micha** [comment]
You can use the git sha as the version when you install to maven, perhaps.

**Comment by martinklepsch** [comment]
Another option might be to just add the source dirs of your submodules to
the source-paths of the root project.

Installing into the local maven repo can be as fast as 0.2s when using
"boot watch build-jar" or similar.

**Comment by dustingetz** [comment]
What about my submodules' dependencies?

**Comment by martinklepsch** [comment]
With the source paths approach you'd need to handle that separately. Could
be automated by reading a dependencies.edn file from the submodule.

**Comment by micha** [comment]
Yes, this is why the checkout task consumes jars, it decouples the builds so the consumer doesn't need to know how to build the submodule and there can't be conflicts between the two.

**Comment by micha** [comment]
I recommend making a script that builds the submodules and installs to local maven. If you are clobbering versions with your submodules you can segregate them by putting `BOOT_LOCAL_REPO=<some path>` in a `boot.properties` file in the project directories, and the build will have its own maven cache.

**Comment by dustingetz** [comment]
Project maven cache fixes my concern, thank you.

How will the clojurescript case work? I am unclear in my mental model how this will be possible at all since clojurescript build artifacts are js files. If I add cljs subproject sources to root-project src-dirs, I will see local changes but will not have access to the subproject dependencies right?

**Comment by micha** [comment]
ClojureScript build artifacts are usually .cljs files, not compiled JS. This is the same as Clojure itself, in that AOT compilation of libraries is normally avoided. The ClojureScript source files in the subproject jars can be compiled seamlessly in your parent project's ClojureScript build.

**Comment by micha** [comment]
@dustingetz Did you get it working satisfactorily?

**Comment by dustingetz** [comment]
Yeah - clojurescript subproject with dependencies, published to local maven, with subproject source dir manually added to root project :source-paths, so the root project runs the watch script. If a subproject dependency changes we re-pubish a new jar, and restart the root project watch script. Thanks.

**Comment by aft-luke** [comment]
@dustingetz whats the syntax required to get this working? I've been fiddling around and cannot seem to find the right setup.

```clojure
;; boot file
...
:checkouts '[[my-org/my-proj "0.0.1"]]
:depencendies '[[my-org/my-proj "0.0.1"]]
...

;; example module I want to expose
(ns foo.core)
(defn some-stuff [] ...)

;; project-b
(ns proj-b.core
  (:require [foo.core :as foo]
;; or [my-org/my-proj.foo.core ?]
))

(foo/some-stuff args)
```

But I get a built-time error with `no such namespace`. I'm not sure what namespace I have wrong here...

**Comment by aft-luke** [comment]
Disregard... I figured out the issue was with a `(:require-macros` and the original --checkout works fun as defined above. Still at a loss for how to require a clojurescript module that defines .clj macros elsewhere, though.

**Comment by dustingetz** [comment]
I hoist all submodule cljs dependencies and source dirs to the root
project, it has barely held together for a couple months during early
development but we have just about outgrown it, it results in a lot of
broken builds, not sure what we are going to do next
