### ISSUE TITLE
is as-jar option to uber task being ignored?

### ISSUE THREAD

**Issue by instilled** [boot-clj/boot#366]
I was wondering how the `as-jars` option to the `uber` task is supposed to work. Checking the code for [uber](https://github.com/boot-clj/boot/blob/master/boot/core/src/boot/task/built_in.clj#L472) I can see no reference to the option. Should the `uber` task itself handle the `as-jars` option or should it be passed further down to, e.g. `boot.pod/unpack-jar`?

**Comment by micha** [comment]
The as-jars implementation was accidentally removed in 2.5.0, but restored in 2.5.2. https://github.com/boot-clj/boot/blob/master/CHANGES.md#fixed

**Comment by instilled** [comment]
@micha thanks. Wasn't aware of how fast boot development is :)

**Comment by instilled** [comment]
I'll close the issue.
