### ISSUE TITLE
Add option to show task to verify dependencies

### ISSUE THREAD

**Issue by tobias** [boot-clj/boot#375]
Similar to `lein deps :verify`. 

I have this working locally, I just have a couple of questions about how you would like to see the output. [tcrawley/boot-verify](https://github.com/tobias/boot-verify) just prints a flat list:

![e9276](https://cloud.githubusercontent.com/assets/2631/12064856/35d7ec92-af9b-11e5-89ff-e3c65d7b28d2.png)

My current `boot show --verify-deps` implementation shows the dependency tree with each dep prefixed with the verification status, and is really an enhancement to `boot show -d`:

![d8cc5](https://cloud.githubusercontent.com/assets/2631/12064863/633d442a-af9b-11e5-9413-0aa554028665.png)

Another option is to show the status after each dep:

![eb818](https://cloud.githubusercontent.com/assets/2631/12064893/e025b864-af9b-11e5-8655-e50a4772df68.png)

Yet another option (which I haven't yet tried to implement) is to modify `boot.util/print-tree` to allow for a per-entry prefix, which would allow me to display the verification status on the far left of the tree (which would be a blending of the `boot verify`-style output and `boot show -d`).

Do you have a preference for any of these four output options?

**Comment by alandipert** [comment]
Thinking about this myself, it seems to depend on how we intend people to use the output.

The tree-style output is for human consumption, and so it doesn't matter as much what we put in there.  I'm attracted to "flat" output because it's especially amenable to `awk` etc.

I vote we enhance `boot show -d` as per your second graphic.  It's unlikely anyone is consuming the output programmatically, and I feel personally that it's just as easy to read, especially with the coloring.

Other than that... maybe what we also want is an EDN output for `show` - dump everything we know about dependencies in a machine-readable format.

**Comment by micha** [comment]
I like the second example, but the signing status keywords are different lengths, which interferes with the ability to see the dependency graph clearly. So I think the third one is really the most useful. If you'd like to try putting the signature status on the far left I can probably add something to `print-tree` for that.

**Comment by micha** [comment]
Oh, also :+1: for just adding this functionality to `show -d`.

**Comment by tobias** [comment]
@alandipert - I agree - I think it would be useful to have an option to show that would emit whatever was requested as EDN - I'll file an issue for that.

I went ahead and modified `print-tree` to allow for a prefix fn, just to see what that would look like, and now have:

![bf427](https://cloud.githubusercontent.com/assets/2631/12067968/ada507ce-afd1-11e5-81a0-c42a2d10cd4c.png)

I like this, my only concern is that it may be harder to visually correlate the status with the dependency if the tree is deeply nested.

**Comment by tobias** [comment]
EDN output issue is #376.

**Comment by micha** [comment]
maybe instead of `:signed`, `:unsigned`, and `:bad-signature` we could use :heavy_check_mark:, :grey_question:, and :heavy_multiplication_x: ? Then they'd all be the same width and narrow. Not sure about unicode support on windows, though.

**Comment by micha** [comment]
I think this last iteration is the best one so far, i think the separation of the signature info from the graph make it easier to read because you can focus on one or the other.

**Comment by micha** [comment]
Actually, on second thought i think having the keys different lengths helps when the user has colors turned off, so the unicode idea is maybe not great.

**Comment by tobias** [comment]
My concern with the unicode characters is it's less clear what they mean. There is also a fourth option that I haven't shown: `:no-key`. This can occur if the public key hasn't been published.

What if we changed `:bad-signature` to `:bad-sig`? That would drop the column width from 14 to 9, and would preserve different lengths for each state.

**Comment by micha** [comment]
Sounds great to me.

**Comment by micha** [comment]
We could also maybe color the dependency symbol the same color as the signature status, to help with deeply nested dependencies?

**Comment by tobias** [comment]
That's a good idea, let me see what that would take.

**Comment by tobias** [comment]
That works pretty well - I submit a PR in a few:

![ae644](https://cloud.githubusercontent.com/assets/2631/12068237/6e0c57ce-afd7-11e5-831c-6d6467fbfca4.png)

**Comment by micha** [comment]
Merged with #377
