### ISSUE TITLE
apt-get install boot?

### ISSUE THREAD

**Issue by binarykitchen** [boot-clj/boot#379]
On Mac you can install via homebrew. Would be good to supply the same stuff for apt-get, for Linux machines. Equality :)

**Comment by micha** [comment]
And [Chocolatey NuGet][1], too.

Are you volunteering to maintain this? :)

[1]: https://chocolatey.org/

**Comment by binarykitchen** [comment]
@micha thanks - well, i wouldn't know where to start and was more like wondering if it's already out there, hidden somewhere ...

**Comment by micha** [comment]
Ah, yeah there isn't anything right now. I'm not really familiar with the process of submitting packages for the different Linux distributions. Seems like a bigger job than submitting to HomeBrew.

**Comment by daveyarwood** [comment]
This might be handy: https://github.com/jordansissel/fpm

**Comment by micha** [comment]
I think [linuxbrew][1] might be the answer. Boot doesn't require building and it has no dependencies other than Java, so packaging it is not difficult. The real pain is dealing with the bureaucracy of Linux distribution and packaging policies and procedures. Linuxbrew avoids needing to deal with all the distros individually, which is key.

[1]: http://brew.sh/linuxbrew/

**Comment by binarykitchen** [comment]
Whatever works best. Just make sure it is documented here and Ubuntu users are able to install, update and delete boot. These three are the most important use cases, nothing else. KISS.

**Comment by Deraen** [comment]
I don't know, I doubt many Linux users have Ruby installed. I avoid installing it myself.

**Comment by binarykitchen** [comment]
I don't care if linuxbrew requires Ruby. No big deal for me.

**Comment by arichiardi** [comment]
Agree with @Deraen, you would force to install a lot more deps then `boot` requires...probably an `apt-get` package is better...ok not for me as a `wget ...boot.sh` is enough (and usually I symlink to a local `git` repository)

**Comment by micha** [comment]
New binary releases will be exceedingly rare now that we have a robust implementation of `boot.sh`. The current version of `boot.sh` is compatible with all stable versions of Boot (i.e. 2.0.0 and later) and will be compatible with all future versions of Boot, as well. The `boot.sh` shim is so minimal and stable that we moved it into a [separate project altogether](https://github.com/boot-clj/boot-bin/).

I think the `wget` one-liner is pretty good for a first install...I think we can close this ticket for now.
