### ISSUE TITLE
uber task clearing project name based on as-jars parameter

### ISSUE THREAD

**Issue by cursork** [boot-clj/boot#383]
Some experimentation on the command line:

```
$ boot -V
#http://boot-clj.com
#Mon Jan 11 13:21:22 GMT 2016
BOOT_CLOJURE_NAME=org.clojure/clojure
BOOT_CLOJURE_VERSION=1.7.0
BOOT_VERSION=2.5.5

$ boot pom --project some-project --version 0.1.0 jar
[...]
Writing some-project-0.1.0.jar...

$ boot pom --project some-project --version 0.1.0 uber jar
[...]
Writing project.jar...

$ boot pom --project some-project --version 0.1.0 uber --as-jars jar
[...]
Writing some-project-0.1.0.jar...
```

I'd have thought the second case would also produce `some-project-0.1.0.jar`?

**Comment by martinklepsch** [comment]
@cursork the `uber` task explodes (unwraps) all dependency jars which may contain `pom.xml` files making it harder for the jar task to identify the correct one. If the jar name can't be determined with certainty a fall back `project.jar` is used. 

If you check `boot jar --help` you can see how to set the jar name manually. Hope that helps.

**Comment by cursork** [comment]
I can set the jar name manually, sure. But it's a bit redundant. I do wonder if `pom.xml` files shouldn't be caught in the default `exclude` set for the `uber` task though?

**Comment by martinklepsch** [comment]
@cursork This has been talked about before but I unfortunately don't remember much of it. This issue seems relevant at least: https://github.com/boot-clj/boot/issues/112

Maybe @micha can clear things up later or search for other uber related issues :)

**Comment by micha** [comment]
@cursork The `uber` task does not exclude _pom.xml_ files by default because some libraries look for their own POM on the classpath at runtime, but you can add `#"/pom.xml$"` to `boot.pod/standard-jar-exclusions` in your boot script. If there is exactly one _pom.xml_ entry in the JAR it will get a friendly name based on the artifact and group IDs in the POM.

**Comment by lachy-xe** [comment]
Would it be possible to add an argument to the `jar` task so you could select which `pom.xml` file to use? Similar to the one for the `install` task?

**Comment by micha** [comment]
I'll open a new ticket for the `jar` task argument, and close this one.
