### ISSUE TITLE
`boot new`: implicit target is deprecated

### ISSUE THREAD

**Issue by pesterhazy** [boot-clj/boot#402]
With `boot` 2.5.5 you get this warning:

```
bash-3.2$ boot -d seancorfield/boot-new new -t tenzing -n t1
Generating fresh 'lein new' tenzing project.
Implicit target dir is deprecated, please use the target task instead.
Set BOOT_EMIT_TARGET=no to disable implicit target dir.
```

For this use case (basically a command-line utility), the warning is not very helpful, and jarring for newcomers, especially since `boot new` (like `lein new`) is used to onboard people.

Will `BOOT_EMIT_TARGET=no` eventually become the default?

CC @seancorfield

**Comment by Deraen** [comment]
> Will BOOT_EMIT_TARGET=no eventually become the default?

Yes.

**Comment by micha** [comment]
One option is to set the property in the `new` task:

```clojure
(System/setProperty "BOOT_EMIT_TARGET" "no")
```

This will eliminate the warning.

**Comment by seancorfield** [comment]
Good suggestion. I'll add that into 0.3.2.

**Comment by seancorfield** [comment]
Can folks try `seancorfield/boot-new` 0.3.2 which has this in?

**Comment by pesterhazy** [comment]
@seancorfield works for me! great solution!

**Comment by micha** [comment]
Can I close this issue?

**Comment by pesterhazy** [comment]
Yes, thanks :smiley_cat:
