### ISSUE TITLE
download progress indicator

### ISSUE THREAD

**Issue by mobileink** [boot-clj/boot#408]
Minor enhancement request:  implement a progress indicator of some kind (e.g. hashmarks) for dependency downloads.  appengine-java-sdk is 165 MB; waiting with no feedback makes me nervous.

**Comment by micha** [comment]
PR welcome!

**Comment by micha** [comment]
This is pretty difficult to do correctly, given the limitations of the console and the fact that Aether is resolving dependencies asynchronously and in parallel.
