### ISSUE TITLE
maintain directory structure of resources in (uber)jar

### ISSUE THREAD

**Issue by thomas-shares** [boot-clj/boot#409]
Hi,

I have a Compojure project that also includes some CLJS. The CLJS files are compiled to JS files and are in the resources/ dir of the project. The resources/ dir also includes some CSS and a few .png files.

When I generate my (uber)jar file with

```
(deftask uberjar
  "Build uberjar"
  []
  (comp
    (cljs :source-map true)
    (aot)
    (pom)
    (uber)
    (jar)))
```
my web browser get some 404's for the JS and CSS files. Looking in the (uber)jar file it seems that the files that are in the resources/ dir are included in the .jar file, but all the files are in the top level dir of the jar file. The resources/ dir structure doesn't seem to be maintained.

I think it would be advantageous if there was an option to maintain the dir structure when the files are included in the jar.

Thomas

**Comment by micha** [comment]
@thomas-shares I think it's working as it's supposed to. The directories you add to `:source-paths` and `:resource-paths` form the classpath. The directories in those sets are overlayed, with file paths computed relative to the base directory specified in the set.

Consider this directory structure:

```
.
├── resources
│   └── foo
│       └── bar
│           └── hi.txt
└── src
    └── baz
        └── baf
            └── main.clj
```

With these settings:

```clojure
(set-env! :source-paths #{"src"} :resource-paths #{"resources"})
```

This will result in a classpath (and jar) with this structure:

```
.
├── baz
│   └── baf
│       └── main.clj
└── foo
    └── bar
        └── hi.txt
```

Is this not what you need?

**Comment by thomas-shares** [comment]
Hi Micha,
Just spotted the difference... I expect the the resulting structure to be:

```
.
├── resources
│   └── foo
│       └── bar
│           └── hi.txt
└── src
    └── baz
        └── baf
            └── main.clj
```
Note the included resources/ and src/ dir. As in my Compojure I have this as a route for my resources:
```
(defroutes app-routes
  (GET "/" [] (page-frame))
  (route/resources "/")
  (route/not-found "Not Found"))

```
My understanding is that the resources are taken from the resources dir. This does work Tenzing template which fires up a jetty server (with compojure is my understanding)

Does this clarify what I mean? 

TIA,
Thomas

**Comment by micha** [comment]
Could you not just create directories named `resources` and `src` or whatever you need, inside the directories you add to `:source-paths` etc?

**Comment by thomas-shares** [comment]
I have worked around this issue for the moment and therefore willing to close it and I would like to point out that this is not the behaviour that I expected. Willing to discuss.

Thank you,
Thomas

**Comment by micha** [comment]
Feel free to reopen this issue, or if you'd like to add a note to the wiki, or anything else please do :)
