### ISSUE TITLE
exception handling for bad env vals, BOOT_EMIT_TARGET

### ISSUE THREAD

**Issue by mobileink** [boot-clj/boot#410]
In my build.boot I had :target-path #{"build"} instead of :target-path "build".  With BOOT_EMIT_TARGET=no this went undetected. With BOOT_EMIT_TARGET=yes (or unspecified), I get an exception on every boot command:

IllegalArgumentException: No implementation of method: :as-file of protocol: #'clojure.java.io/Coercions found for class: clojure.lang.PersistentHashSet

So there are two problems.  One is that the bad value is either undetected or silently ignored with BOOT_EMIT_TARGET=no.  The other is that the error message is unhelpful, especially to newcomers; it really should indicate where the problem is.  I had to trial-and-error troubleshoot to find it.

**Comment by jethrokuan** [comment]
Wrt to the second problem: IMO IllegalArgumentException is quite informative. One nifty trick is to do `boot -vb | cat -n` and match the error line you see. This should help you narrow your search. It's unfortunate these tricks aren't documented anywhere.

**Comment by mobileink** [comment]
Nice, I'll document boot -vb | cat -n one the wiki somewhere, Troubleshooting I expect.  But in this case it doesn't help, I'm afraid.  The exception message makes no reference to any of my source files.  It tells me something tried to use :as-file on a set, but if I've got a bunch of sets that's not much help.  BTW, I note that in the recent State of Clojure survey bad error messages is the number one complain about Clojure by a large margin.

**Comment by jethrokuan** [comment]
Tried to repro this case and I see what you mean. I thought the `:data` would point to the correct line, thus making the IllegalArgumentException quite informative.

**Comment by mobileink** [comment]
On Wed, Feb 10, 2016 at 11:02 AM, Jethro Kuan Sheng Yuan <
notifications@github.com> wrote:

> Wrt to the second problem: IMO IllegalArgumentException is quite
> informative. One nifty trick is to do boot -vb | cat -n and match the
> error line you see. This should help you narrow your search. It's
> unfortunate these tricks aren't documented anywhere.
>
FYI I added a (minor) note about boot -vb to the wiki
<https://github.com/boot-clj/boot/wiki/Boot-Troubleshooting> - feel free to
enhance.

**Comment by martinklepsch** [comment]
`:target-path` has been removed and the assertions for other global env keys are pretty informative. Closing this.
