### ISSUE TITLE
Task option desc formatting too opinionated

### ISSUE THREAD

**Issue by mobileink** [boot-clj/boot#411]
Currently task option doc string formatting is very inflexible.  format-doc in cli.clj uses just `(format "Set %s to %s." (depunc (decap doc)) optarg)`.  To support more helpful docstrings, I suggest using Stencil or some similar templating mechanism.

**Comment by micha** [comment]
Can you sketch out how you'd like it to work please?

**Comment by micha** [comment]
I believe this was merged in #415, feel free to reopen if not :)
