### ISSUE TITLE
target target hardcoded as "target"

### ISSUE THREAD

**Issue by mobileink** [boot-clj/boot#412]
Currently the target task defaults to "target" for the output.  It should use the value of the :target-path key instead, no?

**Comment by micha** [comment]
@mobileink We want to eliminate that key in 3.0.0.

**Comment by micha** [comment]
If we have an explicit linkage between `target` task and `:target-path` then we can't really remove that deprecated key without breaking builds, so I think it's probably best to keep the two things completely separate.

Of course, please reopen this issue if that's not what we want :)
