### ISSUE TITLE
Better describe when to use which fileset roles in documentation

### ISSUE THREAD

**Issue by mobileink** [boot-clj/boot#418]
Suggest some additional explanation of how roles actually function during boot processes.  Specifically, the concept that each item in a fileset is persistently marked with its roles, so items effectively carry their roles with them as they move through the pipeline.  The `target` task will write anything marked with the Output role, even if it has been moved e.g. by `sift`.  Also, stuff in `:source-paths` will not be marked Output, so target will not write it - if you want to move stuff from your source paths for output, you have to put it in `:resource-paths` so it will be marked as both Input and Output.

**Comment by mobileink** [comment]
some notes from micha on slack that might be useful for composing documentation:

packaging is construction of artifacts that will be used in other environments
basically packaging represents building a classpath for another JVM process
so that might be building a jar or war file
or it may be building a "classpath" for a cljs single page app that is deployed to s3
my cljs applications have a "classpath" oriented architecture, too
basically that's how i approach all applications now
jars in maven provide one thing only: a classpath snapshot
while you're building the jar and stuff you have a merging of the classpath that will be part of thejar and the classpath your build program needs to run
that's why the fileset roles are there
input files are part of the classpath the build program uses
output files are part of the classpath you want to create in your final artifacts
of course files in the fileset can be both at the same time
but i think of my build programs as a transformation of classpaths

**Comment by arichiardi** [comment]
Definitely worth adding

**Comment by martinklepsch** [comment]
There's [documentation for Fileset roles in the wiki](https://github.com/boot-clj/boot/wiki/Filesets#fileset-components). I think it existed when this issue was opened but not sure.

Can anyone point out what specifically they'd like to see added to the information already in the wiki?

**Comment by flyboarder** [comment]
I would say some use cases could be documented. For example, "when building a cljs library you want to use :resource-paths so files can be consumed in other projects when packaged."

**Comment by flyboarder** [comment]
Added an example to the wiki, feel free to add more as needed.
