### ISSUE TITLE
make pipeline accept nils

### ISSUE THREAD

**Issue by mobileink** [boot-clj/boot#420]
This doesn't work:  `(comp (A) (if foo (B)) (C))` but this does `(comp (A) (if foo (B) identity) (C))`.  It might be more user friendly to make the former acceptable.

**Comment by mobileink** [comment]
scratch that, it's the way `clojure.core/comp` behaves.  so the suggestion is to add something about this to the documentation.

**Comment by flyboarder** [comment]
I added a note to the README under or composition example.
