### ISSUE TITLE
Define how fileset is constructed instead of specifying *-paths

### ISSUE THREAD

**Issue by mobileink** [boot-clj/boot#421]
The names and semantics `:source-paths`, `:resource-paths` and `:asset-paths` sometimes lead to confusion.  Ditto for the INPUT role; everything in those paths are "inputs" to boot, so why aren't they all +INPUT?

The suggestion here is to deprecate the :*-paths keys in favor of a new key `:fileset`, a macro `with-features` and two metadata keys, `:input` and `:output`.  So instead of writing

```
(set-env!
 :asset-paths #{"resources/assets"}
 :source-paths #{"src"}
 :resource-paths #{"resources/public"})
```

we would write

```
(set-env!
 :fileset (concat
           (with-features #{"resources/assets"} {:input false :output true})
           (with-features #{"resources/public"} {:input true :output true})
           (with-features #{"src"} {:input true :output false})))
```

This has the virtue of making the following explicit:
- we're constructing a fileset
- there's only one "root" to the fileset - everything in the listed paths gets put into it
- the fileset "roles" to attach to each item
- +INPUT is a role attached to only some files, even though they're all "input" to the boot process

**Comment by mobileink** [comment]
PS.  `with-features` instead of `with-roles` because it's more general, you could allow any metadata.

**Comment by martinklepsch** [comment]
I do like the general idea of this but the information of source-path etc is also relevant to the `watch` task and maybe other tasks. So switching to the outlined approach would likely result in a lot of breakage. Still I think it could be worth exploring so if anyone feels like working on this, go for it :+1:

**Comment by flyboarder** [comment]
Im going to close this for now, as it's not something we are currently looking at implementing. Also the intention of the `*-paths` is to make this implicit.
