### ISSUE TITLE
[help-wanted] verbose option for pods

### ISSUE THREAD

**Issue by mobileink** [boot-clj/boot#424]
The idea is to provide some means of inspecting/logging pod config/state.  For example, a -verbose option on `make-pod` might set a flag so that when `with-call-in` etc. are run they log their classpath at startup.  That's just a possibility, there may be better ways.

This could be very useful for troubleshooting since pods are first class, can be constructed dynamically, passed around, etc. - if you run into trouble it might take some work to figure out what's "in" a pod.

Would also be useful for learners exploring how pods work.

See the slack discussion with @alandipert  starting at https://clojurians.slack.com/archives/boot/p1456932856003401

**Comment by micha** [comment]
@mobileink The `show` task accepts the `-P, --pods` option that lets you specify which pod it should show info from (matches regexes against the pod names). Is this what you are looking for?

**Comment by mobileink** [comment]
Not sure what exactly I had in mind. ;)  If it comes up again I'll reopen.
