### ISSUE TITLE
Target task in build.boot

### ISSUE THREAD

**Issue by nashbridges** [boot-clj/boot#425]
Given the following task:

```clojure
(deftask spec
  "Compile clojurescript files for tests"
  []
  (comp
   (watch)
   (speak)
   (cljs :optimizations :whitespace)))
```

When I execute `boot spec target -d app/assets/javascripts/cljs`, then everything works correctly.

How should I specify target task in build.boot itself?

```clojure
(deftask spec
  "Compile clojurescript files for tests"
  []
  (comp
   (watch)
   (speak)
   (cljs :optimizations :whitespace)
   (target "app/assets/javascripts/cljs")))
```

Executes, but writes nothing.

```clojure
(deftask spec
  "Compile clojurescript files for tests"
  []
  (comp
   (watch)
   (speak)
   (cljs :optimizations :whitespace)
   (target #{"app/assets/javascripts/cljs"})))
```

Exits with "clojure.lang.ExceptionInfo: java.lang.ClassCastException: clojure.lang.PersistentHashSet cannot be cast to java.lang.CharSequence"

```clojure
(deftask spec
  "Compile clojurescript files for tests"
  []
  (comp
   (watch)
   (speak)
   (cljs :optimizations :whitespace)
   (target :dirs #{"app/assets/javascripts/cljs"})))
```

Warns with "target: unknown option(s): :dirs"

**Comment by mitchelkuijpers** [comment]
It should be `(target :dir #{"app/assets/javascripts/cljs"})`

**Comment by mitchelkuijpers** [comment]
be sure to use the help function because this is documented

`boot target -h`

```
Writes output files to the given directory on the filesystem.

Options:
  -h, --help      Print this help info.
  -d, --dir PATH  Conj PATH onto the set of directories to write to (target).
  -L, --no-link   Don't create hard links.
  -C, --no-clean  Don't clean target before writing project files.
```

**Comment by nashbridges** [comment]
My bad. I'm pretty sure that I've looked into `boot target -h` a couple of times, but in my mind Set type strongly associated with plural form.

@mitchelkuijpers, thank you!

**Comment by mitchelkuijpers** [comment]
No problem @nashbridges Happy to help!
