### ISSUE TITLE
Decrypt deploy creds only when needed

### ISSUE THREAD

**Issue by malcolmsparks** [boot-clj/boot#432]
The `configure-repositories!` solution described [here](https://github.com/boot-clj/boot/wiki/Repository-Credentials-and-Deploying#encrypted-credentials-file) involves the decryption of credentials every time boot is run, even for operations that don't require them. 

This is a problem for those of us using yubikeys or other hardware tokens who have to keep them plugged in even while doing offline development.

It was be better if the design of this was improved such that it was lazier.

FWIW here's my profile.boot

``` clojure
;; Get credentials from a GPG encrypted file.
(defn decrypt-creds [url]
  (let [creds-file (java.io.File. (boot.App/bootdir) "credentials.gpg")
        creds-data (boot.core/gpg-decrypt creds-file :as :edn)]
    (some #(when (re-seq (first %) url) (second %)) creds-data)))

(defn repo-map [repo]
  (case repo
    "clojars" (let [url "https://clojars.org/repo/"]
                (merge {:url url}
                       (decrypt-creds url)))
    (throw (ex-info "Unknown repo" {:repo repo}))))


```

This way I can deploy like this in my build.boot

``````
(deftask deploy []
   (push :repo-map (repo-map "clojars")))```
``````

**Comment by arichiardi** [comment]
:+1:

**Comment by micha** [comment]
Perhaps decrypt only after getting `Forbidden` error when fetching/pushing from/to repo?

**Comment by martinklepsch** [comment]
I'll close this issue as it's basically covered by #450 as far as I can see. Please reopen if you feel like it should stay open.
