### ISSUE TITLE
Support transforms?

### ISSUE THREAD

**Issue by aft-luke** [boot-clj/boot#448]
I haven't been able to find any resources on how I might transform some foreign-libs using boot. Is this possible?

My particular use case is I have a handful of javascript modules from another app, but they are using `jsx` syntax. What I would like to do is something [like this](http://mneise.github.io/posts/2015-08-04-week-9-and-10.html) where we can provide `:preprocess :jsx` to the `:compiler-options :foreign-libs`. I can't seem to get access to the `:provides` namespaces, however, from within my actual code

```
// build.boot
(set-env!
 :source-paths #{"src/cljs" "src/js"}
 :compiler-options {:foreign-libs [{:file "testabc/index.jsx"
                                    :provides ["testabc"]
                                    :preprocess :jsx
                                    :module-type :commonjs})
```

Requiring below will throw `ERROR: No such namespace: testabc, could not locate testabc.cljs, testabc.cljc, or Closure namespace "testabc"`

```
// my code
(ns main.core
  (:require [testabc :as abc]))
```

I don't fully understand `boot` and in what environment it runs, but any help would be appreciated.

**Comment by micha** [comment]
I think you need to add the `:compiler-options` to the `cljs` task arguments, not the boot JVM environment. The `set-env!` function is for configuring boot's classpath.

You want something more like this:

```
// build.boot
(set-env!
  :source-paths #{"src/cljs" "src/js"}
  :dependencies '[[org.clojure/clojurescript "..."]
                  [adzerk/boot-cljs "..."]])
                  
(require '[adzerk.boot-cljs :refer [cljs]])

(deftask build
  []
  (cljs :compiler-options ...))
```

See [the boot-cljs README](https://github.com/adzerk-oss/boot-cljs) for more
info and docs.

**Comment by aft-luke** [comment]
Thanks @micha . I'll take a look at this in a few days and report back.

**Comment by micha** [comment]
Please feel free to reopen if the issue persists.
