### ISSUE TITLE
dosh capabilities, limitations?

### ISSUE THREAD

**Issue by aft-luke** [boot-clj/boot#454]
I've spent all day trying to figure out how to write this boot task, but I'm running out of ideas.

I want to execute a shell command that compiles `.styl` files into `.css`. Stylus exposes an executable, so I figured I might be able to use `dosh`. My attempts have been many, but I'm just not so convinced this is the right approach. Here's an example:

```
(defn compile-styl! [in out]
    (doto out io/make-parents)
    (u/dosh "../fb/node_modules/.bin/stylus" "-p" "--include-css" (.getPath in) (str " > " (.getPath out))))

(deftask compile-styl
    "Compile all .styl files into css-modules with their corresponding .json."
    []
    (let [tmp (c/tmp-dir!)]
        (c/with-pre-wrap fileset
            (c/empty-dir! tmp)
            (let [in-files (c/input-files fileset)
                  styl-files (c/by-ext [".styl"] in-files)]
                (doseq [in styl-files]
                    (let [in-file (c/tmp-file in)
                          in-path (c/tmp-path in)
                          out-path (.replaceAll in-path "\\.styl$" ".css")
                          out-file (io/file tmp out-path)]
                        (compile-styl! in-file out-file)))
                (-> fileset
                    (c/add-resource tmp)
                    c/commit!)
            )
        )))
```

This fails with `Error: ENOENT: no such file or directory, stat ' > /Path/to/cache/tmp/file'`. In fact, any combination that tries to use redirects `< >` fails. 

If I try something like the following in an attempt to write the file:

```
(defn compile-styl! [in out]
    (doto out 
        io/make-parents
        (u/dosh "../fb/node_modules/.bin/stylus" "--include-css" (.getPath in))))

```

I get the expected `*.css` files inside of `/target`, but they're all empty (as expected, I'm essentially spitting nothing into them, but I don't know how to get the output from the sh).

If I try the same `spit` without the `-p` (print to stdout instead of to a file), I get a `Error: EACCES: permission denied, open '/Path/to/cache/tmp/file`. 

I'm just out of ideas and really lost. Do I need to go outside of boot and use some java interop to execute a shell command, wait for the future, then tell boot it's done? Is there a totally different approach to make this work?

**Comment by martinklepsch** [comment]
I think the issue might me how you're prepending the `>` to the out-file.

Not sure how the shell stuff works exactly but I think what's happening is that the shell sees an argument like `" > out-file"` (note the quotes) which it interprets as single string instead of two separate arguments.

With that in mind I would suggest to try something like this:

```clojure 
(u/dosh "../fb/node_modules/.bin/stylus" "-p" "--include-css" (.getPath in) ">" (.getPath out)))
```

**Comment by aft-luke** [comment]
I feel like I tried that variation, but after running it again here's what I get:

```
Error: ENOENT: no such file or directory, stat '<'
    at Error (native)
```

And that happens with every variation of redirecting `"<" or ">" or "<" (.getPath in) ">" (.getPath out)`, with or without the `-p` flag. The error message would seem to imply that it takes some sort of positional argument... but perhaps you just cannot use redirects in this context?

**Comment by martinklepsch** [comment]
Ah, I thought this was some stylus CLI syntax thing but you're totally
right, it's just a shell redirect.

Maybe in this case the easiest solution would be to capture stdout (look at
the return value of dish, I think it should be there somewhere) and `spit`
that to a file afterwards.

**Comment by martinklepsch** [comment]
After looking at the dosh code, what you want is probably wrapping the call
in `with-out-str`.

**Comment by aft-luke** [comment]
I couldn't get `dosh` or `sh` to work with or `with-out-str`. I dropped down to `conch` and was able to get a side-effected operation to work:

```
(defn compile-styl!
    "Run the stylus compile task, but since it is async, wait for it to
    complete by coercing the stream output into a string. There wont be a
    result but, by invoking the process, stylus generates the file as a side
    effect."
    [in out]
    (co/stream-to-string (co/proc "node_modules/.bin/stylus" "--include-css" "-p" (.getPath in)) :out)
    (println (str "Writing " (.getName out) "..."))
)

```
