### ISSUE TITLE
Add explicit :dependency option for uber

### ISSUE THREAD

**Issue by arichiardi** [boot-clj/boot#455]
I have been fighting with isolation for a while now and specifically about having exactly the deps I want to in my uberjar

At the moment the `uber` task queries `get-env` for  `:dependencies` but most of the times you can find boot deps in there that you don't want to add to the uberjar.

One solution would be to execute the uber task in a pod, but I cannot make it work. I could isolate the things that are going on in the task and create a function instead that can be called from a pod.

I came to the conclusion that either I am missing something, which is always possible, or allow the user to specify a `:dependencies` vector in `uber` makes sense.

**Comment by Deraen** [comment]
Uber task uses Maven scopes to filter dependencies. By default dependencies with `test` scope should not be included in uberjar.

https://github.com/Deraen/saapas/blob/master/build.boot#L9-L22

**Comment by arichiardi** [comment]
You are right @Deraen, and indeed I have some problem with transitive dependencies. I am investigating, closing this and sorry for the noise
