### ISSUE TITLE
dev task: need to use port other than 3000 ; how to configure that?

### ISSUE THREAD

**Issue by gamecubate** [boot-clj/boot#456]
Where can one specify the port — 3000 by default — used by the jetty server for the dev task?

**Comment by martinklepsch** [comment]
There is no dev task itself. Probably best to look at your build.boot and find the task starting a server. One popular option is boot-https `serve` task. If you find a `serve` task used inside your `dev` task you can look up the available options using `boot serve --help`.

Hope this helps. Please close the issue if it does.

**Comment by gamecubate** [comment]
Hoping to get a head start on my project without understanding core boot ideas, I used the tenzing lein template. My bad. Will close issue (and search for simple examples of build.boot with dev and prod tasks).

**Comment by martinklepsch** [comment]
@gamecubate if you use tenzing then look for something like `(serve)` and change it to `(serve :port 5555)`. See https://github.com/pandeiro/boot-http for details.

**Comment by gamecubate** [comment]
@martinklepsch Thanks.
