### ISSUE TITLE
Add command line switch for executing arbitrary forms

### ISSUE THREAD

**Issue by arichiardi** [boot-clj/boot#465]
I was working on a cider issue: https://github.com/clojure-emacs/cider/pull/1751

But then got stuck as there is no way to require from the command line. I think I saw someone asking kind of a similar thing on Slack, so maybe we can add some flag that enables to execute a form in `boot.user` before or even without having to rely on `build.boot`?

Would you guys be open to a patch?

**Comment by micha** [comment]
@arichiardi Sure, that sounds great to me!

**Comment by oahner** [comment]
On the topic of adding a flag to execute arbitrary forms, it would be useful to have a similar flag that executes the content of a file rather than just the string, effectively bypassing the shebang issue on Windows.
