### ISSUE TITLE
Exclude clojure in all default dependencies

### ISSUE THREAD

**Issue by lsnape** [boot-clj/boot#469]
The clojure version included by one of my default dependencies was loaded before the clojure version defined in the project by `BOOT_CLOJURE_VERSION`, without any warning or trace.

The workaround is to exclude clojure from all the default dependencies, but ideally clojure should be excluded by boot automatically.

**Comment by micha** [comment]
See #230, it's related.

**Comment by micha** [comment]
I think the correct solution is to add an explicit `org.clojure/clojure` dependency to your `:dependencies` in the _build.boot_ file. I think there should be a warning, though. What do you think?
