### ISSUE TITLE
(repl :server false) and watch tasks conflict

### ISSUE THREAD

**Issue by pesterhazy** [boot-clj/boot#473]
Running a mixed clj/cljs build.boot, I'm among those who like the terminal-based repl (i.e. not using cider to connect). `boot repl` works fine for this purpose. But if I add a `watch` based pipeline to the mix, the `repl` task doesn't attach to the terminal anymore.

If I run

```
boot repl watch cljs-build
```

the terminal prompt never appears (although the nREPL server is started). The other way round (`boot watch repl`) is worse: it breaks killing the process using `^C`.

The obvious workaround is to run `boot repl -c` in a separate terminal window. But is there another solution? Ideally I'd like to run everything in a single `boot` process and a single terminal window.

**Comment by Deraen** [comment]
This might work:

```clj
$ boot
boot.user=> (def x (future (boot (comp (watch) (cljs-build))))
```

**Comment by pesterhazy** [comment]
@Deraen that does work, yes. I guess I this could be combined with `:eval` to automatically start the compilation on repl startup. Is this an instance of "boot in boot"?

Anyway, I think it's a bit too clunky for me for now, so I'll go with running `boot repl -c` in another terminal.

What would be great would be a much faster (<200 ms startup) nREPL client for this purpose to replace `boot repl -c`, maybe based on planck?

**Comment by Deraen** [comment]
I don't think this is boot-in-boot. There is just one Boot running several tasks in the same env.

**Comment by micha** [comment]
@pesterhazy I've used https://github.com/gfredericks/repl-utils to help make things like this less clunky in the REPL.

**Comment by pesterhazy** [comment]
@micha, @Deraen, thanks for the tips! I'll close this issue as I think it's sufficiently clear now.
