### ISSUE TITLE
Remove vestigial -t, -T boot cli options and :target-path environment entry

### ISSUE THREAD

**Issue by esp1** [boot-clj/boot#475]
The boot cli still shows -t and -T options to set (or unset) the target path, even though those options no longer have any effect. Similarly, there is a :target-path entry in the boot environment which no longer affects the target task. These should be removed as their continued presence is misleading.

**Comment by esp1** [comment]
Hmm. removing :target-path could be tricky. There are third party tasks that make use of this, e.g.  https://github.com/adzerk-oss/boot-reload/blob/bb26bdabb6529668bfc42f6ba759cf70e13a7e8b/src/adzerk/boot_reload.clj#L62

**Comment by Deraen** [comment]
Boot-reload doesn't really need it. It is only used in a rare case which can be replaced with separate option if needed.
