### ISSUE TITLE
Symlinked directories are ignored when building the fileset

### ISSUE THREAD

**Issue by svdm** [boot-clj/boot#481]
Boot ignores symlinked directories when walking the filesystem tree to build the fileset.

A minimal case:
```shellsession
$ mkdir src
$ mkdir linked-src && touch linked-src/foo.clj
$ ln -s ../linked-src src/my-link
$ touch src/bar.clj
$ boot -s src show -f

└── bar.clj
```
Note that the contents of `src` are added to the fileset, but the `src/my-link` symlink is ignored.

The underlying cause is that the filesystem walkers in `boot.tmpdir/dir->tree!` and `boot.filesystem/mktree` call `Files/walkFileTree` without specifying the `FOLLOW_SYMLINKS` option ([javadoc](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#walkFileTree-java.nio.file.Path-java.util.Set-int-java.nio.file.FileVisitor-)). As a quick workaround I've done some ugly runtime patching using `alter-var-root` to replace those two functions with symlink-following versions, and it all appears stable.

Is there a reason not to follow symlinks when adding files to the fileset? If not, I'd be happy to make a PR to add the relevant options.

**Comment by micha** [comment]
Currently bood doesn't follow symlinks because of #180

**Comment by svdm** [comment]
I completely get the need to be very careful with links when deleting. It seems to me this is not directly related though: with the proposed change, there are still no symlinks inside the tempdirs, so the various deletion/cleanup functions don't need to follow symlinks and can stay as-is.

The only thing that changes is that symlinks are followed when creating the fileset, which makes symlinked directories "just work". For the example above the fileset becomes:
```
├── bar.clj
└── my-link
    └── foo.clj
```
Where `my-link` is a plain directory in the tempdir, even though it was a symlink in the real filesystem tree. The same behavior actually already exists for symlinks to individual files (they become plain files containing the symlinked content).

**Comment by micha** [comment]
Ah, yes, that sounds totally reasonable to me, PR would be greatly appreciated! Thanks! :)
