### ISSUE TITLE
`boot show -c` should not list boot's own dependencies

### ISSUE THREAD

**Issue by borkdude** [boot-clj/boot#485]
I wanted to get a classpath for a ClojureScript library, so I could use it with Planck. 

I could get the classpath using the `boot-cp` task:

    boot --dependencies org.clojars.micha/boot-cp  --dependencies com.andrewmcveigh/cljs-time:"0.4.0"  with-cp -w --file .classpath 

`boot show -c > .classpath` should have the same result, not including boot's own dependencies.

See also https://clojurians.slack.com/archives/clojurescript/p1469712478001202.

**Comment by micha** [comment]
Starting with version 2.7.0 you will be able to do `boot cp -w -f - > .classpath`. (The `cp` task is the same as the `with-cp` task, added to boot itself.)

**Comment by arichiardi** [comment]
:+1: i thought about the above as well, it is a very good addition.
