### ISSUE TITLE
OSX notify throws IllegalArgumentException

### ISSUE THREAD

**Issue by esp1** [boot-clj/boot#491]
There is one more issue with the notify task on OSX. It attempts to pull a value for a `:pid` key from the input argument map, but that value is never set, resulting in the following exception when the task is run:

java.lang.IllegalArgumentException: No value supplied for key: null

Perhaps this should be `:uid` instead?

**Comment by micha** [comment]
How can this be reproduced?

**Comment by esp1** [comment]
Just run `boot notify` on OSX, it will throw the exception

**Comment by esp1** [comment]
The root of the issue is that the boot `notify` task provides sensible default values for `:title`,`:uid`, `:icon`, and `:messages` in the options map it sends to the `notify-method` multimethod, but the OSX defmethod expects to find a `:pid` key, which is never populated. The `shell/sh` command then dies with the above exception because pid is nil. It seems like a simple typo and that `:pid` should be `:uid`, which is defaulted appropriately in the `notify` task.
