### ISSUE TITLE
Unicode is problematic for windows --boot show -p

### ISSUE THREAD

**Issue by laforge49** [boot-clj/boot#493]
Windows 10 still has unicode issues when running an application, even with powershell ise.

boot show -p uses unicode to tag conflict resolution.

Perhaps dropping the unicode or turning it off when not using color would be a good idea.

**Comment by flyboarder** [comment]
Have you tried this recently? Powershell resolved this I believe.

**Comment by arichiardi** [comment]
Is this still happening? I do not have a W10 machine to try @laforge49 :smile:

**Comment by martinklepsch** [comment]
I'll close this since there hasn't been any recent activity around this issue.
