### ISSUE TITLE
Installation through homebrew complains for JAVA, which is already present

### ISSUE THREAD

**Issue by jshulk** [boot-clj/boot#505]
Installation of boot through homebrew complains that Java is not present, while it is already present and available on $PATH

Error : boot-clj: Java is required to install this formula.JavaRequirement unsatisfied!

OS - Mac OS X Yosemite
Java - 8

**Comment by flyboarder** [comment]
It is looking for the Java homebrew package, not just any Java. You would need to install the homebrew Java formula first.
