### ISSUE TITLE
2.6.0 problems with symlinks in :resource-paths; 2.5.5 works fine

### ISSUE THREAD

**Issue by limist** [boot-clj/boot#512]
In one of my libraries, I have a `resources` dir that has some subdirs that are relative symlinked directories to another library's `resources` subdirs, on the same filesystem, e.g. `lib-A/resources/public/something` symlinks to the folder `../../../../lib-B/resources/public/something`  

When running tests that need files in the `resources` directory, everything works fine with Boot 2.5.5.  But making just one change, to use Boot 2.6.0, and then the tests fail.  

By starting up a REPL in the library directory using Boot 2.6.0, it looks like the process has no visibility to the symlinked dir, e.g. 

``` clojure
(->> "public/something"
      io/resource)
```

...returns `nil` when `something` is a symlink as described above.  Switch to Boot 2.5.5, and everything works again.

**Comment by micha** [comment]
I believe this was fixed in #483, if you could verify with boot master that would be great :)

**Comment by martinklepsch** [comment]
Instructions for building Boot from master are on the README and should work smoothly: https://github.com/boot-clj/boot#hacking-boot

You do not need to update the binary, just update `BOOT_VERSION` in your `boot.properties` file and it will load the version you built from your local Maven repo.

**Comment by martinklepsch** [comment]
Closing this as there hasn't been any feedback from OP.
