### ISSUE TITLE
Boot-clj is in the Chocolatey repository now

### ISSUE THREAD

**Issue by zilti** [boot-clj/boot#517]
Hi! Just a heads-up, I packaged the boot.exe for the Chocolatey package manager: https://chocolatey.org/packages/boot-clj

**Comment by micha** [comment]
Awesome, thanks! Should we add a note to the README or anything?

**Comment by zilti** [comment]
If you want, feel free to do so :) The installation would be `choco install boot-clj`.

**Comment by micha** [comment]
Thanks! I'll add a note to the README about it.
