### ISSUE TITLE
export BOOT_JVM_OPTIONS='-Dscala.usejavacp true' causes boot to not start

### ISSUE THREAD

**Issue by tmtwd** [boot-clj/boot#518]
To replicate:

`# mkdir boot-test`
`# cd boot-test`
`# export BOOT_JVM_OPTIONS='-Dscala.usejavacp true'`
`# boot repl`

which prints out: 

Error: Could not find or load main class true

**Comment by schmir** [comment]
It looks like you're missing a '=' in BOOT_JVM_OPTIONS. 
with 
```
export BOOT_JVM_OPTIONS='-Dscala.usejavacp=true' 
```
the boot repl starts without problems.

I'm closing that one, feel free to reopen if you still think there's an issue.

**Comment by tmtwd** [comment]
thanks
