### ISSUE TITLE
Add Brew Support!

### ISSUE THREAD

**Issue by aadrian** [boot-clj/boot#52]
Please add brew support for OS X

thanks in advance

**Comment by pasviegas** [comment]
+1

**Comment by martinklepsch** [comment]
I'll check with some brew maintainers how we can get boot into homebrew.

Options are 

1) put it into homebrew-binary 
1) make a brew formula that builds boot

Probably the first one is best. 
Will update this issue.

**Comment by martinklepsch** [comment]
https://github.com/Homebrew/homebrew/pull/35540

**Comment by pasviegas** [comment]
Cool, so after the next stable release?

thanks!

**Comment by martinklepsch** [comment]
Don't know yet, hope I can convince him to put RC4 into brew as the shell script is mostly stable anyways.

**Comment by martinklepsch** [comment]
> You need to convince upstream to release a non-RC version. Sorry but it is a blocker for now.

It seems before there is 2.0.0 final we won't get it into Homebrew. :disappointed:

**Comment by martinklepsch** [comment]
FWIW it can already be installed like that: 
```
$ brew install https://raw.githubusercontent.com/martinklepsch/homebrew/boot-formula/Library/Formula/boot-clj.rb
```

Although I don't know if that will cause any trouble later on when it gets into homebrew.

**Comment by alandipert** [comment]
@martinklepsch we just released 2.0.0 :fireworks: , would you care to move this forward?

**Comment by martinklepsch** [comment]
Sure!

**Comment by aadrian** [comment]
```brew install boot-clj``` seems to work ! 
It installs Boot 2.0.0, and so far seems to work great :).

Thank you very much.

**Comment by martinklepsch** [comment]
Oh. I forgot to update here. :) 

https://github.com/Homebrew/homebrew/pull/35540 has been merged so Boot can now be installed via Hombrew :)

**Comment by aadrian** [comment]
> Oh. I forgot to update here. :) 

Please  update the getting-started section too:
https://github.com/boot-clj/boot#install

**Comment by alandipert** [comment]
@aadrian added to the README :rocket:

**Comment by pasviegas** [comment]
Finally!!! :+1:
