### ISSUE TITLE
Linux: user limit of inotify watches reached

### ISSUE THREAD

**Issue by pesterhazy** [boot-clj/boot#530]
When building my project using CircleCI (Linux), builds fail about 20% of the time with the message

```
+ boot deps
Downloading https://github.com/boot-clj/boot/releases/download/2.5.5/boot.jar...
clojure.lang.ExceptionInfo: User limit of inotify watches reached
    data: {:file "/tmp/boot.user4446813814261296413.clj", :line 5}
       java.io.IOException: User limit of inotify watches reached
sun.nio.fs.LinuxWatchService$Poller.implRegister  LinuxWatchService.java: 264
       sun.nio.fs.AbstractPoller.processRequests     AbstractPoller.java: 260
         sun.nio.fs.LinuxWatchService$Poller.run  LinuxWatchService.java: 329
```

The reason is that boot creates fs watches for the source directories, and CircleCI limits this resource. However, for CI builds watching for changes is not necessary.

One way around this would be to add an option to boot that prevents it from creating the inotify watches, or some way to reduce the number of concurrent watches.

**Comment by gtrak** [comment]
I was pointed here by @alandipert on slack, might be a start :-) https://readmes.numm.org/init/upstart/init/tests/wrap_inotify.c

**Comment by alandipert** [comment]
I made this, but I haven't tested it on CircleCI: https://github.com/alandipert/stubwatch

**Comment by alandipert** [comment]
Mitigated by #564

**Comment by danielcompton** [comment]
I've added docs for this to https://github.com/boot-clj/boot/wiki/Running-Boot-on-CI-systems#circleci.

**Comment by Deraen** [comment]
Also, with CircleCI v2 using Docker containers, there is no such tight limits on inotify watches: https://github.com/cljsjs/packages/blob/master/circle.yml#L6

**Comment by Deraen** [comment]
@danielcompton I added docs for using CircleCI v2: https://github.com/boot-clj/boot/wiki/Running-Boot-on-CI-systems#circleci-v2

**Comment by vikeri** [comment]
@Deraen I still got the Inotify watches error on 2.0 with the boot docker image. So I will add that to the wiki for 2.0 as well

**Comment by vikeri** [comment]
Actually I'm getting the issue sometimes irregardless of if I set `BOOT_WATCHERS_DISABLE: yes`

**Comment by danielcompton** [comment]
@vikeri this isn't in a stable release of boot yet, only in 2.7.2-SNAPSHOT, that might be the problem?

**Comment by vikeri** [comment]
@danielcompton That makes sense, the Docker image is for `2.7.1`.

**Comment by SevereOverfl0w** [comment]
I'm still having this issue occasionally with CircleCI v2.

**Comment by xiongtx** [comment]
> I'm still having this issue occasionally with CircleCI v2.

@SevereOverfl0w Even w/ Boot 2.7.2 and `BOOT_WATCHERS_DISABLE` set to `yes` in your `circle.yml`?

**Comment by SevereOverfl0w** [comment]
I use `boot --disable-watchers`
