### ISSUE TITLE
Name of script is `boot`

### ISSUE THREAD

**Issue by marcusadair** [boot-clj/boot#538]
It should not be named `boot`. Thanks.

**Comment by micha** [comment]
```bash
mv boot notboot
```

**Comment by marcusadair** [comment]
No need, won't install as long as that's the name put in my path.

**Comment by micha** [comment]
Nothing is put in your path other than what you put there. The installation process is just downloading a file and moving it to somewhere on your path&mdash;what you name it and where you move it to is completely up to you.

**Comment by marcusadair** [comment]
Hey, I totally expect you to close-won't-fix this. I'm just one voice, but inappropriate land-grabbing names are worth speaking up about.

**Comment by micha** [comment]
OK, sorry you feel that way but there isn't really much we can do about it now. Feel free to reopen the ticket if you want to discuss it or anything.

**Comment by marcusadair** [comment]
Also, it's actually `brew install boot-clj` or `nix-env -i boot`, so it's a bit disingenuous to say that's "just a script download" when it's a package install for most people.
