### ISSUE TITLE
Built-in REPL task doesn't close nREPL server when Boot pipeline is closed

### ISSUE THREAD

**Issue by Deraen** [boot-clj/boot#554]
To reproduce:

```
$ boot repl
=> (boot (comp (repl :server true :port 4567) (wait)))
```

In another terminal:
```
$ boot repl -c -p 4567
```

Once the pipeline is closed on the first terminal with C-c, the repl server should be stopped.

I think repl task should add a cleanup hook to close the nrepl server.

This also affect boot-cljs-repl.

Ping @vikeri

**Comment by Deraen** [comment]
It would be easy to add cleanup hook for repl task, but currently cleanup-fns are global and closing one "boot process" will call cleanup fns for all other prcesses. In repl task case this means that even the main process would be closed.

REPL cleanup hook for future use.

```patch
diff --git a/boot/core/src/boot/task/built_in.clj b/boot/core/src/boot/task/built_in.clj
index 1cc5580..5cf8711 100644
--- a/boot/core/src/boot/task/built_in.clj
+++ b/boot/core/src/boot/task/built_in.clj
@@ -474,6 +474,8 @@
         deps     (remove pod/dependency-loaded? @repl/*default-dependencies*)
         repl-svr (delay (apply core/launch-nrepl (mapcat identity srv-opts)))
         repl-cli (delay (pod/with-call-worker (boot.repl-client/client ~cli-opts)))]
+    (when (or server (not client))
+      (core/cleanup (@repl-svr)))
     (comp (core/with-pass-thru [fs]
             (when (or server (not client)) @repl-svr))
           (core/with-post-wrap [_]
```

**Comment by flyboarder** [comment]
Closing as we have a new repl task since issue was opened.
