### ISSUE TITLE
boot fails to run on Windows 10

### ISSUE THREAD

**Issue by Ifiht** [boot-clj/boot#559]
Sorry if this is my own error, but it didn't match the existing issues and seemed beyond me so thought I'd open the issue.

Running a hello-world script causes boot to fail on an error from a temp file:
`C:\Users\Mark_Antony\Developer`
`λ boot -vvv test.clj`
`clojure.lang.ExceptionInfo: test.clj {:file "C:\\Users\\MARK_A~1\\AppData\\Local\\Temp\\boot.user6360842381734121343.clj", :line 4}`
`        at clojure.core$ex_info.invoke(core.clj:4593)`
`        at boot.main$_main$fn__1788.invoke(main.clj:213)`
`        at boot.main$_main.invoke(main.clj:206)`
`        at clojure.lang.Var.invoke(Var.java:394)`
`        at org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke(ClojureRuntimeShimImpl.java:159)`
`        at org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke(ClojureRuntimeShimImpl.java:150)`
`        at boot.App.runBoot(App.java:399)`
`        at boot.App.main(App.java:491)`
`        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)`
`        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)`
`        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)`
`        at java.lang.reflect.Method.invoke(Method.java:498)`
`        at Boot.main(Boot.java:258)`
`Caused by: java.lang.ClassNotFoundException: test.clj`
`        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)`
`        at clojure.lang.DynamicClassLoader.findClass(DynamicClassLoader.java:69)`
`        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)`
`        at clojure.lang.DynamicClassLoader.loadClass(DynamicClassLoader.java:77)`
`        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)`
`        at java.lang.Class.forName0(Native Method)`
`        at java.lang.Class.forName(Class.java:348)`
`        at clojure.lang.RT.classForName(RT.java:2154)`
`        at clojure.lang.RT.classForName(RT.java:2163)`
`        at clojure.lang.Compiler.maybeResolveIn(Compiler.java:7042)`
`        at clojure.core$ns_resolve.invoke(core.clj:4216)`
`        at clojure.core$ns_resolve.invoke(core.clj:4213)`
`        at clojure.core$resolve.invoke(core.clj:4222)`
`        at boot.core$construct_tasks.doInvoke(core.clj:982)`
`        at clojure.lang.RestFn.invoke(RestFn.java:439)`
`        at boot.core$boot$fn__918.invoke(core.clj:1030)`
`        at clojure.core$binding_conveyor_fn$fn__4444.invoke(core.clj:1916)`
`        at clojure.lang.AFn.call(AFn.java:18)`
`        at java.util.concurrent.FutureTask.run(FutureTask.java:266)`
`        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)`
`        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)`
`        at java.lang.Thread.run(Thread.java:745)`

Relevant system info:
`C:\Users\Mark_Antony\Developer`
`λ lein -v`
`Leiningen 2.7.1 on Java 1.8.0_102 Java HotSpot(TM) 64-Bit Server VM`

`C:\Users\Mark_Antony\Developer`
`λ boot -V`
`#http://boot-clj.com`
`#Tue Jan 03 19:38:17 KST 2017`
`BOOT_CLOJURE_NAME=org.clojure/clojure`
`BOOT_CLOJURE_VERSION=1.7.0`
`BOOT_VERSION=2.7.1`

`C:\Users\Mark_Antony\Developer`
`λ systeminfo`

`Host Name:                 SOME-PC`
`OS Name:                   Microsoft Windows 10 Education`
`OS Version:                10.0.14393 N/A Build 14393`

The code is simply 
`#!/usr/bin/env boot`
`(println "Hello world!")`

Appreciate any help, even it it's just directing me how to resolve this myself. Normally I'd access the file and see what's error-ing, however the temp file is deleted before I can access it, and my code seems sound. The same exact code run in a Ubuntu environment with boot executes fine, which leads me to believe this is a Windows bug.

**Comment by micha** [comment]
This is sort of a Windows bug, but not really. The issue you are seeing is caused by the way you're invoking boot&mdash;boot requires its command line to be constructed a certain way when evaluating a "shebang" script, due to complications related to distinguishing boot tasks from file names.

We recently added the `-f,--file` boot option to fix this issue:

```
C:\Users\Mark_Antony\Developer
λ boot -f test.clj
```

Does that work for you?

**Comment by micha** [comment]
I forgot to say, you can see the generated temp file with the `-b,--boot-script` option to boot, like this:

```bash
$ boot -bf /tmp/test.clj |cat -n
```clojure
     1  (ns boot.user (:use boot.core boot.util boot.task.built-in))
     2
     3  (clojure.core/comment "start boot script")
     4
     5  (println "hello world!")
     6
     7  (clojure.core/comment "end boot script")
     8
     9  (clojure.core/let [boot?__1656__auto__ false] (clojure.core/if-not boot?__1656__auto__ (clojure.core/when-let [main__1657__auto__ (clojure.core/resolve (quote boot.user/-main))] (main__1657__auto__)) (boot.core/boot "boot.task.built-in/help")))
```

Note that the command line options you are using will affect the generated namespace, so you want to just add `-b` to the command line arguments you used when you got the error (so the generated namespace will be the same). If you want to see the source with nicer indentation and pretty-printing you may add the `-v,--verbose` boot option. (Whenever you run boot with `-v` option the generated script is pretty-printed, even without `-b`, so the line number of the exception will match up.)

**Comment by Ifiht** [comment]
`C:\Users\Mark_Antony\Developer\iris\scripts`
`λ boot -vf test.clj`
`Hello world!`

**THANK YOU!!!**

It works with that, sorry for missing such a simple fix but with the additional details, particularly printing out temp file specifics I should be able to handle bigger problems in the future. 

Who knows, maybe someday I could even help someone else in return.

Thanks again, issue fixed (user educated).
