### ISSUE TITLE
The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by p-adams** [boot-clj/boot#560]
Whenever I save an edit to `index.cljs.hl` I get the error sound, and when I look in the terminal I see:

    The process cannot access the file because it is being used by another process

I am running on a Windows 10 machine. If I kill the program and run `boot dev` again, the edit shows up in the browser. Any idea what might be causing this?

**Comment by mikera** [comment]
Did you solve this issue? I think I'm running into a similar one (using figwheel)

**Comment by tensor-programming** [comment]
got the same issue; any fix?

**Comment by matthewlal** [comment]
If you are using boot-http refer to this page https://github.com/pandeiro/boot-http/wiki/Using-with-windows
