### ISSUE TITLE
quiet flag for sift

### ISSUE THREAD

**Issue by mobileink** [boot-clj/boot#571]
The sift task seems always to print "Sifting output files...".  It would be nice to be able to suppress this:  sift --quiet

**Comment by arichiardi** [comment]
Yeah this makes sense, the string does not add value, it would be probably better to print out a longer message using `util/debug`.

**Comment by alandipert** [comment]
I don't see us doing this since none of the other builtins have a quiet option and I don't think we want to go down that road.

You could do something like this yourself though:

```clojure
(deftask quietly [] 
  (fn [next-task]
    (fn [fs]
      (with-redefs [boot.util/info (constantly nil)]
        (next-task fs)))))
```
and then

`(boot (quietly) (sift))` or `(boot (comp quietly sift))`

**Comment by alandipert** [comment]
Btw if anyone feels strongly about this, happy to have further discussion.
