### ISSUE TITLE
Using update causes NegatvieArrayException

### ISSUE THREAD

**Issue by Supernerd11** [boot-clj/boot#572]
When using the update task, I either get a segfault or a lot of NegativeArraySizeExceptions.
The logs are:
```
Could not transfer metadata boot:boot/maven-metadata.xml from/to maven-central (https://repo1.maven.org/maven2/): java.security.ProviderException: java.lang.NegativeArraySizeException
Could not transfer metadata boot:boot/maven-metadata.xml from/to clojars (https://clojars.org/repo/): java.security.ProviderException: java.lang.NegativeArraySizeException
#http://boot-clj.com
#Thu Jan 26 20:48:04 CET 2017
BOOT_CLOJURE_NAME=org.clojure/clojure
BOOT_VERSION=2.6.0
BOOT_CLOJURE_VERSION=1.7.0
``` 
When using `-u`, but a lot longer when using `-U`

**Comment by martinklepsch** [comment]
@Supernerd11 Hi, what operating system are you using? Maybe there's some different security configuration that causes this issue? Found [this on StackOverflow](https://stackoverflow.com/questions/41893845/java-lang-negativearraysizeexception-when-using-urlconnection) which describes a similar issue.

Also can you try with latest `BOOT_VERSION=2.7.2` and maybe `CLOJURE_VERSION=1.8.0` — you can set these in `boot.properties`.

Cheers

**Comment by seancorfield** [comment]
I thought the latest version was still `2.7.1`?

**Comment by martinklepsch** [comment]
@seancorfield whoops. You're right of course :) Updated my comment.

**Comment by martinklepsch** [comment]
I'll close this issue as there hasn't been any more information by the original reporter.
