### ISSUE TITLE
aot should throw exception if no param

### ISSUE THREAD

**Issue by mobileink** [boot-clj/boot#573]
The aot task requires one of --all or --namespace.  If neither is provided, either an exception should be thrown or a prominent warning message should be emitted.

**Comment by esanmiguelc** [comment]
This one seems simple enough, I can take a stab at it.

I'm thinking that it should be a warning; something along the lines of "aot will not be run - here's what you should do". Would it make sense for the task to actually just default to `--all`?

**Comment by mobileink** [comment]
I'm inclined to think there should be no default. If the use does not specify what is to be aot-compiled, the task should fail. to avoid surprises.

**Comment by alandipert** [comment]
Closing in favor of #576 where discussion can continue.
