### ISSUE TITLE
Ability to specify watched dirs in watch

### ISSUE THREAD

**Issue by arichiardi** [boot-clj/boot#583]
At the moment the dirs that you set with `set-env!` are watched but it would be great if we could specify them to `watch` directly therefore kind of decoupling from `build.boot`.

Ok I could use another tool altogether for watching but I so like boot and all my tasks are in it (but I don't set dirs with `set-env!`. :boot: 

:+1:

**Comment by arichiardi** [comment]
Mmm, I actually can use `boot -s` and specify whatever dir I want, but probably an option on `watch` would be still valuable, opinions?

**Comment by Deraen** [comment]
The tasks work with fileset, and fileset consists of paths in source/resource-paths. Also, many of tasks depend on files being in the classpath, which is also depends on source/resource-paths. And even if watch could create fileset based on the watched paths, classpath is global state and can't be easily changed like this.

So this is not as simple as just adding parameter to watch task and using that to select watch directories.

**Comment by arichiardi** [comment]
Ok so the easiest solution I found is basically:

`boot -B --source-paths "." watch -e "^mvn-target" sift -i "src" -i "pom.xml" mvn -W `pwd` -A "-Pboot-clj clean install"`

Closing this idea, rejected! 😀
