### ISSUE TITLE
`boot target -h` clears target/ as well as showing help

### ISSUE THREAD

**Issue by HakimCassimallyBBC** [boot-clj/boot#585]
e.g. 

```
$ boot build
... wait some time...
# Aha!  I wonder if I can preserve target/ to speed up the next build!

$ boot target -h
... some help output

$ find target/   # oh noes, it all got deleted!
```

In general, asking for help shouldn't also do things, so this feels like a bug.

**Comment by alandipert** [comment]
Agreed: `-h` shouldn't do anything. A PR would be most welcome.

**Comment by DonyorM** [comment]
I'm going to try and take this issue on. Would anyone be willing to point to me the function which clears out the target folder?

**Comment by DonyorM** [comment]
I am no longer seeing this behavior on my machine. Is this issue fixed?

**Comment by martinklepsch** [comment]
Also could not reproduce this issue, closing.
