### ISSUE TITLE
Move boot.aether/default-repositories to boot.pod

### ISSUE THREAD

**Issue by arichiardi** [boot-clj/boot#592]
Hello folks!

Sometimes you want to use it when creating pods, for instance I have recently used this way:

```
(def ^:dynamic
  *pod-env*
  "The pod env, it can be dynamically changed before the first task call
  to run-local if necessary."
  {:name "dynamodb-pod"
   :dependencies '[[arichiardi/boot-dynamodb "0.1.0-SNAPSHOT"]
                   [camel-snake-kebab "0.4.0" :scope "test"]
                   [com.amazonaws/DynamoDBLocal "[1.11,2.0)"]
                   #_[com.almworks.sqlite4java/sqlite4java "1.0.392"]]
   :local-repo (:local-repo (boot/get-env))
   :repositories  (conj @aether/default-repositories
                        ["dynamodb-local-oregon" {:url "https://s3-us-west-2.amazonaws.com/dynamodb-local/release"}])})

...make-pod...
```

There is probably a reason why it is not in `boot.core` or `boot.pod` already, but it would be nice to have somewhere without having to specify a dependency on `boot/aether`.

I mainly opened this issue to be told: "you can go this other way" :smile:

**Comment by hit023** [comment]
Could someone( @arichiardi ) please elaborate on the issue; to a newcomer?

**Comment by arichiardi** [comment]
So the issue is very simple, `default-repositories` should imho go in `boot.core` or at least in `boot.pod`, because user code would want to include it at configuration time without the need of importing an additional dependency (`boot.aether`) just for referring to a var.
This is a breaking change though, so I was looking for other opinions as well.

**Comment by Deraen** [comment]
In your example code you could just append custom repositories to `(:repositories (get-env))`?
I think it is best for pods to include the repositories configured for the project?

**Comment by arichiardi** [comment]
Uhm, not sure I get it, I am creating a pod there and need to specify a custom repo, which I am building, am I missing something?

**Comment by Deraen** [comment]
```
boot.user=> (:repositories (boot.core/get-env))
[["clojars" {:url "https://repo.clojars.org/", :username "bar", :password "foo"}] ["maven-central" {:url "https://repo1.maven.org/maven2"}]]
boot.user=> (conj (:repositories (boot.core/get-env)) ["dynamodb-local-oregon" {:url "https://s3-us-west-2.amazonaws.com/dynamodb-local/release"}])
[["clojars" {:url "https://repo.clojars.org/", :username "foo", :password "bar"}] ["maven-central" {:url "https://repo1.maven.org/maven2"}] ["dynamodb-local-oregon" {:url "https://s3-us-west-2.amazonaws.com/dynamodb-local/release"}]]
```

(Btw. it is quite dangerous solution to always add credentials to repository maps...)

**Comment by flyboarder** [comment]
closing as the correct way to do this is by modifying the env.
