### ISSUE TITLE
Running shell (make all) command after completion of (comp) task

### ISSUE THREAD

**Issue by gamecubate** [boot-clj/boot#593]
I have a Makefile and would like to invoke a ```make all``` shell command at the completion of my (boot) release task.

So I did this:
```
(deftask release []
  "Compile for release"
  (task-options! cljs {:optimizations :advanced})
  (comp
    (build)
    (sift :include #{#"index.html" #"css/*" #"js/app.js"})
    (target :dir #{"release"})
    (dosh "make" "all")))
```

That clearly fails as make seems to be invoked immediately, cutting off execution of the previous tasks, and is then followed by a java.lang.NullPointerException error.

I tried this with ```sh``` as well. In that case, the command fails immediately (no make execution) and is again followed by a java.lang.NullPointerException error.

**Comment by arichiardi** [comment]
Yep it makes sense because `sh` is not a task. In order to get what you want to achieve you have to wrap it into a ` with-pass-thru`. Also note that because of the fileset abstraction `make` won't see files created by boot unless you use the target task before it.

Hope it helps!
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by gamecubate** [comment]
Thanks @arichiardi.

In passing, I couldn't find documentation for ```with-pass-thru```.  Assuming this is part of the boot "vernacular". Will dig deeper.

**Comment by arichiardi** [comment]
No problem! Sample [here](https://github.com/Lambda-X/cljs-repl-web/blob/devel/build.boot#L288).

**Comment by gamecubate** [comment]
Great. I was just about to ask for one. :)

**Comment by gamecubate** [comment]
Actually... getting errors of the type ```Cannot run program "/usr/bin/make all": error=2, No such file or directory```. Here's my task:
```
(deftask release []
  "Compile for release"
  (task-options! cljs {:optimizations :advanced})
  (comp
    (build)
    (sift :include #{#"index.html" #"css/*" #"js/app.js"})
    (target :dir #{"release"})
    (with-pass-thru _
      (let [{:keys [exit out err]} (sh "/usr/bin/make all")]
        (println out)
        (when-not (zero? exit)
          (println err))))))
```

The Makefile is in the same directory as build.boot. Assuming that the task's cwd is not that from which `boot release``` was launched.

**Comment by arichiardi** [comment]
It should work, I am basically doing something similar (but with `dosh`) [here too](https://github.com/arichiardi/lumo-repros/blob/master/build.boot).

**Comment by gamecubate** [comment]
Great example. Will try it out immediately. Thanks!

**Comment by gamecubate** [comment]
This works very well. I later realized that same results could have been obtained by adding a ```boot release``` command to my Makefile target:
```
all:
  boot release
  scp ...
```
