### ISSUE TITLE
With-cp does not consider source/resource paths

### ISSUE THREAD

**Issue by arichiardi** [boot-clj/boot#596]
Probably a very easy fix on [this line](https://github.com/boot-clj/boot/blob/aea894de8bf3c9f637f48c9bcd0fd967221725ab/boot/core/src/boot/task/built_in.clj#L352).

Reminder 😁

**Comment by hit023** [comment]
Newcomer here: @alandipert  and @arichiardi , can I get some idea on what is wrong and how should a fix look like ?

**Comment by arichiardi** [comment]
Basically at the moment the code builds a string with resolved entries from the `: dependencies`, it should append also the stings contained in `:source-paths`, @alandipert can tell us if `asset-paths` is also necessary here 😀

**Comment by hit023** [comment]
`(apply str (interpose ":" relative-paths) (interpose ":" (into [ ] :source-paths)))`
Am I on the right track? I'm not really sure if :source-paths can be used like this.

**Comment by arichiardi** [comment]
@hit023 you are on the right track, you just need to grab `source-path` in a `let` binding before the line you posted (where you used it).
