### ISSUE TITLE
[Question] about boot pods, make-pod and pool-pod ?

### ISSUE THREAD

**Issue by azizzaeny** [boot-clj/boot#605]
what is the differences pod-pool and just pod ? 
docs says "is isolation", it is like threading ?

**Comment by azizzaeny** [comment]
and how to list all running pods ?

**Comment by martinklepsch** [comment]
Hey @azizzaeny 

`pods` — you can think of them as isolated Clojure runtimes, allowing you to load potentially conflicting versions of jars in different pods or "shielding" consumers of your tasks from dependency issues. Threading/parallelism isn't the primary concern of pods but you can of course run a `future` in a pod if that's what you need.

`pod-pools` are useful when you intend to use many pods (e.g. in combination with watch). They allow you to create a few pods up front and create new ones as you remove them from the pool.

Listing all pods — there is a var `boot.pod/pods` that can help you with that. Also check the [boot.pod docs](https://github.com/boot-clj/boot/blob/master/doc/boot.pod.md) which have some more detail on what's available.

I'll close this for now, if you have further questions don't hesitate to ask 🙂
