### ISSUE TITLE
Socket Repl

### ISSUE THREAD

**Issue by arichiardi** [boot-clj/boot#619]
This is a proposal for adding a new task for the socket repl.

There has been a lot of discussion around repls in #unrepl lately and I was thinking that there could be a new task for the socket REPL.

It would not do anything fancy, apart from setting correctly the [JVM options](https://clojure.org/reference/repl_and_main#_launching_a_socket_server) and exposing them as options.

Very simple achievement.

**Comment by martinklepsch** [comment]
@arichiardi https://github.com/boot-clj/boot/pull/549 isn't this what you're referring to?

**Comment by arichiardi** [comment]
Lol ok cool, today is the day I am doing it wrong :smile:
