### ISSUE TITLE
Discourse forum disabled?

### ISSUE THREAD

**Issue by bzg** [boot-clj/boot#630]
## Steps to reproduce

Go to http://hoplon.discoursehosting.net and check the error message.

It looks like the forum is not available and maybe the `README.md` should just not mention it?

**Comment by mudgen** [comment]
Bump?

**Comment by mudgen** [comment]
The link has been changed to point to a category/topic in ClojureVerse: https://clojureverse.org/c/projects/boot

More info here:  https://github.com/boot-clj/boot/issues/657
