### ISSUE TITLE
conda-forge package for boot-clj

### ISSUE THREAD

**Issue by abhi18av** [boot-clj/boot#642]
Hi guys,

I've been working on the [`conda-forge`](https://conda-forge.org/) package for `boot-clj` in this [PR](https://github.com/conda-forge/staged-recipes/pull/4035) 

I'm running into issues, could you help me get boot into the conda management space ?

**Comment by martinklepsch** [comment]
@abhi18av hey :) Reading the error in Travis it seems that the shasum you provided is not correct.

**Comment by abhi18av** [comment]
Hi @martinklepsch :)

I guess you mean, `circle-ci` logs since `travis-ci` takes a while to run the PRs. I've updated the `sha256` but now there's some error regarding this
```python
TypeError: 'NoneType' object is not callable
```

**Comment by martinklepsch** [comment]
I'm afraid I can't really help with this. Maybe there's some chat/forum for `conda-forge` that could help working out the details?

**Comment by martinklepsch** [comment]
Hey @abhi18av I hope you had success with this! I'll close this issue as there's nothing that can or must be done on Boot's end.
