### ISSUE TITLE
how to set java-source-path like in lein

### ISSUE THREAD

**Issue by jiacai2050** [boot-clj/boot#643]
I have tried this, but no luck.
```
(set-env!
 :source-paths #{"src"}
 :java-source-paths #{"java_src"}
 :dependencies '[.....])
```

https://github.com/boot-clj/boot/wiki/Boot-Environment
This document doesn't have some like `java-source-paths`, Is there anything I'm missing ? 
Thanks in advance.

**Comment by Deraen** [comment]
`:source-paths #{"src" "java_src"}`

and add `javac` task to your pipeline.

**Comment by jiacai2050** [comment]
Thanks
