### ISSUE TITLE
Discourse Website & Funding or More Love Somehow

### ISSUE THREAD

**Issue by mudgen** [boot-clj/boot#657]
It would be great if there was a working Discourse website for Boot.

The Discourse website is one of the first things mentioned in the README for boot.  The fact that the link to the Discourse website is broken makes it look/seem like Boot is abandoned -- and to a degree boot has been abandoned since the forum for it is gone and the documentation is out of date in that the link to the forum is broken and doesn't get fixed.

The broken link to Discourse is on every wiki webpage for boot.

Can we get the Discourse website back up?  Or can we remove it from the documentation?

I know it takes time and effort that is given freely to create and maintain this awesome peace of software.  It shouldn't just be like that. I think it should be funded and I think it can be.

I would like to see Boot development get financial backing from the newly created Clojurists Together (https://clojuriststogether.org/)

I would l love to see boot getting more attention for its forum, documentation, maintenance and development. 

Because of Boot I am joining a paid membership with Clojurists Together.

**Comment by martinklepsch** [comment]
I also noticed that yesterday. We could create topics on ClojureVerse.org if Alan and Micha don’t want to run a separate instance anymore.

**Comment by mudgen** [comment]
Martin, great idea about ClojureVerse.org if Alan and Micha don't want to host it.

**Comment by alandipert** [comment]
@martinklepsch 👍 for clojureverse, thank you in advance for setting that up. Everyone else feel free to fix Discourse links wherever you run across them.

The old discourse is locked up in some kind of credit card issue, not sure if it's ever coming back. If it does I'll look into posting it in some kind of archive mode so we at least have read-only access.

**Comment by plexus** [comment]
Hiya boot folks! Welcome to the ClojureVerse :)

Here's your category: https://clojureverse.org/c/projects/boot

You can also treat it as a mailing list: boot@lists.clojureverse.org.

@alandipert if you ever manage to get a database dump we might be able to import the old messages

**Comment by mudgen** [comment]
I made a pull request to fix the Discourse links, pointing to the new category on ClojureVerse.

**Comment by mudgen** [comment]
The links have now been fixed!
