### ISSUE TITLE
Applying to Clojurists Together For Funding

### ISSUE THREAD

**Issue by mudgen** [boot-clj/boot#659]
There are currently 103 outstanding issues for the boot project.

I would like to see these all get handled. 

Sometimes it takes a long time for issues to get resolved for the boot project. 

For example I made an issue about a month ago and there is no word of anything being done about it and I don't know when/if the problem will be fixed. The issue is here: [Issue 647](https://github.com/boot-clj/boot/issues/647) Though I know it isn't a big deal, just a warning.

Do you think some funding will help speed up the handling of issues for the boot project?  I signed up as a developer member and would vote for financial support of boot if someone can fix issues at a faster rate.

Are any maintainers/contributors of the boot project willing to apply for funding here: https://clojuriststogether.org/open-source/ ?

Are any of the maintainers/contributors willing to be paid to work on boot?

**Comment by alandipert** [comment]
I'm not personally motivated by Clojurists Together to work on boot more than I already do, but I am happy to support anyone else who would be.

If anyone with an interest runs across this thread, don't hesitate to get in touch with me on Slack or by e-mail, and we can coordinate applying.

**Comment by flyboarder** [comment]
Boot has applied many times to clojurists together, and we now have new maintainers.
