### ISSUE TITLE
Official Docker Repo

### ISSUE THREAD

**Issue by flyboarder** [boot-clj/boot#661]
Requesting an official repo for docker builds.

**Comment by Deraen** [comment]
I'd consider https://hub.docker.com/_/clojure/ official for Boot, or officially recommended anyway. I could add link on the readme.

**Comment by Deraen** [comment]
https://github.com/boot-clj/boot/commit/495fb36c4fb172446adf558cae890c7f6c10d181

**Comment by flyboarder** [comment]
That works!
