### ISSUE TITLE
Internal: Tooling to inline dependencies

### ISSUE THREAD

**Issue by martinklepsch** [boot-clj/boot#671]
We use some libraries by copying their Clojure source files into Boot jars. This is done to avoid dependency conflicts with anything users specify on their own. Currently this copying is done manually but it should probably get automated at some point.

via https://github.com/boot-clj/boot/issues/355#issuecomment-165494940

**Comment by benedekfazekas** [comment]
what are the blockers to use mranderson directly for this in boot?

**Comment by flyboarder** [comment]
Closing as the direction for how to handle dependencies internally has changed. 

There is a task for solving this problem for boot projects. https://github.com/boot-clj/boot/issues/671#issuecomment-419130667
