### ISSUE TITLE
Watch task should ignore files matching .gitignore patterns 

### ISSUE THREAD

**Issue by pandeiro** [boot-clj/boot#68]
Emacs users in particular will have their workflow frequently disrupted due to Emacs creating its weird temporary files in the source directory, which Boot cannot access, causing an Exception and the breaking of the Boot pipeline.

This, coupled with the unavailability of any [ClojureScript caching in boot-cljs](https://github.com/adzerk/boot-cljs/issues/22), makes for fairly slow going when working with something akin to the boot-cljs-example.

@alandipert mentioned that this feature may have already been implemented in Boot at one point: could we revisit this?

**Comment by martinklepsch** [comment]
:+1:

**Comment by micha** [comment]
I think we should wait for this one. I don't think it's so bad to require that users configure their editors to store scratch files elsewhere.

**Comment by nashbridges** [comment]
Possibly related issue: file watcher triggers extra event if I create a git commit, i.e. write `.git/COMMIT_EDITMSG`. I use `(speak)`, thus hear a sound when I begin to writing a commit message, which is a bit weird.
