### ISSUE TITLE
Async pod refresh(?) throws ClassNotFoundException sometimes

### ISSUE THREAD

**Issue by seancorfield** [boot-clj/boot#715]
As mentioned on Slack, this is a seemingly random failure that manifests in a number of different ways.

### Problem Description

When running a large, complex Boot task pipeline, sometimes a random compiler error or ClassNotFoundException is thrown asynchronously -- which seems to suggest a pod-refresh or at least pod-related problem.

See for example: https://gist.github.com/seancorfield/f29bdb948a2a533c14a07ff6ffd6548a

Sometimes the error is a compilation error (in dynapath.clj seems to be the most common, but when using Clojure 1.9.0 it was often a problem loading the instant18 file -- with a "stream closed" error instead).

### Steps to reproduce

Very hard to reproduce. It happens randomly. Re-running the exact same Boot task pipeline may well succeed, or it may fail with the same or even a different error.

### Platform details

Platform (macOS, Linux, Windows): macOS
Platform version: 10.12.6
JRE/JDK version (`java -version`): 

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

### Boot details

Boot version (2.7.1): 2.7.2
`build.boot` present? (yes/no): yes (massive, complex one)
`~/.boot/profile` present? (yes/no): yes (just has repo config in it)
Task name? (if applicable): Happens with various tasks, mostly in pods related to boot-test but I've seen it coming from other pod/with-eval-in expressions.

Please also provide the contents of `build.boot` and `~/.boot/profile` (if applicable).

Sorry, lots of proprietary stuff in our `build.boot` file.

**Comment by seancorfield** [comment]
Here's another stack trace, this time complaining (incorrectly) that `dynapath.clj` has a syntax error: https://gist.github.com/seancorfield/e6005eb6361fdaeaee00f522abd0e599

**Comment by alandipert** [comment]
@seancorfield Do you know about how many pods are running when it crashes? You could find out by adding `(show :list-pods true)` to your pipeline.

I agree it smells like pods, and I wonder in particular if it's some kind of contention related to pods that doesn't manifest with fewer of them.

**Comment by seancorfield** [comment]
This is what shows up as the pipeline starts:
```
boot.pod
boot.pod
boot.pod
boot.pod
boot.pod
boot.pod
boot.pod
clojure.core
core
worker
```

**Comment by seancorfield** [comment]
And here's what shows up at the end of the pipeline:
```
boot.pod
boot.pod
boot.pod
boot.pod
boot.pod
boot.pod
boot.pod
boot.pod
boot.pod
boot.pod
boot.pod
boot.pod
clojure.core
core
worker
```

**Comment by seancorfield** [comment]
Closing due to lack of feedback/interest.
