### ISSUE TITLE
--no-color option

### ISSUE THREAD

**Issue by Deraen** [boot-clj/boot#74]
It's easy to add colors to output of tasks using `boot.from.io.aviso.ansi`-ns.

There should be global boot option which can be used to disable all colors in output.

Perhaps the easiest way would be to add dynamic var like *verbosity* and use that to apply [strip-ansi](https://github.com/boot-clj/boot/blob/master/boot/pod/src/boot/from/io/aviso/ansi.clj#L80) to output string when no colors are desired.

Other way would be to only add codes conditionally.
But perhaps there is some pros to using strip-ansi:
- No matter what's the source of colors codes, it'll work

**Comment by micha** [comment]
This sounds great to me!

**Comment by micha** [comment]
@Deraen I like the `strip-ansi` approach, but i think we can also benefit from a little library of functions in boot that tasks can use to print messages nicely formatted. Do you have any ideas for something like that?
