### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by bbatsov** [boot-clj/boot#741]
I know there are big plans for Boot 3.0, but in the mean time it'd be really great if you cut simply a 2.8.3 release that features the updated nREPL and REPLy. This is a tiny change, but it improves the end user experience a lot for everyone using an nREPL powered editor. It's not like people can't override the deps themselves and use the latest versions, but I think that's pretty poor user experience overall. 

I also think that #738 should probably be included in such a small release. It's great that there are ambitious plans for the future, but in the mean time a tiny set of changes can make a lot of difference for many users.

**Comment by flyboarder** [comment]
2.8.3 is now out
