### ISSUE TITLE
Eliminate dependency graph cycles before sorting dependencies

### ISSUE THREAD

**Issue by Deraen** [boot-clj/boot#75]
`jars-in-dep-order` has some problems with some projects. `jars-dep-graph` works but topo-sort returns nil.

https://github.com/boot-clj/boot/blob/d2c45de6d7335002f4b18577da05f662768afda8/boot/aether/src/boot/aether.clj#L135

**Comment by Deraen** [comment]
`[clj-pdf "1.11.21"]` seems to be the dependency causing problems

**Comment by martinklepsch** [comment]
Had similar problems before and didn't depend on `cli-pdf`.

**Comment by micha** [comment]
This probably indicates that there are circular dependencies in the dep graph, which defeats kahn's topological sort algorithm.

**Comment by Deraen** [comment]
Yeah: https://issues.apache.org/jira/browse/BATIK-1098

**Comment by micha** [comment]
This doesn't seem to be a pressing issue anymore.
