### ISSUE TITLE
IncompatibleClassChangeError  Found class jline.Terminal, but interface was expected

### ISSUE THREAD

**Issue by SanAngeloMike** [boot-clj/boot#84]
OSX 10.9.5

Mikes-2:clj miked$ boot -v
Boot App Version: 2.0.0-rc4
Boot Lib Version: 2.0.0-rc6
Clojure Version:  1.6.0

Mikes-2:clj miked$ boot repl
nREPL server started on port 60766 on host 0.0.0.0 - nrepl://0.0.0.0:60766
REPL-y 0.3.5, nREPL 0.2.6
Clojure 1.6.0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_25-b17
        Exit: Control+D or (exit) or (quit)
    Commands: (user/help)
        Docs: (doc function-name-here)
              (find-doc "part-of-name-here")
Find by Name: (find-name "part-of-name-here")
      Source: (source function-name-here)
     Javadoc: (javadoc java-object-or-class-here)
    Examples from clojuredocs.org: [clojuredocs or cdoc]
              (user/clojuredocs name-here)
              (user/clojuredocs "ns-here" "name-here")
IncompatibleClassChangeError Found class jline.Terminal, but interface was expected
	jline.console.ConsoleReader.<init> (ConsoleReader.java:230)
	jline.console.ConsoleReader.<init> (ConsoleReader.java:221)
	jline.console.ConsoleReader.<init> (ConsoleReader.java:213)
	reply.reader.simple-jline/setup-console-reader (simple_jline.clj:71)
	reply.reader.simple-jline/get-input-line (simple_jline.clj:109)
	clojure.lang.Atom.swap (Atom.java:37)
	clojure.core/swap! (core.clj:2232)
	reply.reader.simple-jline/safe-read-line (simple_jline.clj:148)
	reply.reader.simple-jline/safe-read-line (simple_jline.clj:155)
	clojure.core/apply (core.clj:626)
	clojure.core/partial/fn--4228 (core.clj:2468)
	reply.parsing/parsed-forms (parsing.clj:60)
Bye for now!

**Comment by micha** [comment]
This looks like an issue with dependencies. Can you paste the output of `boot show -d` for your project please?

**Comment by SanAngeloMike** [comment]
Hi Micha,

>> This looks like an issue with dependencies. Can you paste the output of boot
show -d for your project please?

Wow, talk about customer service! Thanks so much for being so responsive
and most of all, for creating what looks like a fantastic system!

Here you go:

mikes-2:hop2it-02 miked$ boot show -d

java.lang.RuntimeException: Unable to resolve symbol: show in this context,
compiling:(/Users/miked/clj/hop2it-02/.boot/tmp/20378/_COLON_tailrecursion.boot_SLASH_bootscript/dir.tmp/tailrecursion/boot/user.clj:54:33)

↳ Caused by: Unable to resolve symbol: show in this context

mikes-2:hop2it-02 miked$


Mike Doffing

**Comment by SanAngeloMike** [comment]
HI Micha,

I just remembered. To get things working I reverted back to 1.1.1. I still
get a similar error. Note that the boot -show -d   was from 1.1.1.


mikes-2:hop2it-02 miked$ boot repl

nREPL server started on port 61242 on host 127.0.0.1 - nrepl://
127.0.0.1:61242

REPL-y 0.3.0

Clojure 1.6.0

        Exit: Control+D or (exit) or (quit)

    Commands: (user/help)

        Docs: (doc function-name-here)

              (find-doc "part-of-name-here")

Find by Name: (find-name "part-of-name-here")

      Source: (source function-name-here)

     Javadoc: (javadoc java-object-or-class-here)

    Examples from clojuredocs.org: [clojuredocs or cdoc]

              (user/clojuredocs name-here)

              (user/clojuredocs "ns-here" "name-here")

IncompatibleClassChangeError Found class jline.Terminal, but interface was
expected

jline.console.ConsoleReader.<init> (ConsoleReader.java:228)

jline.console.ConsoleReader.<init> (ConsoleReader.java:219)

jline.console.ConsoleReader.<init> (ConsoleReader.java:211)

reply.reader.simple-jline/setup-console-reader (simple_jline.clj:69)

reply.reader.simple-jline/get-input-line (simple_jline.clj:107)

clojure.lang.Atom.swap (Atom.java:37)

clojure.core/swap! (core.clj:2232)

reply.reader.simple-jline/safe-read-line (simple_jline.clj:146)

reply.reader.simple-jline/safe-read-line (simple_jline.clj:153)

clojure.core/apply (core.clj:626)

clojure.core/partial/fn--4228 (core.clj:2468)

reply.parsing/parsed-forms (parsing.clj:60)

Bye for now!

mikes-2:hop2it-02 miked$

mikes-2:hop2it-02 miked$

mikes-2:hop2it-02 miked$

mikes-2:hop2it-02 miked$ boot show -d

java.lang.RuntimeException: Unable to resolve symbol: show in this context,
compiling:(/Users/miked/clj/hop2it-02/.boot/tmp/20378/_COLON_tailrecursion.boot_SLASH_bootscript/dir.tmp/tailrecursion/boot/user.clj:54:33)

↳ Caused by: Unable to resolve symbol: show in this context

mikes-2:hop2it-02 miked$

mikes-2:hop2it-02 miked$

mikes-2:hop2it-02 miked$

mikes-2:hop2it-02 miked$

mikes-2:hop2it-02 miked$

mikes-2:hop2it-02 miked$ boot -h

java.lang.RuntimeException: Unable to resolve symbol: -h in this context,
compiling:(/Users/miked/clj/hop2it-02/.boot/tmp/20430/_COLON_tailrecursion.boot_SLASH_bootscript/dir.tmp/tailrecursion/boot/user.clj:54:33)

↳ Caused by: Unable to resolve symbol: -h in this context

mikes-2:hop2it-02 miked$ boot

tailrecursion/boot 1.1.1: http://github.com/tailrecursion/boot


Usage: boot OPTS task ...

       boot OPTS [task arg arg] ...

       boot OPTS [help task]

**Comment by micha** [comment]
You reverted to version 1.1.1 of which dependency? What happens if you make a new directory with nothing in it and try to start a repl there?

```
mkdir foo
cd foo
boot repl
```

If that works then it must be something in your build.boot file or your project dependencies.

**Comment by SanAngeloMike** [comment]
Hi Micha,

>> You reverted to version 1.1.1 of which dependency?

Boot itself.

Thanks again for getting back so quickly. Here's the results:

Mikes-2:temp1 miked$ boot :strap > build.boot
Retrieving org/apache/httpcomponents/httpcore/4.3/httpcore-4.3.jar from http://repo1.maven.org/maven2/
Retrieving org/apache/httpcomponents/httpmime/4.3.1/httpmime-4.3.1.jar from http://repo1.maven.org/maven2/
Retrieving org/apache/httpcomponents/httpclient/4.3.1/httpclient-4.3.1.jar from http://repo1.maven.org/maven2/
Retrieving commons-codec/commons-codec/1.8/commons-codec-1.8.jar from http://repo1.maven.org/maven2/
Retrieving tailrecursion/ancient-clj/0.1.7/ancient-clj-0.1.7.jar from http://clojars.org/repo/
Retrieving clj-http/clj-http/0.7.8/clj-http-0.7.8.jar from http://clojars.org/repo/
Mikes-2:temp1 miked$ 
Mikes-2:temp1 miked$ boot --no-profile repl
java.lang.RuntimeException: Unable to resolve symbol: --no-profile in this context, compiling:(/Users/miked/clj/temp1/.boot/tmp/22573/_COLON_tailrecursion.boot_SLASH_bootscript/dir.tmp/tailrecursion/boot/user.clj:12:33)
↳ Caused by: Unable to resolve symbol: --no-profile in this context
Mikes-2:temp1 miked$ 

Mike

**Comment by SanAngeloMike** [comment]
Whoops, I left off the first part of that.

Mikes-2:clj miked$ mkdir temp1
Mikes-2:clj miked$ cd temp1
Mikes-2:temp1 miked$ boot --no-profile repl
boot: script file not found: build.boot

Usage: boot :strap
       boot [arg ...]
       boot <scriptfile.boot> [arg ...]

Create a minimal boot script: `boot :strap > build.boot`

Mikes-2:temp1 miked$

**Comment by SanAngeloMike** [comment]
Hi Micha,

OK, I got it going by doing this:

Mikes-2:temp1 miked$ boot lein-generate 
Mikes-2:temp1 miked$ lein repl
nREPL server started on port 59225 on host 127.0.0.1 - nrepl://127.0.0.1:59225
REPL-y 0.3.5, nREPL 0.2.6
Clojure 1.6.0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_25-b17
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

user=> (* 6 7 8)
336
user=>

Thanks for your help and especially for a fascinating set of libraries.

Mike

**Comment by SanAngeloMike** [comment]
Aaarrgh! Here it is with boot repl, not lein repl.

Mikes-2:temp1 miked$ boot repl
nREPL server started on port 59245 on host 127.0.0.1 - nrepl://127.0.0.1:59245
REPL-y 0.3.0
Clojure 1.6.0
        Exit: Control+D or (exit) or (quit)
    Commands: (user/help)
        Docs: (doc function-name-here)
              (find-doc "part-of-name-here")
Find by Name: (find-name "part-of-name-here")
      Source: (source function-name-here)
     Javadoc: (javadoc java-object-or-class-here)
    Examples from clojuredocs.org: [clojuredocs or cdoc]
              (user/clojuredocs name-here)
              (user/clojuredocs "ns-here" "name-here")
IncompatibleClassChangeError Found class jline.Terminal, but interface was expected
	jline.console.ConsoleReader.<init> (ConsoleReader.java:228)
	jline.console.ConsoleReader.<init> (ConsoleReader.java:219)
	jline.console.ConsoleReader.<init> (ConsoleReader.java:211)
	reply.reader.simple-jline/setup-console-reader (simple_jline.clj:69)
	reply.reader.simple-jline/get-input-line (simple_jline.clj:107)
	clojure.lang.Atom.swap (Atom.java:37)
	clojure.core/swap! (core.clj:2232)
	reply.reader.simple-jline/safe-read-line (simple_jline.clj:146)
	reply.reader.simple-jline/safe-read-line (simple_jline.clj:153)
	clojure.core/apply (core.clj:626)
	clojure.core/partial/fn--4228 (core.clj:2468)
	reply.parsing/parsed-forms (parsing.clj:60)
Bye for now!
Mikes-2:temp1 miked$

**Comment by alandipert** [comment]
It looks like you're using boot version 1.x from [tailrecursion/boot](https://github.com/tailrecursion/boot), but this repo is for Boot 2.0 which is a nearly complete (and backward incompatible) rewrite.

Can you try [installing Boot 2](https://github.com/boot-clj/boot#install) and letting us know if that lets you start a REPL without error?

If you're using Boot 1 for [Hoplon](http://hoplon.io/), as we still are pending porting Hoplon to boot2, you can keep it around by renaming old boot to `boot1`.

We realize this is confusing, sorry for the inconvenience!

**Comment by SanAngeloMike** [comment]
Hi Alan,

Thanks for getting back to me.

I renamed boot 1.1.1 and then downloaded and installed the latest.

Mikes-2:hop2it-01 miked$ boot -V
#https://github.com/boot-clj/boot
#Thu Jan 15 23:12:44 EST 2015
BOOT_CLOJURE_VERSION=1.6.0
BOOT_VERSION=2.0.0-rc6

By the way, I saw an rc7 mentioned in another post but this is still rc6. Is the later version available?

Here's what happened next:

Mikes-2:clj miked$ boot repl 
nREPL server started on port 55419 on host 0.0.0.0 - nrepl://0.0.0.0:55419
REPL-y 0.3.5, nREPL 0.2.6
Clojure 1.6.0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_25-b17
        Exit: Control+D or (exit) or (quit)
    Commands: (user/help)
        Docs: (doc function-name-here)
              (find-doc "part-of-name-here")
Find by Name: (find-name "part-of-name-here")
      Source: (source function-name-here)
     Javadoc: (javadoc java-object-or-class-here)
    Examples from clojuredocs.org: [clojuredocs or cdoc]
              (user/clojuredocs name-here)
              (user/clojuredocs "ns-here" "name-here")
IncompatibleClassChangeError Found class jline.Terminal, but interface was expected
	jline.console.ConsoleReader.<init> (ConsoleReader.java:230)
	jline.console.ConsoleReader.<init> (ConsoleReader.java:221)
	jline.console.ConsoleReader.<init> (ConsoleReader.java:213)
	reply.reader.simple-jline/setup-console-reader (simple_jline.clj:71)
	reply.reader.simple-jline/get-input-line (simple_jline.clj:109)
	clojure.lang.Atom.swap (Atom.java:37)
	clojure.core/swap! (core.clj:2232)
	reply.reader.simple-jline/safe-read-line (simple_jline.clj:148)
	reply.reader.simple-jline/safe-read-line (simple_jline.clj:155)
	clojure.core/apply (core.clj:626)
	clojure.core/partial/fn--4228 (core.clj:2468)
	reply.parsing/parsed-forms (parsing.clj:60)
Bye for now!
------------------------------------------

Note that boot repl -h works fine:

Mikes-2:clj miked$ boot repl -h
Start a REPL session for the current project.

If no bind/host is specified the REPL server will listen on 0.0.0.0 and the
client will connect to 127.0.0.1.

If no port is specified the server will choose a random one and the client
will read the .nrepl-port file and use that.

The *default-middleware* and *default-dependencies* atoms in the boot.repl-server
namespace contain vectors of default REPL middleware and REPL dependencies to
be loaded when starting the server. You may modify these in your build.boot
file.

Options:
  -h, --help            Print this help info.
  -s, --server          Start REPL server only.
  -c, --client          Start REPL client only.
  -C, --no-color        Disable ANSI color output in client.
  -e, --eval EXPR       Set the form the client will evaluate in the boot.user ns to EXPR.
  -b, --bind ADDR       Set the address server listens on to ADDR.
  -H, --host HOST       Set the host client connects to to HOST.
  -i, --init PATH       Set the file to evaluate in the boot.user ns to PATH.
  -I, --skip-init       Skip default client initialization code.
  -p, --port PORT       Set the port to listen on and/or connect to to PORT.
  -n, --init-ns NS      Set the initial REPL namespace to NS.
  -m, --middleware SYM  Conj SYM onto the REPL middleware vector.
  -x, --handler SYM     Set the REPL handler (overrides middleware options) to SYM.
Mikes-2:clj miked$
--------------------------------------

Also, when I run it from a sub-dir with a build.boot file I get a different error:

Mikes-2:hop2it-02 miked$ ls
README.md	build.boot	 project.clj	resources 	src		target
Mikes-2:hop2it-02 miked$ 
Mikes-2:hop2it-02 miked$ boot repl
java.lang.RuntimeException: No reader function for tag tailrecursion.boot.core/version
                      ...                
 clojure.core/read-string  core.clj: 3497
boot.util/read-string-all  util.clj:  146
          boot.main/-main  main.clj:  111
                      ...                
         boot.App.runBoot  App.java:  225
            boot.App.main  App.java:  317
Mikes-2:hop2it-02 miked$
------------------------------------------

THanks for the warning about boot 2.0.0 and Hoplon. I'll keep using 1.1.1

**Comment by micha** [comment]
Grasping at straws, but is [this stackoverflow.com thread](http://stackoverflow.com/questions/19466950/sbt-0-13-0-jline-incompatibility-detected) relevant?

**Comment by SanAngeloMike** [comment]
Thanks for getting back to me. I'll dig into this tomorrow and get back to
you.

**Comment by micha** [comment]
I think this was resolved...? If not feel free to reopen or maybe create a new ticket!
