### ISSUE TITLE
Illegal character error when invoking getting started boot command-line in Windows

### ISSUE THREAD

**Issue by asampal** [boot-clj/boot#85]
Using Windows 8.1, with Msys

When I follow the sample project boot invocation from the readme:
`boot -s src -d me.raynes/conch:0.8.0 -- pom -p my-project -v 0.1.0 -- jar -M Foo=bar -- install`
the result is:

```
java.net.URISyntaxException: Illegal character in path at index 2: ..\dev\msys64\tmp\boot.user462574277576676674.clj
     index: 2
     input: "..\\dev\\msys64\\tmp\\boot.user462574277576676674.clj"
    reason: "Illegal character in path"
                  ...
boot.file/relative-to  file.clj:  80
   boot.main/-main/fn  main.clj: 137
      boot.main/-main  main.clj: 134
                  ...
     boot.App.runBoot  App.java: 225
        boot.App.main  App.java: 317
```
I'm assuming this is a problem specific to Windows and might not get any attention soon, but figured it should be tracked in any case.

**Comment by asampal** [comment]
I'm still getting the same exception (line numbers are different):

```
java.net.URISyntaxException: Illegal character in path at index 2: ..\dev\msys64\tmp\boot.user8074567052377619436.clj
     index: 2
     input: "..\\dev\\msys64\\tmp\\boot.user8074567052377619436.clj"
    reason: "Illegal character in path"
                  ...
boot.file/relative-to  file.clj:  80
   boot.main/-main/fn  main.clj: 140
      boot.main/-main  main.clj: 137
                  ...
     boot.App.runBoot  App.java: 226
        boot.App.main  App.java: 320
```

**Comment by gzmask** [comment]
I am getting this on windows 7:

←[1;31mjava.net.URISyntaxException←[m: ←[31mIllegal character in path at ind
t.user96864699030540486.clj←[m
     ←[1mindex←[m: 2
     ←[1minput←[m: "..\\Users\\lei203\\AppData\\Local\\Temp\\boot.user968646
    ←[1mreason←[m: "Illegal character in path"
                  ...←[m  ←[32m             ←[m
←[33mboot.file/←[1;33mrelative-to←[m  ←[32mfile.clj:  80←[m
   ←[33mboot.main/-main/←[1;33mfn←[m  ←[32mmain.clj: 140←[m
      ←[33mboot.main/←[1;33m-main←[m  ←[32mmain.clj: 137←[m
                  ...←[m  ←[32m             ←[m
     ←[37mboot.App.runBoot←[m  ←[32mApp.java: 226←[m
        ←[37mboot.App.main←[m  ←[32mApp.java: 320←[m
PS D:\temp\embodier-stl-slicer> boot build
←[1;31mjava.net.URISyntaxException←[m: ←[31mIllegal character in path at ind
t.user7031135787541502490.clj←[m
     ←[1mindex←[m: 2
     ←[1minput←[m: "..\\Users\\lei203\\AppData\\Local\\Temp\\boot.user703113
    ←[1mreason←[m: "Illegal character in path"
                  ...←[m  ←[32m             ←[m
←[33mboot.file/←[1;33mrelative-to←[m  ←[32mfile.clj:  80←[m
   ←[33mboot.main/-main/←[1;33mfn←[m  ←[32mmain.clj: 140←[m
      ←[33mboot.main/←[1;33m-main←[m  ←[32mmain.clj: 137←[m
                  ...←[m  ←[32m             ←[m
     ←[37mboot.App.runBoot←[m  ←[32mApp.java: 226←[m
        ←[37mboot.App.main←[m  ←[32mApp.java: 320←[m

**Comment by lypanov** [comment]
@asampal @gzmask are you on the latest version? I'm not sure this test has been actually released.

**Comment by asampal** [comment]
I'm not - duh. Any ETA?

**Comment by lypanov** [comment]
To install
  1. Download the GitHub Windows app
  2. Click the clone button on the boot page
  3. Right click on the boot repo in GitHub and do "open in file explorer"
  4. Open a terminal and navigate to the directory
  5. cd into boot/boot/pod and enter lein install

Not tested with latest revision but worked for me a few days back :)

**Comment by gzmask** [comment]
@lypanov Thanks! This solves my problem!
