### ISSUE TITLE
aot task throws exception in 2.0.0-rc6

### ISSUE THREAD

**Issue by sparkofreason** [boot-clj/boot#91]
clojure.lang.Compiler$CompilerException: java.lang.RuntimeException: No such namespace: util, compiling:(NO_SOURCE_PATH:0:0)
             java.lang.RuntimeException: No such namespace: util
                                ...                                        
                  clojure.core/eval                          core.clj: 2927
                  boot.pod/eval-in*                           pod.clj:  203
                                ...                                        
                  boot.pod/eval-in*                           pod.clj:  206
     boot.task.built-in/fn/fn/fn/fn                      built_in.clj:  434
     boot.task.built-in/fn/fn/fn/fn                      built_in.clj:  233
  deraen.boot-cljx/eval276/fn/fn/fn                     boot_cljx.clj:   27
                boot.core/run-tasks                          core.clj:  623
                                ...                                        
              boot.user/eval1702/fn  boot.user5216483693988363082.clj:   15
clojure.core/binding-conveyor-fn/fn                          core.clj: 1910

Removing the (util/info ...) call at line 437 of built_in.clj makes this go away, but that doesn't seem like an acceptable fix.

**Comment by martinklepsch** [comment]
@alandipert just fixed this I believe #90

**Comment by martinklepsch** [comment]
There is no release yet so if you need it now I'd recommend building it yourself:
```
> clone git@github.com:boot-clj/boot.git 
> cd boot/boot/core
> lein install
```

**Comment by sparkofreason** [comment]
Verified.

**Comment by alandipert** [comment]
Thanks for the report, this will go out with RC7 probably within the next few days.

Because of this I also created #92, would appreciate any thoughts folks might have on what we can do to prevent silly regressions like this moving forward.
