### ISSUE TITLE
built-ins test suite

### ISSUE THREAD

**Issue by alandipert** [boot-clj/boot#92]
We should test every builtin to some degree.  The builtins exercise most of the boot API and also demonstrate patterns that task authors can emulate, so it would be great to have some extra assurances around their proper operation.

#90 is an example of a regression that came up today that a very simple test would have caught.

It's not clear to me now what the best way to organize tests like this should be.  Should we have a directory of test projects?  Should we drive the tasks programmatically, without test/example projects?

**Comment by martinklepsch** [comment]
I think in general establishing some sort of pattern to test tasks would be a good step.
I'm not sure though how exactly that could work. Maybe there could be tasks that "validate the fileset" after some function ran?

**Comment by alandipert** [comment]
I like that concept a lot - extending it, I can imagine using test.check generators to generate re/source filesets and maybe even task compositions.

**Comment by micha** [comment]
[Check it out!](https://travis-ci.org/boot-clj/boot)

**Comment by arichiardi** [comment]
I like it!
