### ISSUE TITLE
Windows cmd console shows ANSI escape characters

### ISSUE THREAD

**Issue by wheineman** [boot-clj/boot#99]
Running under Windows 8 cmd console, I see artifacts from the ANSI escape characters:

C:\Users\heinemanwp\MyApps>boot repl
nREPL server started on port 62857 on host 0.0.0.0 - nrepl://0.0.0.0:62857
REPL-y 0.3.5, nREPL 0.2.6
Clojure 1.6.0
Java HotSpot(TM) Client VM 1.7.0_45-b18
        Exit: Control+D or (exit) or (quit)
    Commands: (user/help)
        Docs: (doc function-name-here)
              (find-doc "part-of-name-here")
Find by Name: (find-name "part-of-name-here")
      Source: (source function-name-here)
     Javadoc: (javadoc java-object-or-class-here)
    Examples from clojuredocs.org: [clojuredocs or cdoc]
              (user/clojuredocs name-here)
              (user/clojuredocs "ns-here" "name-here")
boot.user=> (* 6 7)
←[34m42←[m
boot.user=> (println "hello")
hello
←[34mnil←[m
boot.user=> (quit)
Bye for now!

**Comment by micha** [comment]
There is a `--no-colors` option to boot itself, and a `--no-color` option for the `repl` task that you can use to completely disable all ansi colors.

**Comment by lypanov** [comment]
My personal Windows console deals with this fine (PowerShell via ConEmu) so I'd really not like to have a default. -C seems fine as a work around.

**Comment by micha** [comment]
I'll close this ticket for now. Please feel free to reopen if the `-C` doesn't solve the problem or isn't a good solution to the problem.

**Comment by schmir** [comment]
people paste these escape codes here on most of the bug reports regarding windows. I do think it should be turned off by default on windows. Having an environment variable to turn it on again would probably also work for @lypanov?

**Comment by schmir** [comment]
In other words it's a bad default on windows and leads to a bad first experience when trying boot on windows.

**Comment by lypanov** [comment]
Yes, that or a new "turn on" setting would be fine @schmir. It's a pretty specific setup required to actually have it work.

**Comment by schmir** [comment]
The default is now to turn them off on windows. You can set the environment variable BOOT_COLOR=1 in order to turn it on again.

There's still a problem when exceptions occur in the repl. They are printed with escape codes, but that's another issue.
